### ISSUE TITLE
Wire up log_event_data 

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1010]
At this time, we're using the custom events pipeline to send log event data. Once the collector team has the log event pipeline ready, we need to change references to custom events within log forwarding to point to the log event endpoint instead.

## Known Tasks 
* Replace calls to `custom_insights_events` within `lib/new_relic/agent/log_event_aggregator.rb`
* Add tests for `event_harvest_config.harvest_limits.log_event_data` coming back in the response

Blocked until collector team's work is complete. It's sufficient to use the custom insights events pipeline for the EAP.

**Comment by kaylareopelle** [comment]
@angelatan2  - This issue isn't ready for poker until we're aware of the other changes that need to be made to fully connect our code to the correct collector reporting endpoint. That requires the collector team to finish setting up the log event pipeline.

**Comment by jasonrclark** [comment]
@kaylareopelle Yeah this can be considered complete. The use of custom events actually went away a loooooong time ago on the agent branch so with the harvest limits there I don't think there are any other changes we're looking for from the collector team.
