### ISSUE TITLE
Include HTTP headers with all Transactions

### ISSUE THREAD

**Issue by jamesarosen** [newrelic/newrelic-ruby-agent#1029]
### Is your feature request related to a problem? Please describe.

Yes? The Ruby agent lacks features that the JS agent has, so we're missing data.

### Feature Description

The Node JS agent [supports](https://github.com/newrelic/node-newrelic/blob/91967dd5cd997aa283b8aa0b2fdacc2a5f10a628/test/unit/header-attributes.test.js#L31) sending all HTTP headers via the `allow_all_headers` flag. This results in attributes like `request.headers.accept` showing up as attributes on all Transactions. See [New Relic Data Dictionary](https://docs.newrelic.com/attribute-dictionary/?event=Transaction) for more on those attributes.

### Describe Alternatives

We can add each header as a custom attribute. This works fine, but it's a fair bit of extra code we have to maintain.

### Priority
Really Want

**Comment by elucus** [comment]
Hi @jamesarosen thanks for the suggestion. We try and maintain feature parity with our agents and several agents have implemented support for capturing HTTP headers. We will add this to our backlog.

**Comment by angelatan2** [comment]
Let's size this story and then assess next steps.

**Comment by kaylareopelle** [comment]
Link to ticket where we worked on logging HTTP headers: https://github.com/newrelic/newrelic-ruby-agent/pull/1839

**Comment by fallwith** [comment]
Hi @jamesarosen, thanks again for suggesting this feature! The PR to introduce a new `allow_all_headers` config option is now in our `dev` branch and is slated to go out with in our next agent version.

**Comment by jamesarosen** [comment]
Nice work, team 👏

**Comment by fallwith** [comment]
Version 9.4.0 of the agent is now available from RubyGems.org.

[CHANGELOG](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CHANGELOG.md)
