### ISSUE TITLE
MLT: Confirm MLT is automatically associated with all covered Rails methods

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1073]
The `method_level_telemetry` branch should be updated so that MLT metrics are automatically included alongside of all existing method level metrics that are gathered in a Rails application context. NOTE: see the existing `TODO: MLT` comments in the source code for suggested entrypoints for this effort.

**Comment by angelatan2** [comment]
We reviewed the scope of the existing Rails instrumented methods and agree that they are sufficient for Code level metrics.  We look forward to hearing from the community if there is additional scope needed after our release of this feature.

**Comment by fallwith** [comment]
For posterity if anyone looks over this issue in the future...

Code level metrics will appear in the IDE when a class file has been loaded that meets any one of the following 3 criteria:

- The class is a controller class
- The class is a job class
- The class has manually applied New Relic method traces

Here are our thoughts on each Rails library:

- **ActiveController**: CLM will be reported for all controller methods that generate ActiveSupport::Notifications content (all CRUD and/or routed operations should be covered)
- **ActiveJob**: CLM will be reported for the `perform` method of any job
- **ActionView**: Without methods being defined in the view templates, we currently don't map any metrics to those files within an IDE. We could potentially map overall stats for each view to individual files in future.
- **ActionCable**: Given the typical use of ActionCable, the methods involved are actually defined in the ActionCable library itself in classes that are unlikely to be loaded up in the user's IDE. No plans for CLM coverage of ActionCable at present.
- **ActiveRecord**: Given that the vast majority of methods are defined in the base library classes, we do not provide CLM for model classes loaded up in the IDE. Any manually traced model method will have CLM data associated with it. In future, we may wish to provide relevant SQL performance data while on the model file.
- **ActiveStorage**: As with ActionCable, the methods involved are defined in the library itself and not covered by us for CLM data.
