### ISSUE TITLE
MLT: Incorporate cross agent test

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1077]
Using the `method_level_telemetry` branch, we should bring in the new cross-agent spec(s) for MLT and get them working with the agent.

**Comment by kaylareopelle** [comment]
To confirm, this is for the missing tests in the cross-agent-tests repo to be added to our repository and made to pass?

**Comment by fallwith** [comment]
@kaylareopelle when this issue was authored, yes, that was the expectation. However, the new MLT/CLM tests do not appear to have been added to the cross agent suite yet (not even in a draft). So this issue might grow in scope to include working with Uma to help take things from Google Docs into GitHub as a prerequisite for us then implementing support for the new tests in the Ruby agent.

**Comment by angelatan2** [comment]
The existing cross-agent test used in Ruby is a few versions back.  We may need to spend more time if we need to do this story (ie. if the story applies to us).

**Comment by angelatan2** [comment]
As discussed in the previous planning meeting. We decided not to implement this story since in the spec, the attributes are "should" for each language agent depending on the availability of the attribute within that language stack.
