### ISSUE TITLE
Update attributes configs default values

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1091]
The Ruby Agent is not yet in compliance with the default `attributes.include` and `attributes.exclude` values outlined in the [Agent Attributes PORTED: Request Headers spec (Internal)](https://source.datanerd.us/agents/agent-specs/blob/0c52d16310bcef40cea84873408389f3d1597a98/Agent-Attributes-PORTED.md#request-headers). 

It also seems like we need to add an `allow_all_headers` to meet the full spec requirements.

[Original discussion (Internal)](https://newrelic.slack.com/archives/GAPN6K7T2/p1649975270902499)

### T-Shirt size

**Comment by fallwith** [comment]
The "all headers" part may be related to https://github.com/newrelic/newrelic-ruby-agent/issues/1029

**Comment by fallwith** [comment]
The `allow_all_headers` functionality went in with https://github.com/newrelic/newrelic-ruby-agent/pull/2155.

For the include and exclude lists, there has been .NET agent work recently to specifically implement new excludes for use with request headers. But given that these lists are used for more than just request headers and given the non-request-header-specific agent specs that do indeed call for empty lists as we have now, we're hesitant to make any changes at this time that could impact existing customers unexpectedly.

As customer requests and large scale specs vs. implementation audits continue, we can revisit later - possibly with a major agent version bump.
