### ISSUE TITLE
local decorating doesn't work when log forwarding option is disabled on k8s-newrelic-logging

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1092]
_[Copy of RUBY-2463](https://newrelic.atlassian.net/browse/RUBY-2463)_

When the ruby agent is configured as below, local decorating function doesn’t work.

```
NEW_RELIC_APPLICATION_LOGGING_ENABLED: “true”
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: “false”
NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED: “true”
NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: “true”
```

Customer’s logs were sent via an external forwarder, k8s newrelic-logging, and the log itself can be seen in the New Relic Log UI. However, the message’s attributes do not include the attributes applied through decoration.

Many New Relic customers don’t enable forwarding option in short term because of following reason. So, this issue that the local decorating doesn’t work would be blocker.

They store all logs in other place like AWS S3 for long term. Currently New Relic allows the customers to store logs for one year. Hence, the customer want to forward the logs to other places via external forwarder, then transfer them to New Relic.

The customer wants to avoid sampling of logs and also avoid overhead of transferring logs.

**Comment by angelatan2** [comment]
@kaylareopelle the scope within the logging GA milestone should be limited to assessing if this confirmed bug.  We may have to come around to fixing this later.

**Comment by kaylareopelle** [comment]
We ran two tests on this issue and have not been able to replicate the problem.

Test 1: Locally running Rails application with environment variables setting the values
Test 2: Elastic Beanstalk deployed Sinatra application with the New Relic Infrastructure agent acting as the log forwarder and the configuration options set inside the newrelic.yml file

**Comment by kaylareopelle** [comment]
This ticket was passed to GTS during our pairing session today. Closing this issue here in favor of any future GTSEs.
