### ISSUE TITLE
Add tests for Thread instrumentation using Rails

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1107]
Create a simple Rails controller that makes external requests using Net::HTTP or another instrumented HTTP Client within threads. Turn on our new Thread instrumentation, introduced in #1080, and make sure the spans have the expected relational structure and are created as we saw them in our playground environment.

### T-Shirt size

**Comment by angelatan2** [comment]
We have unit test coverage with thread instrumentation.  Lower priority.

**Comment by fallwith** [comment]
Addressed with subsequent threading work done in v9.x.
