### ISSUE TITLE
Standardize on "agent"

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1118]
We sometimes capitalize "Agent" and sometimes don't. We are inconsistent across our documentation, comments, and the text that is generated and placed in front of users.

We should decide on either a single standard of "Agent" or "agent" or write up some rules if we think both are useful for different contexts.

Recently with #1034 we went with "agent" for the README, and that seemed to match what most of the other agent repos have done.

**Comment by fallwith** [comment]
@angelatan2 that's a terrific idea!

**Comment by fallwith** [comment]
"agent" is desired

**Comment by hannahramadan** [comment]
Closed with https://github.com/newrelic/newrelic-ruby-agent/pull/2295
