### ISSUE TITLE
RailsConf: Ruby Agent Install Demo

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1122]
### Feature Description
Create project that can be used to demo installing the New Relic Ruby agent. Should probably be a Rails 7 app.

### Additional context
This demo install is meant to be shown at RailsConf 2022, May 17-19.

**Comment by hannahramadan** [comment]
Fine tuning demo flow and public repo. Will meet with Kayla next week for wrap up and feedback.

**Comment by hannahramadan** [comment]
Demo Link: https://github.com/hannahramadan/railsconf_rpm_install_demo

**Comment by angelatan2** [comment]
This issue is closed
