### ISSUE TITLE
Remove Orphaned Constants

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1130]
The following is a list of constants that appear to be defined but never referenced. This list is thought to be conservative because it was produced without being concerned by module namespaces. So if `ClassOne::CONSTANT` is defined, but `ClassTwo::CONSTANT` is all that is ever referenced, `ClassOne::CONSTANT` would be left off of this list because of the reference even though it does not belong to the right namespace. 

We should:

- Remove all of these constants from the code base
- Refactor the unit test(s) that reference NEWRELIC_ID_HEADER to either have the test class define the constant or remove the tests if they only pertain to the constant
- Run CI checks to verify everything still works

### Constants

- MYSQL_EXPLAIN_COLUMNS
  -   ./lib/new_relic/agent/database.rb:10
- WEB_ROLLUP_METRIC
  -   ./lib/new_relic/agent/datastores/metric_helper.rb:9
- OTHER_ROLLUP_METRIC
  -   ./lib/new_relic/agent/datastores/metric_helper.rb:10
- MONGO_PRODUCT_NAME
  -   ./lib/new_relic/agent/datastores/mongo/metric_translator.rb:59
- POUND
  -   ./lib/new_relic/agent/distributed_tracing/distributed_trace_payload.rb:21
- ALL_QUEUE_METRIC
  -   ./lib/new_relic/agent/instrumentation/queue_time.rb:14
- NEWRELIC_ID_HEADER **(NOTE: used, but only by tests)**
  -   ./lib/new_relic/agent/monitors/cross_app_monitor.rb:14
- VALID_PREFIX_SEGMENT_COUNT is possibly orphaned.
  -   ./lib/new_relic/agent/rules_engine/segment_terms_rule.rb:13
- GRANDPARENT_ID_KEY
  -   ./lib/new_relic/agent/span_event_primitive.rb:23
- NO_SAMPLES
  -   ./lib/new_relic/agent/transaction/transaction_sample_buffer.rb:11
- TRANSACTION_NAMING_SOURCES
  -   ./lib/new_relic/agent/transaction.rb:39
- DEFAULT_PRODUCT_NAME
  - lib/new_relic/agent/datastores/metric_helper.rb:12

**Comment by fallwith** [comment]
#1408 has taken care of the lion's share of these. Here's an updated list:

- [ ] MYSQL_EXPLAIN_COLUMNS
./lib/new_relic/agent/database.rb:10
- [X] WEB_ROLLUP_METRIC
./lib/new_relic/agent/datastores/metric_helper.rb:9
- [X] OTHER_ROLLUP_METRIC
./lib/new_relic/agent/datastores/metric_helper.rb:10
- [X] MONGO_PRODUCT_NAME
./lib/new_relic/agent/datastores/mongo/metric_translator.rb:59
- [X] POUND
./lib/new_relic/agent/distributed_tracing/distributed_trace_payload.rb:21
- [X] ALL_QUEUE_METRIC
./lib/new_relic/agent/instrumentation/queue_time.rb:14
- [ ] NEWRELIC_ID_HEADER (NOTE: used, but only by tests)
./lib/new_relic/agent/monitors/cross_app_monitor.rb:14
- [ ] VALID_PREFIX_SEGMENT_COUNT is possibly orphaned.
./lib/new_relic/agent/rules_engine/segment_terms_rule.rb:13
- [X] GRANDPARENT_ID_KEY
./lib/new_relic/agent/span_event_primitive.rb:23
- [X] NO_SAMPLES
./lib/new_relic/agent/transaction/transaction_sample_buffer.rb:11
- [X] TRANSACTION_NAMING_SOURCES
./lib/new_relic/agent/transaction.rb:39
- [X] DEFAULT_PRODUCT_NAME
lib/new_relic/agent/datastores/metric_helper.rb:12

**Comment by hannahramadan** [comment]
All orphaned constants references in this ticket have been completed! Thanks to @esquith for wrapping this up.
