### ISSUE TITLE
Adopt latest `setup-ruby` GitHub Actions action, and see if we can cut down on manual customizations

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1132]
The latest [setup-ruby](https://github.com/ruby/setup-ruby) action seems to support all of the Ruby versions that we would need to test against. We should see if we could adopt it into our CI workflow and eliminate as much of our custom logic found in `.github/actions/build-ruby/index.js` (our fork) as possible.

**Comment by angelatan2** [comment]
Closing this issue with the  merge of #1178
