### ISSUE TITLE
Review use of MessageBroker metric for ActiveJob

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1151]
Within a trace, the metric/name generated for calls to ActiveJob follows the message broker format:  

```ruby
# lib/new_relic/agent/instrumentation/active_job.rb

trace_execution_scoped("MessageBroker/#{adapter}/Queue/#{event}/Named/#{job.queue_name}"
```

This format is outlined in the [MessageBroker agent spec (internal)](https://source.datanerd.us/agents/agent-specs/blob/0c52d16310bcef40cea84873408389f3d1597a98/APIs/messaging.md). 

Should this be used? If not, let's use this ticket to fix it.

**Comment by angelatan2** [comment]
Please consider the avenue needed to surface a new metric to our customers if we create a new metric name for ActiveJob instead of using MessageBroker.

**Comment by kaylareopelle** [comment]
Though Active Job performs queueing activities, the Rails Guides describes it as "a framework for declaring jobs and making them run on a variety of queuing backends." [(Source)](https://guides.rubyonrails.org/active_job_basics.html#what-is-active-job-questionmark)

The value I see in changing the metric name is: 
1. Closer alignment with the MessageBroker agent spec - Active Job isn't a message broker, our only instrumented message broker is `bunny` for RabbitMQ. We should not be following the agent spec for message brokers on a library that is not a message broker.
2. More intuitive naming for our customers - Active Job isn't in the name. This may pose challenges for discoverability.

As of right now, I think changing the first clause of the metric should be enough to improve clarity so that the code quoted in the description reads: 

```ruby
trace_execution_scoped("ActiveJob/#{adapter}/Queue/#{event}/Named/#{job.queue_name}"
```

**Comment by kaylareopelle** [comment]
Please add your estimate! @hannahramadan, @tannalynn
