### ISSUE TITLE
Ratify an approach for updating the cross agent tests repo, then do so

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1152]
Now that #924 and #925 are done, we should look at what it takes to update the (internal) cross agent tests repo with the content in this repo's `fixtures/cross_agent_tests` directory. 

Currently running `rake cross_agent_tests:push` will produce one difference recognized by git:

- `attribute_configuration.json`: A file we long differed on to add 2 additional values to various lists. These values are "browser_monitoring" and "span_events".

and the following new files not yet known to git:

- `aws.json`
- `cat_map.json`
- `data_transport/`
- `rum_loader_insertion_location/empty_head`

We should - in collaboration with the other agent teams - decide on how to handle these differences and then proceed to get the content added to the cross agent tests repo. Once done, running `rake cross_agent_tests:pull` and `rake cross_agent_tests:push` should both complete successfully without producing any differences in either of the two repositories involved.

One interesting approach the Java agent team has taken has been to update the cross agent tests repo's README to denote agent specific deviations (look at the `sql_parsing.json` section).

**Comment by angelatan2** [comment]
Let's lower the priority of this ticket for now.   As a group, we need to reinitiate how/when we do cross-agent tests.

**Comment by fallwith** [comment]
Closing in favor of a (hopefully upcoming) cross agent initiative to standardize on how to update and align with these tests.
