### ISSUE TITLE
CI: Start (periodically) testing Rails Edge

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1159]
The best way to test a brand new stable release of Rails is to have already been testing Rails Edge beforehand. Let's add Rails Edge coverage with our CI system, having it run periodically (not as often as on every PR) with perhaps the same cadence as Ruby preview build runs.

**Comment by angelatan2** [comment]
Thank you for adding this ability to our CI.  It will become our foglights to tell if there will be issues with the upcoming rails version.
