### ISSUE TITLE
CI: Multiverse tests: specifying more than 1 suite does not work as intended

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1162]
**NOTE:** Our automated CI system tests multiple multiverse suites by referring to their group/category name and that system is therefore unaffected by this issue.

When attempting to run two or more multiverse suites at the same time, only the first one seems to run.

Our multiverse documentation gives the following example:

```shell
rake 'test:multiverse[rails,net_http]'
```

Issuing that command will only run the "rails" suite and completely ignore the "net_http" suite.

**Comment by tannalynn** [comment]
We've decided we don't need it to work this way, lets just update the readme
