### ISSUE TITLE
Unused variables in tests

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1181]
Running our full suite of Minitest tests reports that the following variables are declared but never used. Each test should be verified to see if the variable can be removed entirely or if the test should be refactored to include the use of the variable. 

```shell
test/new_relic/agent/configuration/server_source_test.rb:139: warning: assigned but unused variable - modified_event_harvest_config
test/new_relic/agent/error_collector_test.rb:353: warning: assigned but unused variable - error
test/new_relic/agent/log_priority_test.rb:12: warning: assigned but unused variable - txn
test/new_relic/agent/span_event_primitive_test.rb:102: warning: assigned but unused variable - external_segment
test/new_relic/dependency_detection_test.rb:212: warning: assigned but unused variable - executed
```

**Comment by ohbarye** [comment]
I found those warnings listed in https://github.com/newrelic/newrelic-ruby-agent/issues/1181#issue-1251019953 has already been removed by https://github.com/newrelic/newrelic-ruby-agent/pull/1353.

**Comment by kaylareopelle** [comment]
I'm going to close this issue and open a new one for the latest batch of unused variables in our tests. Thanks for your help, @ohbarye!
