### ISSUE TITLE
No way to opt-out of sending potentially sensitive log data to NewRelic servers for less than $25k/year commitment 

### ISSUE THREAD

**Issue by stuartrr** [newrelic/newrelic-ruby-agent#1188]
## Description

I'm unable to opt-out of sending log data to NewRelic servers on the Pay as You go plan. I believe this is because it can only be disabled via turning on High Security Mode which has a $25k/year minimum spend. Log data could have sensitive data in it. See https://news.ycombinator.com/item?id=31195476 for a discussion. The announcement blog post https://newrelic.com/blog/nerdlog/apm-logs-in-context written by @juliangiuca states  "with the option to opt-out anytime". But the opt-out will cost $25k/year according to support.

I've pinned my agent version to one from a year ago but that doesn't seem like a sustainable approach from both support  and security fixes. 

## Expected Behavior
Ability to disable or opt-out of sending potentially sensitive log data to NewRelic servers on any paid plan as per the blog post by @juliangiuca - https://newrelic.com/blog/nerdlog/apm-logs-in-context .

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

I tried talking to support and they are saying "In order for us to get you an exception to enable high security mode within your account [snip], you would at least have to be on the Annual Pool of Funds (APoF) plan which is an Annual Commitment with a minimum spend of $25K with Data Plus offering."

## Steps to Reproduce
Install a recent agent

## Your Environment
Rails 6.1.

**Comment by stuartrr** [comment]
So I got the completely wrong information from support. Seems I can turn this off with an environment variable.

https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/#1-agent

**Comment by fallwith** [comment]
Hi @stuartrr,

Thanks very much for reaching out to us with this issue. I apologize for any poor experience that you may have received while working with support. The New Relic Ruby agent only very recently - with version 8.7.0 of the gem - began forwarding log data by default. As such, this log forwarding is still very new to everyone. All of the functionality, configuration, and agent specific details are a lot to get up to speed on.

I would like to assure you that you never have to send log data to New Relic, on any plan, including our free forever plan.

The High Security Mode functionality to which you are referring will indeed restrict log forwarding as one of the many things done in the name of security. But that is not the only way and certainly not the recommended way to go about disabling log forwarding for most users.

Here are 3 options that ought to work for you to disable log forwarding:

### Option 1 - newrelic.yml

In your `newrelic.yml` file (typically stored at `config/newrelic.yml` for a Rails application), disable log forwarding:

```yaml
application_logging:
  forwarding:
    enabled: false
```

This is essentially reversing the instructions on how to enable forwarding from the [docs](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/#1-agent) that you referenced.

### Option 2 - environment variable

If the following environment variable is present and set `false`, the agent will not forward logs:

```shell
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false
```

This too essentially involves reversing the instructions on how to enable forwarding from the [docs](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/#1-agent) that you referenced.

### Option 3 - server-side configuration via the web UI

The New Relic web UI can be used to disable log forwarding. Here are the [instructions](https://docs.newrelic.com/docs/logs/logs-context/disable-automatic-logging/#disable-ui).

### Alternatives

Those are the 3 approaches that I would most highly recommend for disabling log forwarding. As you mentioned you have done, pinning your New Relic Ruby agent to an older version is another way, and I agree with you that doing so is not very sustainable or secure.

Another alternative that you will always have at your disposal is to take advantage of the fact the agent is open source (Apache 2 licensed) software. You will always be welcome to fork the project to make any desired changes. Hopefully you should never have to do so for any other reason than personal preference and we won't ever let you down by locking critical functionality between any sort of paywall, but the option is always there.

Of course in addition to allowing forks, our small but mighty Ruby team also welcomes PRs and Issues (as you have leveraged, thank you!).

**Comment by fallwith** [comment]
I'm glad you found a working solution, @stuartrr. It looks like you just closed this one right before my reply hit. Do please feel free to reach out if you have anything else for us.
