### ISSUE TITLE
All Ruby files should contain the "frozen_string_literal: true" magic comment

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1198]
Around 74% of our code base's individual Ruby files (`*.rb`, `Rakefile`, `Gemfile`, etc.) are missing the `frozen_string_literal: true` magic comment string that tells Ruby to freeze strings by default.

The comment section at the top of each of our Ruby files should declare UTF-8 encoding, provide our license info, and then enable frozen strings. The comment section should look like this for every file:

```ruby
# encoding: utf-8
# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true
```

With [ugrep](https://github.com/Genivia/ugrep), the files that are missing the `frozen_string_literal: true` comment are easily located:

```shell
ug --file-type=ruby -L frozen_string_literal
```

All of the files currently missing the comment should be updated to include it.

NOTE: This issue has been labeled with `good first issue` because the list of actions required is simply:

1. Find the files missing the comment
2. Add the comment to each file found

Once the files have been updated, it is possible that the newly enabled frozen string behavior may cause our CI checks to fail. Modifications to the agent code and/or the tests to get the CI checks to pass would certainly be welcome, but are not at all required as part of submitting a PR for this issue. Only the steps listed above are needed. New Relic's dev team can take things from there.

**Comment by radar07** [comment]
@fallwith Can you assign this to me? I'd like to work on this.

**Comment by kaylareopelle** [comment]
Hi @radar07! 👋  

@fallwith is out right now, so I went ahead and assigned you to this ticket! Let us know if you need any help. Thanks for your interest in contributing!

**Comment by radar07** [comment]
@kaylareopelle Thanks!!

**Comment by radar07** [comment]
Hi @kaylareopelle, I have a couple of questions.

1. When I tried adding the frozen string literal comment in the file and executed bundle exec rake, [database_test.rb](https://github.com/newrelic/newrelic-ruby-agent/blob/553c5a9ef02cc3a7ccd7c0af0d4f9cafdefff195/test/new_relic/agent/database_test.rb) this line   **INVALID_UTF8_STRING = (''.respond_to?(:force_encoding) ? "select \x80".force_encoding('UTF-8') : "select \x80")**
 is throwing the error **can't modify frozen String: "select \\x80" (FrozenError)**. 

2. Do all other rake files should be added with the encoding, license, and frozen string literal comment?

**Comment by kaylareopelle** [comment]
Thanks for your work on this, @radar07! This code will be included in our 8.10.0 release 😄

**Comment by jarblz** [comment]
hey just curious, did ya'll notice a performance improvement from this? I read an [article](https://accidentaltechnologist.com/ruby-on-rails/frozen_string_literal-the-not-so-magical-comment/) that stated that this might actually cause a performance hit.  Trying to decide whether or not we want to do this with our codebase..

**Comment by fallwith** [comment]
Hi @jarblz,

Yep, the performance tests for this project available at `test/performance` did show us an improvement. I definitely don't want to claim those tests as the best in the world and don't consider this project's code base to be the most typical for a Ruby project, but we did see improvements.

For us, we want the New Relic Ruby agent to provide the most value to an application while requiring the fewest possible resources and object allocation is something that we look at. Here's some example code:

```ruby
# frozen_string_literal: true

def test
  a = 'example'
  a.object_id
end

5.times { puts test }
```

Without the magic comment, the `a` variable will have a new object allocated every time the method is called.

This is of course only needed if a string itself is needed. If a symbol can used instead, it will deliver the same allocation benefits.

This reuse (not newly allocating) is one of the benefits of using the magic comment. Another is developer facing. A string marked as frozen will cause Ruby to complain about attempts to modify it. This can help developers ensure that unexpected modifications are not taking place. This is similar to making methods as public or private. Yes, Ruby still lets you get at private methods but there is still value to marking them as private.

My take on Ruby 3 not including the magic comment's functionality by default is entirely about backwards compatibility with Ruby 2.x code bases. Matz changed his mind on having strings be frozen by default with Ruby 3 in order to retain completely compatibility with Ruby 2 code; not because frozen strings are a bad idea. Everyone in the dynamic language community is very sensitive to what happened with the Python 2/3 schism and backwards compatibility is highly prized.

(As mentioned by your second article) the RuboCop linter currently enforces the inclusion of the magic comment. Popular standards enforcing project [Standard](https://github.com/testdouble/standard) currently disables the enforcing of the comment. If you're using one of those projects, then I encourage you to engage with their communities and/or Git history to see why they currently enforce / do not enforce the comment.
