### ISSUE TITLE
RubyVM and Logging Metrics not appearing

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1238]
## Description
After setting `instrumentation.thread.tracing` to `true`, the API Evolution team noticed key information missing from the New Relic platform. The Logs graph on the APM Summary page appears empty. The RubyVMs page also shows 0 for its metrics. Other information, such as that related to transactions, appears as expected.

## Expected Behavior
* Expect Logging Summary table to be populated
* Expect Logging/lines/{severity} metric to be collected
* Expect Ruby
* Expect RubyVM metrics to be collected 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) 
* Debug-level logs turned on - No errors being raised, Samplers correctly ingested, some metric events still being sent
* Audit logging turned on - Confirmed that no `Logging/lines` metrics are being gathered, no `RubyVM/*` metrics being gathered

## Steps to Reproduce
* Have not been able to reproduce the issue locally, however, the problem can be observed on ASGS (staging), an internal app.
  * permalink to summary page: https://staging.onenr.io/08dQeboLowe (Internal)
  * permalink to RubyVM page: https://staging.onenr.io/04ERPNql6QW (Internal)
 
## Your Environment
* Rails 7.0.3
* Ruby 3.1.1
* newrelic-infinite_tracing 8.8.0 + bugfix branch
* application_logging.local_decorating.enabled: true
* instrumentation.thread.tracing: true
* error_collector.max_backtrace_frames: 250

## Additional context

<img width="1792" alt="Screen Shot 2022-07-01 at 9 23 01 AM" src="https://user-images.githubusercontent.com/87386821/176933388-d790b4ae-7c66-444a-a740-e5ba2b608469.png">
<img width="1004" alt="Screen Shot 2022-07-01 at 9 24 22 AM" src="https://user-images.githubusercontent.com/87386821/176933577-e7f1ca04-d85f-4db7-9420-7497e87b9720.png">

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5): P3
*Suggested T-Shirt size (S, M, L, XL, Unknown): Unknown at this time

**Comment by fallwith** [comment]
Linking this one to #1309
