### ISSUE TITLE
gRPC: Author complete unit test coverage for the new instrumentation code

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1242]
As with other instrumented libraries, we should leverage our multiverse system, bring in the `grpc` gem via an `Envfile` file, and perform exhaustive unit test coverage of all new gRPC instrumentation.

**Comment by kaylareopelle** [comment]
@fallwith - Is this to add tests to the code that was written as part of the spike? I would expect tests to be included in the code submitted for the other issues in this milestone.

**Comment by fallwith** [comment]
> @fallwith - Is this to add tests to the code that was written as part of the spike? I would expect tests to be included in the code submitted for the other issues in this milestone.

I wanted to be flexible with an overall gRPC branch and require the tests for any merge to dev. But I like your idea here. Let's do that.

**Comment by hannahramadan** [comment]
@kaylareopelle can I pair with you on this ticket?

**Comment by kaylareopelle** [comment]
@hannahramadan - Sure! I'll put some time on the calendar.

**Comment by kaylareopelle** [comment]
We've made a lot of progress on the test coverage for gRPC client code.

The following areas remain: 
* Create a helper test file to test `#cleaned_name`
* Write tests that exercise the following gRPC methods call our instrumentation: 
  * bidi_streaming
  * request_response
  * server_streaming
  * client_streaming 

I started consulting gRPC's specs and got a few ideas that involve building out a more robust gRPC client for the sake of the tests.

**Comment by fallwith** [comment]
Resolved with the current state of the `grpc` branch
