### ISSUE TITLE
Replace String.new() with +string

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1246]
Ruby 2.3 introduces the [+string](https://ruby-doc.org/core-3.1.2/String.html#method-i-2B-40) method. After conducting some benchmarking tests, `+string` has a performance benefit over `String.new()` in both object allocations and iterations per second. 

When we remove support for Ruby 2.2 in major release 9.0.0, we can enhance our performance by replacing calls to String.new() with +string.

**Comment by tannalynn** [comment]
Removed the the 9.0 milestone
Since we will no longer support 2.2 as of 9.0 , this will not be a breaking change after 9.0 is released

**Comment by kaylareopelle** [comment]
Closed by #1787
