### ISSUE TITLE
Decide on a pattern for regularly updating config.dot or remove it

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1253]
10 years ago with RUBY-868 (internal) / 26580d0eac250919cdb51a49e87a27919edf8d60, we added a `config.dot` file to the repo to power a diagram of the agent's configuration options.

We should decide as a group on the current value of such a diagram and either establish a pattern to keep the `config.dot` file up to date or remove it from the repository.

**Comment by kaylareopelle** [comment]
Relates to #1284
