### ISSUE TITLE
newrelic_rpm slows down requests 10x when used with graphql dataloader

### ISSUE THREAD

**Issue by bmulholland** [newrelic/newrelic-ruby-agent#1264]
See https://github.com/rmosolgo/graphql-ruby/issues/3945 for some info about the error

Note the investigation at https://github.com/rmosolgo/graphql-ruby/issues/3945#issuecomment-1186232935 which shows where in newrelic_rpm the slowdown occurs

And the repro at https://github.com/rmosolgo/graphql-ruby/issues/3945#issuecomment-1186210895

Thanks to @hkdnet for moving this along

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by fallwith** [comment]
@bmulholland @hkdnet I opened up `lib/new_relic/agent/range_extensions.rb` and rewrote `merge` and `merge_append` like so:

```ruby
  # CHANGES: 1. instead of instantiating new Integer objects with 'range_min'
  #             and 'range_max' variables, just use a one-liner to build a new
  #             Range object directly (object allocation savings)
  #          2. remove the intersects? check and assume that it has already been
  #             performed elsewhere
  def merge(r1, r2)
    (r1.begin < r2.begin ? r1.begin : r2.begin)..(r1.end > r2.end ? r1.end : r2.end)
  end

  # CHANGES: 1. instead of using Array#each_with_index and finding the first
  #             range with overlap, use Array#index and get the index for the
  #             range instead
  #          2. instead of calling merge on every range, perform the intersects?
  #             check in the Array#index block itself
  def merge_or_append(range, ranges)
    i = ranges.index { |r| intersects?(r, range) }
    (ranges[i] = merge(ranges[i], range) and return ranges) if i
    ranges << range
  end
```

On my development machine with Ruby 3.1.2, these two changes produce about a 27% speed boost.

It appears that the remaining time is being spent inside the `intersects?` method. That method checks to see if 2 ranges have an intersection. For example:

- `1..3` and `2..4` => true, these 2 intersect
- `1..3` and `4..5` => false, these 2 do not intersect

ActiveSupport's core extensions for `Range` define an `#overlaps?` method which uses `#cover?` on each of 2 ranges to see if there's overlap. Our `intersects?` method is instead using `#include?`. `#include?` ought to be slower in general, but with the specific code in question, it seems to be slightly faster than `#cover?`.

That's all I have as an update for now. If we can speed up the `intersects?` method in the New Relic Ruby agent code or avoid calling it as often by making changes in the `graphql` gem, we ought to be able to further improve performance.

@hkdnet's PR #1266 provides a terrific speed boost but currently breaks the way that the agent handles a transaction's children (unit tests are currently failing). Getting that PR to pass the unit tests is another possible solution.

**Comment by fallwith** [comment]
Hi @bmulholland @hkdnet,

With #1274, we have made a change that completely removes the `merge_or_append` method and causes the agent to no longer check to see if pairs of ranges overlap until the very last stage when a segment of data is being reported to New Relic's servers.

We would love to have some GraphQL users test the new `strider` branch to see if the changes improve performance.

A Ruby project's `Gemfile` can be set to use the `strider` branch of the New Relic Ruby agent like so:

```ruby
gem 'newrelic_rpm', git: 'https://github.com/newrelic/newrelic-ruby-agent', branch: 'strider'
```

**Comment by fallwith** [comment]
Hi @bmulholland @hkdnet,

Were you able to take a look at #1274 / the `strider` branch of the repo to see if those changes help at all with the performance issues?

**Comment by bmulholland** [comment]
@fallwith Sorry, I don't have bandwidth right now

**Comment by fallwith** [comment]
@bmulholland no worries at all. I'll drop a note in https://github.com/rmosolgo/graphql-ruby/issues/3945 so that the participants know the branch is available.

**Comment by hkdnet** [comment]
Thank you for your great work. I tried your branch and on my laptop it works very well. The RoR's output was significantly reduced (more than 30sec -> about 800ms).
I found another issue that RoR says it took 800ms but in Chrome's Dev Tool the request took about 1200ms. Usually this is because Rack middleware consumed 400ms in total. 
I need to take another look on which Rack middleware takes so long time and why. But it seems another issue. 
#1274  looks good to me 😃

**Comment by fallwith** [comment]
Thank you @hkdnet for testing the changes! The rest of the maintainers will review this PR and then the improvements will go out with upcoming gem version 8.10.0, hopefully to be released before September.

**Comment by tannalynn** [comment]
Looks like it wasn't linked to the PR #1274 before merging to get auto-closed, so closing now since we have completed the work and it will be included in the upcoming release. 👍

**Comment by fallwith** [comment]
The [v8.10.0](https://rubygems.org/gems/newrelic_rpm/versions/8.10.0) release of the `newrelic_rpm` gem with the improvements is now available on RubyGems.org.
