### ISSUE TITLE
Can't modify frozen Logger

### ISSUE THREAD

**Issue by mkcosta** [newrelic/newrelic-ruby-agent#1288]
## Description
Standard logger instrumentation try to modify the Logger instance, which, as in our case, can be frozen (redirecting to `/dev/null`).

## Expected Behavior
The instrumentation should not modify the logger from other libraries, or clone it, or catching the `FrozenError`.

## Steps to Reproduce
The issue happened when using `newrelic_rpm 8.8.0` together with the [braintree_ruby](https://github.com/braintree/braintree_ruby) gem, which allows to pass an external logger in the configuration. 
We use a frozen instance of the standard logger, whicih works well with previous version of the `newrelic_rpm` gem (ie 8.0.0):

```ruby
    NULL_LOGGER = Logger.new('/dev/null', level: Logger::INFO).freeze

    @client ||= Braintree::Gateway.new(environment: environment,
                                       merchant_account_id: merchant_account_id,
                                       merchant_id: merchant_id,
                                       public_key: public_key,
                                       private_key: private_key,
                                       logger: NULL_LOGGER)
``` 

The above code throws the following error:
```ruby
FrozenError: can't modify frozen Logger: #<Logger:0x00007f4fda9b1be0 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f4fda9b1b18 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007f4fda9b1a50 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename="/dev/null", @dev=#<File:/dev/null>, @binmode=false, @mon_data=#<Monitor:0x00007f4fda9b1a00>, @mon_data_owner_object_id=76420>> /app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/logger/instrumentation.rb:29:in `clear_skip_instrumenting'
```

## Your Environment
The following relevant gems was used:
* `newrelic_rpm` (8.9.0)
* `braintree` (4.4.0)

**Comment by fallwith** [comment]
Hello @mkcosta,

Thank you very much for bringing this issue to our attention.

As of version 8.6.0, the Ruby agent will enhance instances of the Ruby `Logger` class to power New Relic's [logs in context](https://newrelic.com/blog/nerdlog/apm-logs-in-context) functionality.

We are sorry that the agent is raising that error. Hopefully we can make an update to the agent code to have it not attempt to modify a `Logger` instance that is frozen. We could also try rescuing failed attempts to enhance a `Logger` instance.

This definitely qualifies as a bug!

While we investigate the best way to address the bug, you can prevent the New Relic Ruby agent from attempting to enhance all `Logger` instances by setting the following value in your New Relic agent configuration file (`newrelic.yml`):

```yaml
# newrelic.yml
instrumentation.logger: disabled
```

Alternatively you can disable the functionality with the following environment variable:

```shell
NEW_RELIC_INSTRUMENTATION_LOGGER=disabled
```

We will update this issue once we have made progress on the bug.
