### ISSUE TITLE
CI: Simplecov doesn't function correctly when a file argument is present during multiverse testing

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1299]
If a `file` argument is passed to the `test:multiverse` task, SimpleCov reports 0 files observed.

Works:

```shell
bundle exec rake test:multiverse[grpc] 
```

Doesn't work:

```shell
bundle exec rake  test:multiverse[grpc,file=test/multiverse/suites/grpc/grpc_server_test.rb] 
```

<img width="778" alt="Screen Shot 2022-08-01 at 8 14 01 PM" src="https://user-images.githubusercontent.com/121392/182284213-1c2c079c-8104-46af-8c14-b6cb9fb062f4.png">

**Comment by kaylareopelle** [comment]
I believe this has been resolved by #1225 

When I run `bundle exec rake  test:multiverse[grpc,file=test/multiverse/suites/grpc/grpc_server_test.rb]` locally and follow that with `bundle exec rake coverage:report`, the resulting `coverage_results/index.html` reports 49.4% line coverage. 

If I do the same with `bundle exec rake test:multiverse[grpc]` the `coverage_results/index.html` file reports 52.71% line coverage.

Closing!
