### ISSUE TITLE
CI: Identify where time is spent across all tests

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1318]
Looking at our history of CI runs and runs that are performed locally, we should produce an outline of where time is being spent. Time should be represented both as a percentage of the whole, and in actual minutes and seconds to give us a rough idea of real time taken.

For example, we could produce something like this:

- rails61: 30 secs (1%)
- rails52: 30 secs (1%)
- background_2: 2.5 mins (4%)
- infinite_tracing: 1.5 mins (3%)

For multiverse, we can start by listing suites and then go more granular with individually nested test stats after.

Once we produce this outline, we should work as a team to produce new issues to:

a) Address performance concerns through test and/or code refactoring
b) Address no-way-around-it slowness by re-evaluating how we group the tests for better parallelism

**Comment by kaylareopelle** [comment]
@fallwith - It looks like there's an existing reporter that can provide us with the information we're looking for: https://www.rubydoc.info/gems/minitest-reporters/1.5.0/Minitest/Reporters/MeanTimeReporter 

The only downside is that this reporter isn't available on the version of `minitest-reporters` compatible with `minitest` 4.7.5

As `minitest` 5.0 was released in 2013, are we comfortable spending the time we need to get the tests that fail on minitest 5.0 fixed as part of this ticket?

**Comment by kaylareopelle** [comment]
We can get class-level timing data using the `minitest-reporters` gem's `MeanTimeReporter`: 

![Screen Shot 2022-08-24 at 3 43 21 PM](https://user-images.githubusercontent.com/87386821/186784691-926b362d-e774-4070-b2d5-fd30a048b58a.png)

When chatting with James, this seems to be enough to get us over the hurdle of where to start to get the best return on investment when trying to speed things up 

I'm going to spend a bit of time on trying to get the timing information for individual tests by creating my own reporter, but not too much.

**Comment by kaylareopelle** [comment]
Some of the code needs to be pulled out in order to get this to pass on the CI. I'm hoping to do that this afternoon.
