### ISSUE TITLE
CI: Break up the multiverse "rest" group by creating at least one new group

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1320]
The multiverse "rest" group - a catchall to group together all tests that don't fit within any of the specific suite categories - has grown quite large. We should identify which tests currently fall into that catchall group and see if we can create at least one new group to move some of the tests out into away from the catchall group.

**Comment by kaylareopelle** [comment]
Let's wait to work on this until we get the full numbers from #1318 so that we can shuffle the groupings overall to allow each CI group to run for approximately the same length of time.

**Comment by fallwith** [comment]
While the "rest" catch-all has grown in number, it hasn't grown unwieldy in terms of time to complete, and we have known issues with running too many groups in parallel. After some investigation and discussion, we've decided to keep things as-is for now.
