### ISSUE TITLE
Replace Passenger with another server for OATS

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1323]
### Description
ARM64 machines are not compatible with Passenger Phusion. As we're moving to M1 devices in the not-so-distant future, we should prepare for this by changing our OATS server to something that is both reliable (the reason why we moved to passenger/nginx) and compatible with ARM64.

### Acceptance Criteria
- [ ] ARM64-compatible server used to run OATS server

### Design Consideration/Limitations
* We stopped using the AGENT_ENGINE environment variable that allowed `puma`, `thin`, or `webrick` to be alternated between for the server and replaced it with passenger/nginx during Summer 2021 to increase reliability of the results

### Dependencies
* None 

### Additional context
* Passenger is running fine on our GitHub Enterprise SSH machines right now, idk if/when those will be updated to ARM64 devices

### Estimates
M

**Comment by fallwith** [comment]
In planing the team decided to shelve anything OATS related for now until there is an APM wide strategy in place for moving forward with it.
