### ISSUE TITLE
Missed error Stack Trace and Custom Attributes

### ISSUE THREAD

**Issue by ErmolkinVlad** [newrelic/newrelic-ruby-agent#1332]
**Maintainer note: This bug is not within the Ruby agent, but within another NR system. We're working with our internal development teams to get to the bottom of this behavior!**

## Description
There's Rails project with microservices, so if I want to track errors occur in microservice I use `perform_action_with_newrelic_trace` method from `NewRelic::Agent::Instrumentation::ControllerInstrumentation`.
Errors are reported to New Relic, but with weird behavior.
If error raises more than once in one place during less than 10 seconds, they come to New Relic first all with Custom Attributes, but then first one receives Stack Trace and loses Custom Attributes, but rest of them don't receive Stack Trace and keep Custom Attributes.
According to logs, all errors are reported with the same data: same amount of attributes and stack trace.

## Expected Behavior
All errors have both Custom Attributes and Stack Trace.

## Steps to Reproduce
```
require 'newrelic_rpm'

class RandomClass
  include ::NewRelic::Agent::Instrumentation::ControllerInstrumentation

  def random_method
    perform_action_with_newrelic_trace(name: 'random_method', class_name: 'RandomClass', category: 'OtherTransaction/RandomService') do
      random_error  # raises NameError, for example
    end
  end
end
```

Then to call `RandomClass.new.random_method` more than 1 time.

## Your Environment
ruby - 3.1.2
rails - 6.1.3
newrelic_rpm - 8.7.0

**Comment by kaylareopelle** [comment]
Hi @ErmolkinVlad! Thanks for reaching out. I'm working on reproducing the issue you're describing. 

When you say, "According to logs, all errors are reported with the same data: same amount of attributes and stack trace.", are you looking at the `newrelic_agent.log` file or the `newrelic_audit.log` file?

**Comment by kaylareopelle** [comment]
Also, could you let me know where you're looking in the UI for the stack trace and attributes data?

**Comment by ErmolkinVlad** [comment]
Hello @kaylareopelle.
Actually, I used my own logs here: https://github.com/newrelic/newrelic-ruby-agent/blob/da892884c9b9311d1179f09a33208c060083e73c/lib/new_relic/agent/new_relic_service.rb#L419
Checked data sending to New Relic via `send_request` method.

**Comment by kaylareopelle** [comment]
Thanks, @ErmolkinVlad! I was able to reproduce the behavior you described. We're looking into this and will get back to you when we know more! 😄

**Comment by kaylareopelle** [comment]
Hi, @ErmolkinVlad! So far, we've been able to determine the stack trace erasing behavior isn't caused by the Ruby agent and it isn't caused by some sort of UI filter. The stack traces are vanishing in one of New Relic's systems between the agent and the UI. I've been chatting with different teams who deal with data ingest and processing and we're still looking for the place where the stack traces are sampled. 

As far as the custom attributes go, there was a recent bug resolved that sounds very similar to the behavior you described. Can you see if your attributes now appear as expected?

Thanks for your patience! 🌻

**Comment by kaylareopelle** [comment]
@angelatan2 - Do we have the new public portal ticket for this one?

**Comment by kaylareopelle** [comment]
Hello, @ErmolkinVlad! Thanks for your patience. We were able to track down where this data is processed and got the following response from the team:

> Error details published by the agent are not guaranteed to result in exactly one TransactionError event and exactly one ErrorTrace event. The ErrorTrace event, which has the stack trace, falls under the "trace details" category of events and [is expected to have fewer events that TransactionErrors](https://docs.newrelic.com/docs/apm/apm-ui-pages/error-analytics/manage-error-data#trace-details) in addition to being subject to a more strict rate limit.

I hope this helps! If you think this behavior should not be the case, and you'd like to submit a feature request, you can do so by posting in the [New Relic Support Community](https://discuss.newrelic.com/) or by opening a [support ticket](https://support.newrelic.com/new-ticket), depending on your support level.  Please provide a link to this GitHub issue when submitting your community post or support ticket.
