### ISSUE TITLE
CI: Review, ensure automated testing of support for Mongo v6

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1351]
**Note: Mongo is a core technology. We need to update our codebase to support Mongo v6 by October 17, 2022***

The `mongo:latest` tag now points to MongoDB v6. The use of v6 has broken Mongo tests for Ruby 2.2, 2.3, and 2.4, so we have pessimistically locked down our CI system to using a MongoDB v5 tag for now.

We should determine the root cause of Mongo v6 incompatibility so that we can incorporate automated CI tests against Mongo v6.

- If the older Rubies are only incompatible with Mongo 6 simply because they are the only ones being used to test very old versions of the `mongo` gem, then we should see if it's possible to drop support for those versions and set the CI back to tagless.
- If we need to retain support for old Rubies and/or old mongo gems, then we should devise a way to also incorporate Mongo v6 into our testing. Perhaps we could spawn both a v5 and a v6 container and dynamically have the tests switch between targetting them.

* [MongoDB v 6.0.0 was released on July 19, 2022](https://www.mongodb.com/docs/manual/release-notes/6.0/#6.0.0---jul-19--2022)

**Comment by kaylareopelle** [comment]
Mongo v6 is compatible with Ruby 2.5+: https://msp-greg.github.io/mongoid/file.compatibility.html
