### ISSUE TITLE
CI: Investigate JRuby + Ubuntu 22 issues with Typhoeus

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1355]
WIth commit https://github.com/newrelic/newrelic-ruby-agent/pull/1354/commits/8a8325e7aad156155026c69991cfc1c09a7adb1f, the Typhoeus multiverse suite will now be skipped if JRuby and Ubuntu 22 are involved in the CI run (and they are both involved by default).

We should get to the bottom of why specifically JRuby + Ubuntu 22 + Typhoeus + newrelic_rpm isn't working in the hopes of at least restoring partial testing for that combo. It could be that only a specific old version of Typhoeus is problematic and we can simply have a version cut off in the tests and update our supported libraries documentation appropriately.

**Comment by kaylareopelle** [comment]
We don't have enough customers with the combination causing the test failure to put effort toward this. We will reconsider if we receive a customer request.
