### ISSUE TITLE
Refactor ENTRYPOINT on OATS Dockerfile

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1358]
### Description
Turn the code in ENTRYPOINT in the `apps/Ruby/sinatra/Dockerfile` into an executable script and call that script at ENTRYPOINT instead.

### Acceptance Criteria
* Dockerfile is more concise
* Dockerfile still behaves the same way

### Design Consideration/Limitations
* This doesn't need to be done at the same time as #1323 

### Dependencies
* Verify with Rich or another OATS-informed dev that our changes aren't breaking anything we might not be aware of

### Additional context
N/A

### Estimates
S

**Comment by fallwith** [comment]
In planing the team decided to shelve anything OATS related for now until there is an APM wide strategy in place for moving forward with it.
