### ISSUE TITLE
CI: Introduce redis gem v5+ for testing

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1361]
**Note: As a core technology, we have 90 days to adopt this change. This is due November 27, 2022**

The `redis/Envfile` has had its `nil` entry (signifying the use of the latest stable `redis` gem version) commented out for now due to some CI errors that happen when when `redis` v5 is used instead of v4 or v3.

We should investigate and address whatever it takes to get v5 working with our CI checks while retaining support for the older versions as well.

The Redis server version should also be inspected to make sure we're using a recent version.

**Comment by kaylareopelle** [comment]
Some misc todos: 
* Need to make chain work with `call_v` Redis 5.x method
* Keep getting tests to pass 
* See if we need to set the host for our Redis tests at all (removing the host argument from Redis.new allowed us to connect to the Redis server running in Docker)
