### ISSUE TITLE
CI: Automate the fetching of SimpleCov HTML results

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1378]
Our automated, GitHub Actions-based CI runs are currently stitching together SimpleCov results from multiple independent runs of our tests, involving different Ruby versions and test suites. These aggregated results are used to a) pass/fail the overall CI run based on coverage thresholds, and b) comment on the PR with a markdown table of current coverage values.

Locally, devs can very easily have SimpleCov produce an HTML based overview of coverage, but it is less easy to conduct all of the various testing combinations that a single one of our automated CI runs takes care of.

It would be great if we could have an HTML summary for the CI runs, AND be able to access it as easily as we currently are for local dev.

We'll need to do two things:

1) Update the CI's SimpleCov report generation to include HTML output **(DONE)**
2) Automated the fetching of the GHA artifact that contains the HTML

For 1), see #1377.

For 2), perhaps a Rake task could:

- Accept a branch or PR number or default to "latest in dev"
- Leverage the GHA API endpoint for listing artifacts, `https://docs.github.com/en/rest/actions/artifacts#list-artifacts-for-a-repository`
- Leverage the GHA API endpoint for downloading artifacts, `https://docs.github.com/en/rest/actions/artifacts#download-an-artifact`
- Explode the artifact to a git ignored location
- Invoke `open /path/to/index.html`

**Comment by kaylareopelle** [comment]
@fallwith  - Has this been addressed with Stoat?

**Comment by kaylareopelle** [comment]
This has been addressed with `stoat perf`! https://github.com/fallwith/stoat
