### ISSUE TITLE
CI: performance test qualitative notifications and threshold

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1395]
We currently run `performance_tests.yml` on a weekly basis and on PRs to `main`. This produces a Github artifact and Slacks the .txt file to our #ruby-agent-notifications channel. 

### Feature Description
Instead of simply Slacking the .txt file, it would be nice to add qualitative checks that alert the team of notable performance changes, for example: "performance has severely degraded!". It would also be nice to set threshold values similar SimpleCov.

It would also be nice to add a comment to the PR with a markdown table of the perf results. This will last whereas the artifact will go away after 90 days. The test script can also be given a flag to specify markdown output to make it easier.

### Additional context
The team will have to agree on threshold values. 

### Priority
Nice to Have

**Comment by kaylareopelle** [comment]
@fallwith  - Has this been addressed with stoat?

**Comment by kaylareopelle** [comment]
The hooks for this process are available in Stoat. The values for object allocations aren't currently being accounted for.

Let's keep this issue to have the stoat output included with the performance results in Slack.
One difference between this and Stoat is that we need to operate on the artifact created in the CI run.
Simplecov's CI behavior has some examples of operating on artifacts created during the CI run that may be helpful.

**Comment by kaylareopelle** [comment]
This will be evaluated as part of #2157
