### ISSUE TITLE
CI: slack notification if CI SUCCESS after FAILURE

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1397]
### Description
Our team currently receives a Slack notification to `ruby-agent-notifications` when the CI fails on PRs to `dev` and on nightly runs. It is helpful to receive that failure alert, but it would be nice to also be notified on SUCCESS of a scheduled CI run ONLY IF the previous run was a failure.

### Additional context
On first thought, a persisting SUCCESS/FAIL result will be available on Slack as the last posted CI message. Our team is currently only set up to post to Slack, so if that ends up being the only place to pull the previous result from, permissions will have to be adjusted for the bot to read from slack in addition to posting.

### Priority
Nice to Have

**Comment by luigieai** [comment]
Hello, for solving this problem, can we add an action that checks last workflow status? https://github.com/marketplace/actions/get-status-of-last-workflow
It is based on [github API](https://docs.github.com/en/rest/checks/runs#create-a-check-run--parameters).
