### ISSUE TITLE
CI: Cleanup performance_test.yml code

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1398]
### Feature Description
`performance_tests.yml` works, but it could use a code cleanup:
- There's a `working-directory` set, but then the `path` values repeat the `test/performance` path. See if they can use `performance_tests.txt` by itself. It's possible the working directory isn't applicable to the paths.
- The first `path` uses `test` and the second `path` uses `./test`. Both work, but they should match.
- Given that the descriptions all say 'results', the filename `performance_results.txt`, would be clearer and more consistent.
- Once the `runner` script arguments are updated in future, the filename should use `.md` for the extension

### Priority
Nice to Have

**Comment by fallwith** [comment]
This one has been addressed by [#1406](https://github.com/newrelic/newrelic-ruby-agent/pull/1406), thanks to @esquith
