### ISSUE TITLE
Evaluate and resolve rubocop-minitest errors

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1403]
### Description
Currently, failing `rubocop-minitest` cops are disabled by `.rubocop_todo.yml`. These include:
- [x] Minitest/AssertEmpty #1409
- [x] Minitest/AssertEmptyLiteral #1481
- [x] Minitest/AssertEqual #1482
- [x] Minitest/AssertIncludes #1483
- [x] Minitest/AssertKindOf #1484
- [x] Minitest/AssertNil #1485
- [x] Minitest/AssertRespondTo #1504
- [x] Minitest/AssertTruthy #1502
- [x] Minitest/AssertWithExpectedArgument #1505
- [x] Minitest/LiteralAsActualArgument #1503
- [x] Minitest/RefuteEmpty #1411
- [x] Minitest/RefuteEqual - #1487
- [x] Minitest/RefuteFalse - #1488
- [x] Minitest/RefuteIncludes - #1489

Evaluate each of these cops and decide whether they should remain disabled or if the error should be addressed. If it's decided the error should be addressed, resolve it in the code.

### Estimates
S = 1-3 days

**Comment by kaylareopelle** [comment]
It looks like this is finished! I'm going to close this out.
