### ISSUE TITLE
Rubocop: Turn on and address failures for Metrics/AbcSize

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1426]
### Description
One of the aspects of our codebase that makes it difficult to iterate on is the complexity of our methods. Rubocop provides a category of linters to identify complex areas of code. These linters are currently all disabled for the Ruby agent's codebase. Let's start enabling them with Metrics/AbcSize. 

[Link to Documentation for Metrics/AbcSize](https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize)

Update:
Some progress has been made throughout the codebase (a focus on `lib/*`)with PR #1447 

### Acceptance Criteria
* Rubocop Metrics/AbcSize is enabled for the lib directory and passes for all files

### Design Consideration/Limitations
* There are over 100 violations of this rule in our codebase
* This might be a good task to have the whole team work on in tandem
* If we work on this task in tandem, we'll need to devise a way to avoid stepping on each other's toes

### Dependencies
None 

### Additional context
* Rubocop todo files for this linter could be created and addressed on a smaller scale

### Estimates
L

**Comment by fallwith** [comment]
We had multiple devs working on this extensively recently. See all related closed PRs. Closing out the issue to produce a tangible chunk of work with a cut-off point. The remaining work is now obvious with the updates made to the `.rubocop_todo.yml` file, which has been updated to not only indicate the outstanding issues but also to prioritize work done outside of the `test/` directory.
