### ISSUE TITLE
Resolve Dalli TODO

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1439]
The Dalli instrumentation has two marked todos: 

https://github.com/newrelic/newrelic-ruby-agent/blob/c91b9ceac42aba562303d9aa2e8bc2d1785a6f6a/lib/new_relic/agent/instrumentation/memcache/dalli.rb#L62-L72

https://github.com/newrelic/newrelic-ruby-agent/blob/c91b9ceac42aba562303d9aa2e8bc2d1785a6f6a/lib/new_relic/agent/instrumentation/memcache/prepend.rb#L88-L96

we should research the introduction of that TODO to see if it is still applicable and if any work needs to be done. Do work if needed. Remove the TODO in any case.

**Comment by fallwith** [comment]
Considering this milestone's needs addressed with 1911. Future work in this area regarding the removal of deprecated code in an upcoming major version release is tracked separately. Closing.
