### ISSUE TITLE
Resolve Multiverse::Envfile#create_gemfiles TODO

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1440]
The Multiverse::Envfile class has the following TODO:

https://github.com/newrelic/newrelic-ruby-agent/blob/c91b9ceac42aba562303d9aa2e8bc2d1785a6f6a/test/multiverse/lib/multiverse/envfile.rb#L31-L40

we should research the introduction of that TODO to see if it is still applicable and if any work needs to be done. Do work if needed. Remove the TODO in any case.

**Comment by hannahramadan** [comment]
closing with https://github.com/newrelic/newrelic-ruby-agent/pull/1821
