### ISSUE TITLE
Refactor Gabbi code

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1448]
Currently, code related to Gabbi, `cve_methods.rb`, `cve_script.rb`, `notifications_methods.rb`, and `nofitications_script.rb`, are all top-level. We should move everything inside a class and then update all of the tests in `gem_notifications_tests.rb` to reflect the refactor.

**Comment by fallwith** [comment]
I'm thinking the two pairs of `_methods.rb` and `_script.rb` files would be replaced by 2 total class files. Given that these new classes would both be handled notification functionality, it might be good to either have a base `Notifier` class that they inherit from, or a `Notifications` module that they both include.
