### ISSUE TITLE
Announce the deprecation of Ruby 2.3 support for newrelic_rpm gem in an upcoming minor release

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#1452]
### Description
The Ruby Language deprecated Ruby 2.3 in 2018 and ended support of this version in March 31st, 2019
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

### Acceptance Criteria
Please announce the deprecation of support for Ruby 2.3 in our minor release.  After sharing in the minor release.  Please add a new story of EOL in a major release.

- [x] Update code to mark deprecation if relevant.
- [x] Update release notes. #1542
- [x] TODO: Update other customer-facing documentation closer to 8.12.0 release

### Design Consideration/Limitations
Please consider upgrades or features that we can optimize the agent upon after moving forward to newer Ruby version.

For customers using our gem with older version of Ruby, we encourage them to migrate to a newer supported version of the Ruby Language.  The existing releases and supported agent versions will continue to support Ruby 2.3; however, moving forward after this announcement, we will not be adding Ruby 2.3 support to newer versions of the agent.

### Estimates
S

**Comment by kaylareopelle** [comment]
Closing this now that 8.12.0 is released
