### ISSUE TITLE
Haml 6.0 causes tests to fail

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1456]
Haml 6.0 was released yesterday 🎉 

However, Haml 6.0 made some adjustments that cause the way our metrics are calculated for view-related instrumentation to change.

This issue looks into the changes.

Here are the test suites that failed the scheduled continuous integration on 9/21/2022:
jruby_multiverse (rails)
jruby_multiverse (rest)
multiverse (database, 2.5.9)
multiverse (httpclients, 2.5.9)
multiverse (rails, 2.2.10)
multiverse (rails, 2.3.8)
multiverse (rails, 2.4.10)
multiverse (rails, 2.5.9)
multiverse (rails, 2.6.10)
multiverse (rails, 2.7.6)
multiverse (rails, 3.0.4)
multiverse (rails, 3.1.2)
multiverse (rails, 3.2.0-preview2)
multiverse (rest, 2.2.10)
multiverse (rest, 2.3.8)
multiverse (rest, 2.4.10)
multiverse (rest, 2.5.9)
multiverse (rest, 2.6.10)
multiverse (rest, 2.7.6)
multiverse (rest, 3.0.4)
multiverse (rest, 3.1.2)
multiverse (rest, 3.2.0-preview2)

**Comment by fallwith** [comment]
https://github.com/haml/haml/releases/tag/v6.0.0
