### ISSUE TITLE
CI: test Padrino with Sinatra v3+ after it is known to be compatible

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1466]
With #1465 we had to lock Sinatra to < 3 for our Padrino tests, as Padrino seems to want to modify the `CALLERS_TO_IGNORE` array which is now frozen with Sinatra 3.0.0.

After Padrino releases a new version of padrino-core beyond the current 0.15.1 version, we should check to see if we are able to revert the change that #1465 delivered. NOTE that a new version of padrino-core need not specifically solve the Sinatra v3.0.0 compatibility problem. It could also simply add a dependency on Sinatra < 3 so that we no longer have to do so manually.

**Comment by fallwith** [comment]
NOTE: Padrino development is considered to be [halted](https://github.com/padrino/padrino-framework/issues/2256).

**Comment by fallwith** [comment]
Filed [padrino-framework#2258](https://github.com/padrino/padrino-framework/issues/2258)

**Comment by fallwith** [comment]
Closing until Padrino lives again

**Comment by fallwith** [comment]
The [padrino-framework#2258](https://github.com/padrino/padrino-framework/issues/2258) issue I filed has been completed. We should be set to test Padrino with Sinatra 3+ after a new version of Padrino (newer than 0.15.1) is released.

**Comment by nesquena** [comment]
I've now deployed 0.15.2 with the fixes
