### ISSUE TITLE
Elasticsearch: Playground app testing

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#1472]
### Description

Set up a playground app using elasticsearch to use for manual testing of the new instrumentation. This should use a variety of types of requests through elasticsearch in order to have a robust understanding of any differences seen between different requests.

Different playgrounds: 
- [ ] Elasticsearch 8 with security
- [X] Elasticsearch 8 without security (Available using docker-compose and running multiverse)
- [X] Elasticsearch 7 without security (Songs API, docker-compose + multiverse) 

### Estimates
_Please provide initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_
S

**Comment by kaylareopelle** [comment]
The songs_api playground app is working well on Elasticsearch 7.x with security disabled

**Comment by kaylareopelle** [comment]
Elasticsearch 8 with security app is in progress here: https://source.datanerd.us/ruby-agent/ruby_agent_playground/pull/new/elasticsearch-8-secure (Internal)
