### ISSUE TITLE
Investigate: `trace_no_push_scope` as a test

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1491]
Minitest requires test method names to start with `test_` in order to run. In `test/new_relic/agent/method_tracer_test.rb` the method `trace_no_push_scope` appears to be missing the starting `test_`. 

Once changed to `test_trace_no_push_scope` and running the tests, it fails with:
> Expected [#<NewRelic::MetricSpec 'X':''>, #<NewRelic::MetricSpec 'test_txn':''>] to be empty.

We should investigate if this method is supposed to be run as a test and fix it if so. Alternatively if the test is thought to no longer be necessary, it can be removed.

~Note: `test/new_relic/agent/method_tracer/class_methods/add_method_tracer_test.rb` seems to be in the same boat.~

**Comment by fallwith** [comment]
The `test/new_relic/agent/method_tracer/class_methods/add_method_tracer_test.rb` file seems to be in the same boat.
