### ISSUE TITLE
Rails notifications: Add subscriptions to ActionMailer and ActionMailbox topics

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1513]
Rails will publish content to the following 2 ActionMailer topics:

- `deliver.action_mailer`
- `process.action_mailer`

We should subscribe to these in a similar manner used for `*.action_controller` and `*.action_view` topics.

FOR TEAM DISCUSSION: we do not yet instrument ActionMailer itself. This issue does not depend on us doing so, but it might be a good idea to group all ActionMailer work together.

FOR TEAM DISCUSSION: we should also consider subscribing to `process.action_mailbox` which is mail related.

**Update 2022-11-07** the team discussed this one and concluded:

* There should be 2 new subscriber configs/classes; one for ActionMailer and one for ActionMailbox. These should subscribe to the 3 topics listed in the description above.
* There should be 2 new subscriber agent config settings to a) disable the on-by-default subscribing to ActionMailer and b) disable the on-by-default subscribing to ActionMailbox
* For a good example class to make copies of for ActionMailer and ActionMailbox, see the [ActiveStorage instrumentation class](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/active_storage.rb) and the [ActiveStorage subscriber class](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/active_storage_subscriber.rb).

**Comment by kaylareopelle** [comment]
Closed by #1740
