### ISSUE TITLE
Rails notifications: subscribe to additional ActionCable topic

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1516]
By updating [action_cable.rb](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/rails_notifiactions/action_cable.rb) and/or [action_cable_subscriber.rb](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/action_cable_subscriber.rb), we should start subscribing to the `broadcast.action_cable` topic that the Rails framework itself will publish to.

**Comment by kaylareopelle** [comment]
testing [BAINTEG-2382](https://newrelic.atlassian.net/browse/BAINTEG-2382) by closing this issue and reopening it

**Comment by kaylareopelle** [comment]
Reopening this issue to complete the test.

**Comment by kaylareopelle** [comment]
One more try
