### ISSUE TITLE
"Unable to determine source code info" on instrumenting private methods

### ISSUE THREAD

**Issue by jdelStrother** [newrelic/newrelic-ruby-agent#1589]
## Description

When using add_method_tracer on a private method, this warning is printed to the newrelic log:

```
[2022-11-04 13:54:24 +0000 M1MBP.local (29101)] WARN : Unable to determine source code info for 'Foo', method 'secret_method' - NameError: undefined method `secret_method' for class `#<Class:Foo>'

          klass.method(method_name)
               ^^^^^^^
```

## Expected Behavior
No warning is printed.

## Steps to Reproduce

```ruby
class Foo
  include NewRelic::Agent::MethodTracer

  private

  def secret_method
  end
  add_method_tracer :secret_method
end
```

## Your Environment
newrelic 8.12.0
ruby 3.1.2

## Additional context

instance_methods here - 
https://github.com/newrelic/newrelic-ruby-agent/blob/9a8d24072f84ac971302220ae2473a49d85678ed/lib/new_relic/agent/method_tracer_helpers.rb#L109-L114 doesn't include private methods. Perhaps it should be `(klass.instance_methods + klass.private_instance_methods).include?(method_name)` ?

**Comment by tannalynn** [comment]
Hello @jdelStrother! 
Thanks for letting us bringing this to our attention. 
Also, thanks for the suggested fix! That seemed to do the trick #1593
