### ISSUE TITLE
Lay the foundation for concurrent-ruby instrumentation

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1602]
Create the scaffolding for concurrent-ruby instrumentation:
* add configuration value to toggle instrumentation setting (auto, chain, prepend, disabled)
* create dependency detection file
* create chain file
* create prepend file
* update newrelic.yml with config

This can be accomplished using the instrumentation generator task: https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/tasks/instrumentation_generator/README.md 

Adding instrumentation for specific methods in concurrent-ruby is blocked by this issue.

**Comment by hannahramadan** [comment]
Scaffold completed with [concurrent_ruby branch](https://github.com/newrelic/newrelic-ruby-agent/tree/concurrent_ruby). Closing as completed.
