### ISSUE TITLE
Enable Logging while disabling Forwarding & Instrumentation

### ISSUE THREAD

**Issue by chriscz** [newrelic/newrelic-ruby-agent#1614]
### Is your feature request related to a problem? Please describe.
No

### Feature Description
I want to enable logging and submit logs to NewRelic without using the built-in forwarding so that I can make use of a custom gem's log forwarding facilities [SemanticLogger](https://github.com/reidmorrison/semantic_logger).  There is [an open issue](https://github.com/reidmorrison/semantic_logger/issues/222) tracking this problem  for which I am [working on a PR](https://github.com/reidmorrison/semantic_logger/pull/248).

In addition to the above, a public logging API would be great so that instead of
```ruby
::NewRelic::Agent.agent.log_event_aggregator.record(formatted_message, severity) 
```

you would do 
```ruby
::NewRelic::Agent.log(:debug, "message_string_or_hash_payload", exception: nil)
```

### Describe Alternatives
- Integrating the HTTP Logging API
- Monkey patching New Relic

### Additional context
**Instrumentation**
https://github.com/newrelic/newrelic-ruby-agent/blob/9471a2cffeec0be11f32ef6d19bb1be41642325e/lib/new_relic/agent/instrumentation/logger/instrumentation.rb#L44-L61

**Logging Event Code**
https://github.com/newrelic/newrelic-ruby-agent/blob/9471a2cffeec0be11f32ef6d19bb1be41642325e/lib/new_relic/agent/log_event_aggregator.rb#L54-L84

### Priority
Must Have

### Related Issues
- https://github.com/newrelic/newrelic-ruby-agent/issues/1141

**Comment by kaylareopelle** [comment]
Hi @chriscz, thanks for submitting this feature request! We're reviewing it as a team. Right now, consider this issue as gathering interest. Any customers who come across it should comment or use an emoji to show their interest in the feature!

Someone from our team will be in touch if we have questions about what your request.

**Comment by kaylareopelle** [comment]
Also, thank you for your work to make SemanticLogger compatible with the Ruby agent! I'm glad you were able to find the local decorator in your search.

**Comment by tannalynn** [comment]
We've decided to close this issue because this isn't a method we want to add to the agent's public API at this time.
