### ISSUE TITLE
Ruby Agent Playground app for Async

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#1629]
The Ruby Agent Playground app is updated (Eg. with two new directories, “async_v1” and “async_v2”) to provide for the adequate study of the gem and how it behaves without the fiber scheduler (v1) and with it (v2).

Research should be done (likely to start with the Async repository’s README) to determine how to produce the two trivial, playground-level apps needed to test both Async version patterns. These apps should then be ran with the current Ruby Agent in play to make sure all relevant behavior and data collection is operating as desired. Any areas where the agent is found wanting should be documented.

### Acceptance Criteria
The playground app is updated and functioning with the context of the spike.

### Estimates
_Please provide the initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_

**Comment by tannalynn** [comment]
Created a basic playground script using Async and fibers in a couple different ways in different methods in `fiber_scheduler/async_and_fiber_instrumentation.rb`
