### ISSUE TITLE
Make references to "NewRelic" consistent

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1656]
There are a few references in the codebase to "Newrelic". Most references to the company name are in Upper Camel Case as "NewRelic". 

Let's replace the "Newrelic" references with "NewRelic" in all cases except `.proto` files. Those need to remain static to keep gRPC running for Infinite Tracing.

**Comment by kaylareopelle** [comment]
sidekick @fallwith

**Comment by kaylareopelle** [comment]
@tannalynn - Does the description correctly reference the places where "Newrelic" can't be changed?

**Comment by fchatterji** [comment]
Hey, i just submitted a PR for this issue. Be nice, this is my first time contributing to open source :) 

https://github.com/newrelic/newrelic-ruby-agent/pull/1795

**Comment by hannahramadan** [comment]
Completed with #1795 thanks to @fchatterji. The remaining instances of `Newrelic` are infinite tracing related (which accordingly to the ticket description, looks like we need to leave alone) and a back up `newrelic` [key name](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/constants.rb#L24).
