### ISSUE TITLE
CI: Address JRuby TODOs

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1663]
**TODO 1: regarding JRuby with Rails 7.x for the "rails" multiverse test suite**

In November 2022 we noticed a frequently repeating unit test failure with both JRuby v9.3.9.0 and v9.4.0.0 in the "rails" multiverse test suite when the `rails` gem version was set to either `nil` (specifying "latest") or a v7.x version string.

#1651 sidesteps the issue by making sure those 2 version specifications are not tested with JRuby. See the TODO added by that PR to `test/multiverse/suites/rails/Envfile`.

We should get to the bottom of why the test suite is having difficulty with JRuby.

NOTES:
- the test had originally been working with JRuby v9.3.9.0 via GitHub Actions but then started failing
- the test has always had issues with JRuby v9.4.0.0
- seemingly these issues do not occur locally with either JRuby version and require the GitHub Actions tech stack to reproduce

**TODO 2: regarding a single failing rake suite test when JRuby is used**

In November 2022 we started testing with JRuby v9.4.0.0 and noticed several issues with our rake multiverse test suite.

With https://github.com/newrelic/newrelic-ruby-agent/pull/1651, most of these issues were fixed by updating test/multiverse/suites/rake/Envfile to insist that rack v3+ be used for the tests when JRuby v9.4.0.0 is in play (JRuby v9.4.0.0 identifies itself as Ruby 3.1).

However, one single failure persisted and was updated to skip JRuby testing. This is the test_records_transaction_trace test specified by test/multiverse/suites/rake/rake_test.rb.

We should get to the bottom of why that test fails with JRuby.

NOTE that the test does not appear to ever fail locally and requires the GitHub Actions tech stack to reproduce the problem

**TODO 3: for test/new_relic/transaction_ignoring_test_cases.rb**

In November 2022, both JRuby v9.3.9.0 and v9.4.0.0 were seen as creating 2 objects instead of 1 in fully 3 separate places. The existing "== 1" tests were relaxed (for JRuby only) to test for ">= 1".

We should investigate why this relaxing of the assertions was needed, make any updates as necessary, and remove the TODOs from the tests.

test/new_relic/transaction_ignoring_test_cases.rb

--

Checklist

- [x] TODO 1 complete
- [x] TODO 2 complete
- [x] TODO 3 complete

**Comment by tannalynn** [comment]
Try the latest versoin of jruby. If there are still issues, remove the todo (but leave the comment for info) and close issue.

**Comment by fallwith** [comment]
All TODOs addressed
