### ISSUE TITLE
Create a playground exercising Concurrent-Ruby in Rails

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1678]
Create playgrounds that exercise the following: 
* Call the three methods we're instrumenting in the application's code
* Invoke the Rails methods that leverage concurrent-ruby

**Comment by kaylareopelle** [comment]
@hannahramadan - Can we close this issue?

**Comment by hannahramadan** [comment]
Yes @kaylareopelle thank you :)

**Comment by kaylareopelle** [comment]
Completed! In our `ruby-agent-playground` repo, you can find the test app in [`rails7/concurrent_ruby_rails`](https://source.datanerd.us/ruby-agent/ruby_agent_playground/tree/master/rails7/concurrent_ruby_rails)
