### ISSUE TITLE
Frequent warning about bad parameters to accept_distributed_trace_headers

### ISSUE THREAD

**Issue by ludwick** [newrelic/newrelic-ruby-agent#1725]
## Description

We are seeing this very frequent warning in a sidekiq application:

`
WARN : Bad argument passed to #accept_distributed_trace_headers. Expected Hash for `headers` but got NilClass"
`

This started after a major version upgrade (probably from 6.x to 8.x). 

## Expected Behavior

Less logging of warnings.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]

I checked the source and it's clear the agent's Sidekiq [server middleware](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq/server.rb) is busted. It contains this `call` method:

`
    def call(worker, msg, queue, *_)
      trace_args = if worker.respond_to?(:newrelic_trace_args)
        worker.newrelic_trace_args(msg, queue)
      else
        self.class.default_trace_args(msg)
      end
      trace_headers = msg.delete(NewRelic::NEWRELIC_KEY)

      perform_action_with_newrelic_trace(trace_args) do
        NewRelic::Agent::Transaction.merge_untrusted_agent_attributes(msg['args'], :'job.sidekiq.args',
          NewRelic::Agent::AttributeFilter::DST_NONE)

        ::NewRelic::Agent::DistributedTracing::accept_distributed_trace_headers(trace_headers, "Other") if ::NewRelic::Agent.config[:'distributed_tracing.enabled']
        yield
      end
    end
`

The line `trace_headers = msg.delete(NewRelic::NEWRELIC_KEY)` is _always_ going to populate `trace_headers` with `nil` unless the sidekiq message has the newrelic key in it which I think almost no one would have jobs with their new relic key in the job.

I think maybe distributed tracing was not enabled for us on sidekiq previously.

## Steps to Reproduce

Run NewRelic in a Sidekiq application with distributed tracing enabled.

## Your Environment

Running newrelic-rpm version 8.13.1

## Additional context
N/A

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by tannalynn** [comment]
Hello @ludwick,
Thanks for letting us know about running into this. 
The agent should be [inserting distributed tracing headers](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq/client.rb#L10) into the sidekiq jobs if the agent is running and distributed tracing and sidekiq instrumentation are both enabled. Is it possible that distributed tracing isn't enabled when creating the jobs, but it is enabled in the agent on the sidekiq server? If that is the case, I can see why this warning would be logged so frequently. 

I can see why logging so many warnings in this situation would be undesirable. I'll add this to our tech debt and we'll take a look at updating this to minimize warnings being logged.

**Comment by ludwick** [comment]
It's possible it's actually doing the distributed tracing. We don't actually care as we didn't have it enabled before this upgrade.

But this code seems wrong regardless because the application's sidekiq job hash isn't going to have the new relic key in it. It's running a [sidekiq server middleware](https://github.com/mperham/sidekiq/wiki/Middleware) and the msg here is in the [job format](https://github.com/mperham/sidekiq/wiki/Job-Format).  The job isn't going to have the new relic key. Moreover, the line:

`
trace_headers = msg.delete(NewRelic::NEWRELIC_KEY)
`

Is going to populate `trace_headers` with a `nil` (or the value for key NewRelic::NEWRELIC_KEY if that key exists which it likely won't). That `trace_headers` is then passed to `::NewRelic::Agent::DistributedTracing::accept_distributed_trace_headers` which rejects a nil as invalid and logs a warning.

**Comment by tannalynn** [comment]
@ludwick What version of sidekiq are you using? Using the same sidekiq version that you are, I can see if I can replicate this incorrect behavior you're seeing.

In sidekiq versions we've previously tested, this has worked as expected because the ruby agent is actually modifying the job to insert the distributed tracing headers [here](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq/client.rb#L10). The job hash wouldn't otherwise have a newrelic key in it though, that is correct. Because the agent is adding these headers under the newrelic key, this allows us to later pull these headers out in the [server instrumentation](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq/server.rb#L18). 
If distributed tracing is not enabled when the agent is running in the sidekiq client instrumentation, these headers will not be added, which would lead to the warning you described previously.

**Comment by ludwick** [comment]
I guess the agent is inserting this key and it's not a secret? 

But regardless, the point is we updated to latest NR gem and now _every_ sidekiq job logs this warning. That's just absurdly verbose.

**Comment by ludwick** [comment]
But I'll note that this is the method being called that triggers the warning:

`
      def accept_distributed_trace_headers(headers, transport_type = NewRelic::HTTP)
        record_api_supportability_metric(:accept_distributed_trace_headers)

        unless Agent.config[:'distributed_tracing.enabled']
          NewRelic::Agent.logger.warn("Not configured to accept distributed trace headers")
          return nil
        end

        return unless valid_api_argument_class?(headers, "headers", Hash)
        return unless valid_api_argument_class?(transport_type, "transport_type", String)
     ...
`

This method expects a hash and the sidekiq middleware here is passing either Nil (if the key doesn't exist) or whatever that value is (is it a hash?)

This should at least not be sending a parameter into `accept_distributed_trace_headers` that will trigger a warning the user doesn't have control over and it's not clear how to fix.

**Comment by ludwick** [comment]
So the specific cases where this can happen:

- long running jobs where a job was pushed to sidekiq _before_ distributed tracing was enabled but then executed after
- systems where jobs are pushed to sidekiq without using newrelic client middleware (e.g. cross language application stacks where a non-ruby client is pushing jobs)

The new relic sidekiq server middleware can't assume that just because tracing is enabled that the job hash will always have the tracing information.

**Comment by tannalynn** [comment]
We have added this issue to our backlog. 
I can definitely understand wanting this behavior to change. We will make a change here that will prevent these warnings from being created so frequently. Thank you for letting us know about this.

**Comment by kaylareopelle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1725?planning-poker) with Zenhub @fallwith @hannahramadan @tannalynn

**Comment by fallwith** [comment]
The changes in #1834 have now been released in version 9.1.0 of the `newrelic_rpm` gem.
