### ISSUE TITLE
gRPC call causes "ArgumentError: 'X-NewRelic-ID' is an invalid header key, must match [a-z0-9-_.]+" with Google Ads API

### ISSUE THREAD

**Issue by tk3fftk** [newrelic/newrelic-ruby-agent#1730]
## Description
When we call Google Ads API like that example, it causes `"ArgumentError: 'X-NewRelic-ID' is an invalid header key, must match [a-z0-9-_.]+"`.
https://github.com/googleads/google-ads-ruby/blob/d29519bc6c9ec23cad348b9b0ff5375c08a9fdf8/examples/account_management/list_accessible_customers.rb#L28-L40

## Expected Behavior (Acceptance Criteria)

no `ArgumentError` is thrown.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

A stack trace from Rollbar is below:
```
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:373 in run_batch
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:373 in request_response
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:174 in block (2 levels) in request_response
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181 in block in intercept!
File /usr/local/lib/ruby/gems/2.7.0/gems/google-ads-googleads-20.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:65 in request_response
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175 in intercept!
File /usr/local/lib/ruby/gems/2.7.0/gems/grpc-1.50.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:173 in block in request_response
File /usr/local/lib/ruby/gems/2.7.0/gems/gapic-common-0.9.0/lib/gapic/grpc/service_stub/rpc_call.rb:121 in call
File /usr/local/lib/ruby/gems/2.7.0/gems/gapic-common-0.9.0/lib/gapic/grpc/service_stub.rb:156 in call_rpc
File /usr/local/lib/ruby/gems/2.7.0/gems/google-ads-googleads-20.0.0/lib/google/ads/google_ads/v12/services/customer_service/client.rb:322 in list_accessible_customers
File /usr/local/lib/ruby/gems/2.7.0/gems/google-ads-googleads-20.0.0/lib/google/ads/google_ads/service_wrapper.rb:53 in public_send
File /usr/local/lib/ruby/gems/2.7.0/gems/google-ads-googleads-20.0.0/lib/google/ads/google_ads/service_wrapper.rb:53 in method_missing
```

https://github.com/grpc/grpc/blob/91091e3668144de9c6aa392f496bb7639f7025a7/src/ruby/lib/grpc/generic/active_call.rb#L373

## Steps to Reproduce

Our logic is similar with the example code: https://github.com/googleads/google-ads-ruby/blob/d29519bc6c9ec23cad348b9b0ff5375c08a9fdf8/examples/account_management/list_accessible_customers.rb#L28-L40
We are also investigating reproduce condition.

## Your Environment

- Ruby 2.7.6
- newrelic_rpm (8.13.1)
- grpc (1.50.0)
- gapic-common (0.9.0)
- google-ads-googleads (20.0.0)

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

- https://github.com/newrelic/newrelic-ruby-agent/issues/1337

Additional AC:
In the event that CAT is enabled, do not raise an error and handle the use case gracefully.

**Comment by tannalynn** [comment]
Thanks for bringing this issue to our attention @tk3fftk

It looks like the agent is attempting to insert [Cross Application Tracing (CAT)](https://docs.newrelic.com/docs/apm/transactions/cross-application-traces/introduction-cross-application-traces/) headers into the grpc calls. Since it appears the format of CAT headers are incompatible with grpc, we should not be attempting to add these headers to the grpc calls, even if CAT is enabled in the agent.

We will take a look at implementing a fix for this issue. In the meantime, disabling either CAT or the grpc instrumentation should prevent this issue from occurring.
```
# newrelic.yml

  # disable CAT
  cross_application_tracer:
    enabled: false

  # or disable grpc instrumentation
  instrumentation: 
    grpc_client: disabled

```

A side note, but just so you are aware, CAT is deprecated and will eventually be removed in a future agent release. [Distributed tracing](https://docs.newrelic.com/docs/distributed-tracing/concepts/introduction-distributed-tracing/) is the replacement for CAT.

**Comment by tk3fftk** [comment]
@tannalynn Thank you for kind replying:bow:
We consider disabling `instrumentation.grpc_client` as a workaround.

According to [documentation](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#cross_application_tracer-enabled), CAT is looks disabled by default. And we intend not to enable CAT.
Would you tell us what or where should we check?

Our newrelic.yml is like below. 
```yaml
# newrelic.yml
  browser_monitoring:
    auto_instrument: true
  distributed_tracing:
      enabled: false
  infinite_tracing:
      trace_observer:
          host: <masked>
  code_level_metrics:
    enabled: false
  application_logging:
    enabled: false
  instrumentation:
    net_http: chain
```

**Comment by kaylareopelle** [comment]
Hello @tk3fftk! Our apologies for the delayed follow-up.

Thank you for sharing your `newrelic.yml` file. There are two other ways `cross_application_tracer.enabled` can be set. 

* Passing the environment variable `NEW_RELIC_CROSS_APPLICATION_TRACER_ENABLED` while starting your server/application process
* Using server-side configuration to set the value. Here are [instructions to review your server-side configuration settings](https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/server-side-agent-configuration/#customize-ssc).

Could you review those options and see if `cross_application_tracer.enabled` is being applied in one of those locations?

**Comment by tk3fftk** [comment]
Thanks @kaylareopelle :pray:
I didn't know the server-side configuration is available and the priority is high. I found the following setting.

![image](https://user-images.githubusercontent.com/3445553/211459496-8d998be7-96fe-4c94-a812-82084aac2eae.png)

**Comment by kaylareopelle** [comment]
Aha! That's wonderful news, @tk3fftk! 🎉 

Based on the earlier messages in this thread, it seems like you do not want CAT nor DT turned on for your application. To make that happen, change the value in the "Tracing type" dropdown to "NONE". 

Please give that a try and let me know if the `ArgumentError` persists.

**Comment by tk3fftk** [comment]
thank you @kaylareopelle !
I'm facing another problem about updating server-side configuration so I've opened the support ticket.
This issue could be closed if this behavior is known behavior:pray:

**Comment by kaylareopelle** [comment]
Thank you, @tk3fftk! We still have a bit of work to do to make sure our gRPC instrumentation doesn't try to insert CAT headers to prevent an error from being raised. I'll leave this issue open until we can make that change.

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1730?planning-poker) with Zenhub @tannalynn @fallwith @hannahramadan @kaylareopelle
