### ISSUE TITLE
Add Fiber instrumentation

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#1756]
Update the agent to work better within the context of fibers. This work will be very similar to the thread instrumentation, but added to the Fiber class. We will need to copy the current transaction over, and update how we're keeping track of the span parents to account for fibers, as currently it is only taking threads into account.

**Comment by fallwith** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1756?planning-poker) with Zenhub @kaylareopelle @tannalynn @hannahramadan
