### ISSUE TITLE
Instrument Kafka client calls made with rdkafka-ruby

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1758]
With [ruby-kafka](https://github.com/zendesk/ruby-kafka)'s deprecation, the [rdkafka-ruby](https://github.com/appsignal/rdkafka-ruby) gem which wraps [librdkafka](https://github.com/confluentinc/librdkafka) is well positioned to be most likely approach a Rubyist would take to interface with Kafka. As a result, we ought to instrument rdkafka-ruby.

**Comment by kaylareopelle** [comment]
Do we know what gem NR's Ruby teams use/if they're planning to make the move?

**Comment by kaylareopelle** [comment]
The kafka agent spec may also be merged soon. I think it's very close, but may help us accelerate implementation.

**Comment by fallwith** [comment]
It looks like the gem itself plans to publish Active Support messages:

https://github.com/appsignal/rdkafka-ruby/issues/54

**Comment by kaylareopelle** [comment]
https://github.com/karafka has support for AppSignal and DataDog/StatsD monitoring.
https://github.com/zendesk/ruby-kafka?tab=readme-ov-file#instrumentation used ActiveSupport monitoring
