### ISSUE TITLE
Test Failure on railsedge

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#1775]
We test railsedge in our nightly CI, but after recent commits to rails, this test is failing:
```
Failure:
NewRelic::Agent::Instrumentation::ActionControllerSubscriberTest#test_records_filtered_request_params_in_txn [/Users/tmcclure/projects/ruby-agent/test/new_relic/agent/instrumentation/rails/action_controller_subscriber.rb:306]:
Expected: "[FILTERED]"
  Actual: "secret"
```
The cause of this failure seems to be that our block we give to `Rails.application.config.to_prepare` in `lib/new_relic/agent/parameter_filtering.rb` is not getting called for some reason. 

This is the commit where the issue first starts: https://github.com/rails/rails/commit/896c7faedf01893c50d963aa4f7857b42373bd03 in gemfile:
```ruby
 gem 'rails', git: 'https://github.com/rails/rails.git', ref: '896c7faedf01893c50d963aa4f7857b42373bd03'
```
The commit before that has everything passing https://github.com/rails/rails/commit/f6e36c90aa484b00538154c41886a33a1e2c9c8c 

Checking the Gemfile.lock, when it passes it is using rack 2.2.6.2, and when it fails it's using rack 3.0.4.1. It's not clear to me at this point why a change in rack version would prevent our `Rails.application.config.to_prepare` block in `lib/new_relic/agent/parameter_filtering.rb` from getting called.

**Comment by fallwith** [comment]
Addressed by the Ruby community. Rails EDGE testing resumed on a nightly basis with #1898
