### ISSUE TITLE
Spike: Logging Enhancement for Logging Context/Custom Attributes and additional log level filtering.

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#1824]
### Description
Review the feature specs outlined in:
[NEWRELIC-6825](https://issues.newrelic.com/browse/NEWRELIC-6825)
[NEWRELIC-6826](https://issues.newrelic.com/browse/NEWRELIC-6826)

Please reconcile the ask from the community: 
https://github.com/newrelic/newrelic-ruby-agent/issues/1141

### Acceptance Criteria
1) Discover the path to implementation.
2) Document in the milestone document the stories needed.
3) Highlight the following in your milestone template:
 #### Design Consideration/Limitations
_Why is this the route we should take to achieve our goal?_
_What can't be achieved within this story?_

#### Dependencies
_Do any other teams or parts of the New Relic product need to be considered?_
_Some common areas: UI, collector, documentation_

#### Estimates
_Please provide the initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_

Solicit from your peers there estimates for each story.

**Comment by tannalynn** [comment]
[Spike Document](https://docs.google.com/document/d/1FYskP_VEF8zSq2wiup2Wbx7Pwg0umI_pf4BK73z170I/edit#)
