### ISSUE TITLE
Implement Log filtering by log level

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#1831]
Add a new configuration `application_logging.forwarding.log_level` that will set the minimum level the ruby agent will record log events for. We will want to check the log level against this config any time we want to [record a log event](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/logger/instrumentation.rb#L54).
We will be able to compare the configuration to the [logging severity](https://ruby-doc.org/stdlib-2.7.0/libdoc/logger/rdoc/Logger/Severity.html) defined by the Logger class. 
We will also want to record a supportability metric one time, `Supportability/Logging/Forwarding/LogLevel`, any time this configuration option is being used.

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1831?planning-poker) with Zenhub @fallwith @hannahramadan @kaylareopelle @tannalynn
