### ISSUE TITLE
Metadata: update release notes fields

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1833]
### Description
Update release notes fields.

### Acceptance Criteria
The following Ruby agent releases should have their front content updated with three new fields: `features`, `bugs`, and `security`. The field content should be based on the release notes, providing short, high-level sentences of what the release includes. 

For example:

```
releaseDate: '2022-08-17'
version: 8.10.0
downloadLink: 'https://rubygems.org/downloads/newrelic_rpm-8.10.0.gem'
features: ["New gRPC instrumentation", "Code-level metrics functionality is enabled by default", "Performance updates"]
bugs: ["Correctly identify the configuration value of transaction_tracer.transaction_threshold: apdex_f", "Check if a Logger object is frozen before attempting to modify"]
security: []
```

If there is no update for a field, it should be left blank (like the `security` example above). 

- [x] v9.0.0
- [x] v8.16.0
- [x] v8.15.0
- [x] v8.14.0
- [x] v8.13.1
- [x] v8.13.0
- [x] v8.12.0
- [x] v8.11.0
- [x] v8.10.1
- [x] v8.10.0
- [x] v8.9.0
- [x] v8.8.0
- [x] v8.7.0
- [x] v8.6.0
- [x] v8.5.0
- [x] v8.4.0
- [x] v8.3.0
- [x] v8.2.0
- [x] v8.1.0
- [x] v8.0.0
- [x] v7.2.0
- [x] v7.1.0
- [x] v7.0.0
- [x] v6.15.0
- [x] v6.14.0
- [x] v6.13.1
- [x] v6.12.0
- [x] v6.11.0
- [x] v6.10.0

### Estimates
Size small

**Comment by kaylareopelle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1833?planning-poker) with Zenhub @hannahramadan @fallwith @tannalynn
