### ISSUE TITLE
undefined method 'controller_path' errors filling up logs since 8.16.0 upgrade

### ISSUE THREAD

**Issue by gsar** [newrelic/newrelic-ruby-agent#1842]
## Description

There is a long error backtrace getting logged every time an omniauth login failure happens.  We also upgraded to rails 7.0.4.2 along with newrelic 8.16.0.

newrelic 8.15.0 with rails 6.1.7.1 did not produce these errors.

![image](https://user-images.githubusercontent.com/6981812/221475003-b53a6aca-bd79-45d2-9cdc-d23a12a249d5.png)

## Expected Behavior

No errors in the logs.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

The `failure` method in `omniauth_callbacks_controller.rb` simply has the line `redirect_to root_path`.

## Your Environment

Ruby 3.2.1
Rails 7.0.4.2
newrelic_rpm 8.16.0

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by Petercopter** [comment]
Would this also be causing massive memory spikes in production? Because that's what I'm seeing on Heroku. I rolled back to 8.x for right now.

![image](https://user-images.githubusercontent.com/1493974/221697258-d942b0b5-0c58-441d-941a-232b1d55fde8.png)

**Comment by tannalynn** [comment]
@gsar Thank you for letting us know about this issue! We shouldn't be assuming we can call `controller_path` on the class to create the metric name, so I've created a PR to update this. It should be included in our next release. https://github.com/newrelic/newrelic-ruby-agent/pull/1844 


@Petercopter You saw this issue when you upgraded to 8.16? I wouldn't expect this specific issue to cause that kind of behavior. I recommend opening a new issue with details about what you're seeing.

**Comment by fallwith** [comment]
The changes in #1844 have been released in v9.1.0 of the `newrelic_rpm` gem.
