### ISSUE TITLE
Create a new set_error_group_callback public API and set a new error_group agent attribute

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1845]
A new public `set_error_group_callback` API endpoint must be created in adherence with the `APIs/error_group.md` internal specifications doc.

The API must accept as its only argument an instance of a Ruby `Proc` which can be either a proc or lambda but will be referred to generically here as a proc.

The proc itself must accept as argument(s) - the exception class instance for a noticed error and as much other information the agent has at notice time such as the transaction name, the transaction user attributes, any web app info such as request URI, response code, and status, etc. It must return exactly one string value: the desired error group to associate the error with. See the `APIs/error_group.md` internal specifications doc for a full list of ideal inputs.

When the Ruby agent notices an error, it will check to see if it has an error group callback proc that was supplied by the customer. If so, it will invoke that callback with the error instance and expect to get back either a non empty string, a `nil`, or an empty string. If the agent receives a `nil` or an empty string, it discards these and takes no new action compared to what it currently does to process the noticed error. If the agent receives a non empty string, it will use the string as the value for a new `error_group` agent attribute that is sent up within the agent attributes hash for the noticed error.

**Comment by fallwith** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1845?planning-poker) with Zenhub @hannahramadan @kaylareopelle @tannalynn

**Comment by kaylareopelle** [comment]
This is expected to be called once and only once right after the agent initializes

**Comment by kaylareopelle** [comment]
Add method tracer accepts a stabby lambda/proc as an argument: https://rubydoc.info/gems/newrelic_rpm/NewRelic%2FAgent%2FMethodTracer%2FClassMethods:add_method_tracer

**Comment by fallwith** [comment]
Addressed by #1858
