### ISSUE TITLE
End-to-end testing for errors inbox fingerprinting and user tracking

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1850]
~Once issues #1845 and #1847 are complete,~ a build of the agent should exist that will transmit new error group and user id agent attributes to the errors inbox hosted server-side.

In addition to the unit tests delivered by those stories to confirm that the attributes are always present and formatted correctly when they should be, we ought to conduct some end-to-end testing with an instance of the errors inbox that will respond to the presence of the attributes.

We'll likely just use Ruby agent playground testing, but it'd be neat to see if we could come up with something more automated. We already test with dynamic app names to guarantee we're the only ones using an app at one time. We could potentially fire off errors to the backend and then pause for a short while and then automatically fire off of NRQL query to confirm that the expected behavior has taken place. We haven't done much of that to my knowledge outside of OATS where we do something similar to produce graphs. We typically just use a browser logged in to the staging environment and manually confirm things.

Ultimately the testing - however automated - needs to confirm the following:

- A noticed error is grouped as desired
- A noticed error has a user id associated with it

**Comment by kaylareopelle** [comment]
The errors galore playground in the Rails 6 directory has a good foundation for this work.

**Comment by fallwith** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-ruby-agent/1850?planning-poker) with Zenhub @hannahramadan @kaylareopelle @tannalynn

**Comment by kaylareopelle** [comment]
Could also use our audit logs to make sure we're sending data to the right place

**Comment by fallwith** [comment]
The spec calls for "traced errors" and "error events" to both involve the callback, so we ought to test with both of those.
