### ISSUE TITLE
Improve Performance Test Coverage

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1861]
Improve test coverage:
* Add SimpleCov coverage
* Create stories for missing tests
* Run tests inside of a Rails application

**Comment by fallwith** [comment]
The dev work side of things was addressed with #2140.

We'll revisit the story creation at a later time. Full coverage would require something akin to the multiverse tests and I'm hesitant to go that route.

As a team, we'll discuss strategy. I'm thinking we can focus the tests on specific areas of the agent (such as those that were recently improved to benefit GraphQL bulk load performance) and enforce an allowlist with .simplecov.
