### ISSUE TITLE
Metadata: Automate release note PRs to docs site

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1866]
### Description
Create a task that automatically generates release note PRs to the docs site. The node team has already implemented this and may be a good resource to explore during the work on this ticket.

### Acceptance Criteria
PRs to docs site are automatically generated that include: 
* full release note content 
* metadata field content

**Comment by hannahramadan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ruby-Agent-578cc3351c7940044e18b71e/issues/newrelic/newrelic-ruby-agent/1866?planning-poker) with Zenhub @fallwith @kaylareopelle @tannalynn

**Comment by hannahramadan** [comment]
Blocked until we receive credentials for a machine user to create PRs against docs-website

**Comment by kaylareopelle** [comment]
We created our own machine user, `newrelic-ruby-agent-bot`, and are still waiting on approval for this machine user to be granted write access on the `docs-website` repo.
