### ISSUE TITLE
Update release process docs to include metadata steps & more

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1873]
### Description
The metadata project introduced two new items to the release workflow for all agents: 
* Every release: Add the metadata fields `features`, `bugs`, `security` based on the content of the release [Source - Internal](https://source.datanerd.us/agents/agent-specs/blob/main/Agent-Release-Notes.md) 
* Major releases: Inform/Update APM Services update recommendation conditions [Source - Internal](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2800943157/CDD+Agent+Update+Recommendation+Version+Update+Rules)

These steps must be added to the release process documentation [Source - Internal](https://source.datanerd.us/ruby-agent/workflow/blob/master/RELEASE_PROCESS.md)

### Acceptance Criteria
- [x] Metadata field requirement added to release process
- [x] APM Services update added to release process 

We should also update the docs to include new processes and remove outdated ones:
- [x] Edit "Run performance benchmarks" to include how to run using Stoat / performance benchmark flow on GHA
- [x] Describe how to update version constants using Stoat
- [x] TODO: any processes changed during the milestone

### Estimates
S

**Comment by kaylareopelle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ruby-Agent-578cc3351c7940044e18b71e/issues/newrelic/newrelic-ruby-agent/1873?planning-poker) with Zenhub @fallwith @hannahramadan @tannalynn

**Comment by kaylareopelle** [comment]
PR link: https://source.datanerd.us/ruby-agent/workflow/pull/12/files

**Comment by hannahramadan** [comment]
Closed with PR: https://source.datanerd.us/ruby-agent/workflow/pull/12/files
