### ISSUE TITLE
Newrelic is adding 66k of script to each page

### ISSUE THREAD

**Issue by xdmx** [newrelic/newrelic-ruby-agent#1877]
## Description
I'm using the Newrelic gem on many of my projects and I've just noticed (with surprise) that each page has way bigger size than what I was expecting. Checking it out, it seems that the Newrelic gem it's inlining its script at the top of the `head` which causes the page size to increase by 66k, that's multiple times the total size of the page itself. In other

## Expected Behavior
It'd be great if it wasn't doing that, but instead doing the minimum required and then loading an external script async.
I might need to remove it otherwise to lower the page size.

## Steps to Reproduce
Include the Newrelic gem, open any page, you can see the Newrelic script at the top that includes a lot of code

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

Newrelic 9.0.0
Rails 3.2.1
Standard Newrelic generated config

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by kaylareopelle** [comment]
Hi @xdmx! Thanks for reaching out.

The script is [New Relic's Browser Agent](https://docs.newrelic.com/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring/). 

There isn't a current path to load the browser agent asynchronously, but this would make a great feature request. Feature requests are now accepted through [issues.newrelic.com](https://issues.newrelic.com). Please point the request to the Browser agent team.

In the meantime, there are smaller builds of the browser agent available. In the `Application Settings` section of the Browser app in NR1, there is a spot to select which build of the agent to get. Both the `Pro` and `Lite` builds of the agent are smaller. Lite currently has a size of 34kb. You'll have to restart your agent (usually done by restarting your app) to make the changes take effect.

https://user-images.githubusercontent.com/87386821/224834050-89bff24d-47ea-4724-9331-afa73ecb7802.mov

By default, the Ruby agent automatically injects the browser agent into applications. If you'd prefer the agent not inject browser agent, you can update your `newrelic.yml` to: 

```yml
browser_monitoring.auto_instrument: false
```
