### ISSUE TITLE
Fix Bundler::InstallError when running Sidekiq/Redis test

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1894]
### Description
The Sidekiq/Redis test errors out on the CI when using Ruby 3.1.2 with the following error: 

```
SidekiqWithRedisTest#test_redis_client_pipelined_calls_work:
Bundler::InstallError: Bundler::DirectoryRemovalError: Could not delete previous installation of `/opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/redis-5.0.6`.
The underlying error was ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: 
```
The test is currently disabled for Ruby 3.1. 

My guess is there's an issue with using the inline gemfile.

**Comment by angelatan2** [comment]
Tentatively plan to address this in early June.  This estimate is subject to change based on priorities.
