### ISSUE TITLE
Ruby Agent Review K2 Resolution/Mitigation

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#1899]
The team will review the resolution to open items documented from our initial review.

See Internal: [doc]([K2 Team Follow up](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2788458705/Ruby+APM+K2+Integration+K2+team+follow-up))

**Comment by fallwith** [comment]
Closing this placeholder catch-all issue. We can use internal ticket 7707 going forward.
