### ISSUE TITLE
CI: For GHA, allow enterprise and select non-enterprise

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1905]
For each repo, head to Settings > Actions > General and for Actions Permissions, select the "Allow enterprise and select non-enterprise" option. The "Allow actions created by GitHub" and "Allow actions by Marketplace verified creators" sub-options should be checkmarked.

Create any follow up issues related to the change as needed.

**Comment by hannahramadan** [comment]
Completed. Some GHAs are unverified and need to be reviewed by security #1934
