### ISSUE TITLE
Fix assignproj workflow

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1951]
The assignproj workflow is no longer auto-assigning new issues to the [Ruby Engineering Board project](https://github.com/orgs/newrelic/projects/17). Let's fix this so it auto-assigns issues.

A few changes have been made to this workflow recently:
* setting explicit write permissions 
* using a sha-based version of the action

**Comment by hannahramadan** [comment]
#1960 did not resolve this issue. Reopening for further investigation.

**Comment by hannahramadan** [comment]
We're experiencing a [known issue](https://github.com/srggrs/assign-one-project-github-action/issues/65) with this action, which is only for the 'Classic' version of Github projects. Updating the latest version would allow us to use a verified action and not worry about fixing this. Pausing work to explore the use of the latest Github projects.
