### ISSUE TITLE
Identify potential testers

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1963]
A private test/evaluation could be helped along by a prequalified volunteer roster. We should put the feelers out as we've done previously with great success.

**Comment by kaylareopelle** [comment]
Messages sent to: 
* #ruby-agent
* #ruby-cop
* NewRelic.Org internal manager

**Comment by kaylareopelle** [comment]
API-E is in! 👼 
Newrelic.org will circle back after Pro-Bono week.

**Comment by fallwith** [comment]
We're in good shape with Kayla's efforts here.
