### ISSUE TITLE
New gem CI automation

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1965]
Let's lend some GitHub Actions-related help to the new gem repo so that we can automate test runs and quality metrics progression. New CI workflows can be proposed via PRs.

- [x] PR workflow draft: https://github.com/newrelic/csec-ruby-agent/pull/15 
  - [X] Run Rubocop
  - [X] Run tests on all supported ruby versions
  - [x] Run Simplecov w/Comment
- [X] Release workflow draft: https://github.com/newrelic/csec-ruby-agent/pull/16 
- [x] Security check workflow draft: https://github.com/newrelic/csec-ruby-agent/pull/17

**Comment by kaylareopelle** [comment]
This work is on hold until the K2 agent moves to its New Relic codebase because we can't run ruby/setup-ruby due to K2's GHA settings.

**Comment by kaylareopelle** [comment]
The security agent moved its repo into the newrelic organization, but we're still blocked from running the actions until the Ruby agent dev team gets higher permissions on the new repo.

**Comment by kaylareopelle** [comment]
Links to open workflow PRs above. This ticket is now in K2's hands to decide if they want to incorporate the new actions.
