### ISSUE TITLE
Make sure the agent's tests pass with the K2 agent

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1982]
Run the agent's test suites (unit, env, multiverse) and make sure they still pass with the K2 agent 

[Spreadsheet to track suites](https://docs.google.com/spreadsheets/d/1cxw7d7CickTDW0xkcTW-qZ_EP2Y-o-hpJDVtvtUK1lc/edit#gid=0) - Internal

**Comment by fallwith** [comment]
Only deferred_dependency tests remain, and these are causing any issue based on repeated starts of the APM agent that don't result in restarts of the other agent. Will track separately for GA.
