### ISSUE TITLE
False warning: Unable to determine source code info for <Controller>

### ISSUE THREAD

**Issue by jcrisp** [newrelic/newrelic-ruby-agent#2048]
## Description
In newrelic_agent.log, I am receiving megabytes of false warnings:
`WARN : Unable to determine source code info for 'XYZController', method 'index' - NameError: undefined method 'index' for class '#<Class:XYZController>'`
(XYZ is standing in for the real name of the controller)

The controller doesn't have a method for 'index' but it does have an 'index' view and it is in routes.rb. No method is required on the Controller in this case - the view is rendered automatically by Rails without a method on the Controller.

This pull request highlights the code that is causing the warning:
https://github.com/newrelic/newrelic-ruby-agent/pull/1593

I am using newrelic_rpm (9.2.0).

## Expected Behavior
No logging of this false warning.
Or, a way to turn this warning off in the yaml config file without turning off all warnings.

## Steps to Reproduce
Set up a new rails app with a single controller and view. Add the view to routes.rb so it can be accessed (or make it the website root), but do not add a method for the view to the controller.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by hannahramadan** [comment]
Hi @jcrisp - thank you for submitting this issue. This shouldn't be happening and we are currently working on a fix. In the meantime, you can disable these specific warnings by turning off Code Level Metrics. In your `newrelic.yml`, add the following line:

`code_level_metrics.enabled: false`

**Comment by jcrisp** [comment]
Perfect, thank you. Disabling the code_level_metrics has stopped the incorrect log warnings. I'm not using the CodeStream extension - does disabling this affect anything else?

**Comment by hannahramadan** [comment]
@jcrisp Yes! CodeStream is currently the only consumer of Code Level Metrics, so disabling shouldn't affect anything else.

**Comment by hannahramadan** [comment]
Hi @jcrisp. Thanks again for reporting this issue! A fix will be available in our next release [PR#2061](https://github.com/newrelic/newrelic-ruby-agent/pull/2061)

**Comment by jcrisp** [comment]
Thank you!! I appreciate your help and fixing it so quickly :-)
James

**Comment by tannalynn** [comment]
9.3.0, which includes the fix for this, has been released. You should be able to update to this version now and have this be resolved. Please let us know if you run into any other issues in the future!

**Comment by jcrisp** [comment]
Thank you!!
James
