### ISSUE TITLE
`NewRelic::Agent::Logging::DecoratingFormatter#clear_tags!` should  be public?

### ISSUE THREAD

**Issue by dark-panda** [newrelic/newrelic-ruby-agent#2077]
## Description

We're getting errors akin to the following with 9.2.2 when starting up our web server:

```
App 1254076 output: [ 2023-06-14 15:34:38.8502 1254076/0x00007fa3c128c1b8(Worker 1) utils.rb ]: *** Exception NoMethodError in Rack application object (private method
`clear_tags!' called for #<NewRelic::Agent::Logging::DecoratingFormatter:0x00007fa3c7698468 @app_name="App">) (process 1254076, thread 0x00007fa3c128
c1b8(Worker 1)):
App 1254076 output:     from /data/app/shared/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:95:in `clear_tags!'
App 1254076 output:     from /data/app/shared/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:109:in `flush'
App 1254076 output:     from /data/app/shared/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/log_subscriber.rb:97:in `flush_all!'
App 1254076 output:     from /data/app/shared/bundle/ruby/3.2.0/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:23:in `call_app'
```

It appears the no-op method `NewRelic::Agent::Logging::DecoratingFormatter#clear_tags!` was made private recently but it should likely be public since it appears to be public in Rails itself:

https://github.com/rails/rails/blob/01363bd7e789d07b8fcf30b5a8efe3c8ba4423ee/activesupport/lib/active_support/tagged_logging.rb#L52

## Expected Behavior

Rails should start and not error out.

## Steps to Reproduce

In our case, we use tagged logging and lograge and it comes up during app boot. 

## Your Environment

- Ruby 3.2.2
- Rails 7.0.5
- Agent 9.2.2

**Comment by tannalynn** [comment]
Thank you for bringing this to our attention @dark-panda. I've created a PR for this and the fix will be included in our next release.
