### ISSUE TITLE
Update agent defaults to ignore rails 7 commands

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#2086]
Rails 7 uses Thor for the rails commands instead of rake. Currently we're ignoring these using our config `autostart.denylisted_rake_tasks`, but this doesn't work for the Thor commands. One option we could explore is adding the classes for the commands we want to ignore to our default for `autostart.denylisted_constants`.

Comment surfacing this issue: https://github.com/newrelic/newrelic-ruby-agent/issues/1313#issuecomment-1594303083

**Comment by kaylareopelle** [comment]
Conversely, is there something Rails 7 introduced that the agent should support, but does not?
