### ISSUE TITLE
Add test for gemspec files

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2117]
#2113 revealed our recent changes to the files included in the Ruby agent unintentionally broke the `NewRelic::Agent.require_test_helper` public API. We have some tests that try to protect this from happening, but they didn't catch the problem in this case. 

The lines of code to test are around the `s.files` assignment:
https://github.com/newrelic/newrelic-ruby-agent/blob/9fdb4396600ccdf45df1ae662219593536561c06/newrelic_rpm.gemspec#L42-L46

At a minimum, we need to test whether `test/agent_helper.rb` is included in the build.

**Comment by ajesler** [comment]
I had a play this afternoon with spec'ing the test file inclusion, and this was where I got to.

I don't love that `Gem::Specification.load` evals the gemspec file. But given it is the one in the gem, that should be trustworthy for non-PR branches in CI.

I do love the raindow effect in the minitest output, that was an unexpected delight.

```ruby
# frozen_string_literal: true
# test/new_relic/gem_test.rb
# $ TEST="test/new_relic/gem_test.rb" bundle exec rake test

require_relative '../test_helper'

class GemTest < Minitest::Test
  def test_the_test_agent_helper_is_shipped_in_the_gem_files
    agent_helper_file = 'test/agent_helper.rb'

    gem_spec_file_path = File.expand_path('../../../newrelic_rpm.gemspec', __FILE__)

    # This eval's the gemspec file, but in this case we trust it?
    gem_spec = Gem::Specification.load(gem_spec_file_path)

    assert_equal('newrelic_rpm', gem_spec.name)
    assert_includes(gem_spec.files, agent_helper_file)
  end
end
```

**Comment by kaylareopelle** [comment]
This is great, @ajesler! Thank you! Glad you enjoyed `minitest/pride`! 🌈 

I went ahead and added this, with one small tweak, to #2118 as a co-authored commit. Are you comfortable with that approach?

**Comment by ajesler** [comment]
Yep, that sounds great to me.
