### ISSUE TITLE
Ruby - Link Error Traces to Transactions

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2129]
### Description
The Errors Inbox team would like to flexibly display Error Traces and Transaction Errors for a better customer UI experience. The proposed experience is captured in [this CDD](https://newrelic.atlassian.net/wiki/spaces/TDP/pages/2885255250/CDD+Put+Transaction+IDs+into+ErrorTrace+Events).

### Acceptance Criteria
TBD

### Design Consideration/Limitations
As captured in the CDD.

### Dependencies
As captured in the CDD.

### Additional context
None

**Comment by fallwith** [comment]
This is a dup of https://github.com/newrelic/newrelic-ruby-agent/issues/2036
