### ISSUE TITLE
Review IAM policies

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2136]
### Description
Review the IAM policies and ensure that full admin privs aren't specified

### Acceptance Criteria
Review completed and IAM accounts confirmed to not have full admin privs

### Design Consideration/Limitations
None

### Dependencies
None

### Additional context
Additional details on https://issues.newrelic.com/browse/NR-124472

**Comment by kaylareopelle** [comment]
This IAM policy is no longer needed. It has been deleted.
