### ISSUE TITLE
Capture http.statusCode regardless of middleware instrumentation

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2149]
The `http.statusCode` for web requests is only captured if the agent instruments third-party middlewares, which is enabled by default. If middleware tracing is disabled ([configuration setting](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#disable_middleware_instrumentation) `disable_middleware_instrumentation`), the agent will not capture `http.statusCode`. 

The method `capture_http_response_code` contains this logic and describes the reasoning for this decision:

https://github.com/newrelic/newrelic-ruby-agent/blob/ede151dbf3d7be91f9951626914e78cad087a970/lib/new_relic/rack/agent_middleware.rb#L30-L38

We should explore the impact of removing middleware tracing as a requirement for capturing `http.statusCode` and the work involved in this change.

**Comment by hannahramadan** [comment]
- Create Rack app with middleware affecting status code (`disable_middleware_instrumention: true/false`)
- Investigate `AgentHooks.needed?` logic
- Feedback cycle
- Test updates
- Documentation updates
- Consider a middleware 'light' configuration option

**Comment by fallwith** [comment]
The changes delivered by #2175 are now generally available in v9.5.0 of the Ruby agent available for download from RubyGems.org.
