### ISSUE TITLE
Add filtering capabilities for Sidekiq job argument collection

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2150]
The agent's Sidekiq instrumentation has the ability to capture Sidekiq job arguments, which become attributes on transaction traces and traced errors. By default, this configuration option is turned off in case job arguments contain sensitive information ([docs](https://docs.newrelic.com/docs/apm/agents/ruby-agent/background-jobs/sidekiq-instrumentation/#capturing_job_parameters)). This feature can be turned on by adding the string `job.sidekiq.args.*` to the `attributes.include` array inside `newrelic.yml`. 

The current implementation offers an all-or-nothing approach—either all job arguments are captured or none are.  `job.sidekiq.args.*` is the only Sidekiq-related value that `attributes.include` respects, and any added to `attributes.exclude` are ignored.

https://github.com/newrelic/newrelic-ruby-agent/blob/7f38c1d850f8febb9890a8c9df83d00a2dddd545/lib/new_relic/agent/instrumentation/sidekiq/server.rb#L20-L25

We should explore adding more advanced filtering capabilities to give customers greater control over which Sidekiq job arguments should or shouldn't be collected.

**Comment by fallwith** [comment]
The capabilities requested will be available in the next agent release.

**Comment by fallwith** [comment]
The changes delivered by #2177 are now generally available in v9.5.0 of the Ruby agent available for download from RubyGems.org.

**Comment by lcmen** [comment]
@fallwith thank you for this. Quick question: with this new feature in place, does `attributes.exclude` support regex expressions the same way as `sidekiq.args.exclude`?

I would like to exclude sending sensitive parameters (e.g. `request.parameters.user.password`, `request.parameters.employee.password`, etc.) with single regex. However exclude option with `request.parameters.*password$` does not work for me on the latest release.

**Comment by fallwith** [comment]
> @fallwith thank you for this. Quick question: with this new feature in place, does `attributes.exclude` support regex expressions the same way as `sidekiq.args.exclude`?
> 
> I would like to exclude sending sensitive parameters (e.g. `request.parameters.user.password`, `request.parameters.employee.password`, etc.) with single regex. However exclude option with `request.parameters.*password$` does not work for me on the latest release. (documentation mentions only wildcard support like `request.parameters.users.*`).

Hi @lcmen. The `attributes.exclude` functionality was not updated with the new v9.5.0 gem release, so `attributes.exclude` continues to only support the wildcard (`*`) functionality you referenced and not regex.

As of v9.5.0 regex support for filtering is limited to the Ruby specific Sidekiq and Stripe instrumentation. We wanted to be very careful to not alter existing `attributes.include` and `attributes.exclude` functionality to avoid breaking compatibility with existing Ruby customer usage and to maintain alignment of their functionality with New Relic agents in other languages for consistency in multilingual environments.

Based on the feedback and usage of the new regex filtering for Sidekiq and Stripe, we may very well bring regex filtering to other parts of the agent. The regex support for those two instrumentations works in conjunction with the `attributes.include` and `attributes.exclude` functionality with both filters being respected, so it's possible that we could do something similar in future for request parameters by adding an extra, regex based layer of filtering in the same way.

If you'd like to see that or anything else done with the agent, we welcome feature requests (link: [create a feature request](https://github.com/newrelic/newrelic-ruby-agent/issues/new/choose)) and PRs here in GitHub.

I appreciate your reaching out, thanks!

**Comment by lcmen** [comment]
@fallwith thank you for such detailed explenation. I really appreciate that 🙇 .
