### ISSUE TITLE
Add `'/'.freeze` to constants.rb

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2153]
We have a few instances of `'/'.freeze` throughout the agent. We should add this to `constants.rb` and replace calls with this newly created constant.

**Comment by chahmedejaz** [comment]
Hey @kaylareopelle - I'd like to work on this issue, can you please assign it to me? Thanks :)

**Comment by fallwith** [comment]
Thanks very much, @chahmedejaz! You have been assigned.

PLEASE NOTE that this project's use of `/`.freeze predates our adoption of using frozen strings by default. So when you define a new constant for `/`, you can leave off the `.freeze` part.

**Comment by chahmedejaz** [comment]
Thanks @fallwith for the guidance. ❤️
