### ISSUE TITLE
Replace `start up` with `start-up`

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2154]
Let's try to be more grammatically proper: replace instances of `start up` with `start-up`. [Source](https://inventingrealityeditingservice.typepad.com/inventing_reality_editing/2016/03/stuck-in-a-rut-with-startup-vs-start-up-vs-start-up.html)

**Comment by chahmedejaz** [comment]
Hey @kaylareopelle, @hannahramadan - I've submitted the fix for this issue, would love to hear your thoughts on it. Thanks. :)
