### ISSUE TITLE
serverless wrapper for ruby 

### ISSUE THREAD

**Issue by jeremiahlukus** [newrelic/newrelic-ruby-agent#2214]
### Is your feature request related to a problem? Please describe.
I want to be able to instrument my serverless ruby applications with the new relic agent

### Feature Description
https://github.com/newrelic/newrelic-lambda-layers/tree/master
Add a lambda layer for ruby

### Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

### Additional context
Add any other context here.

### Priority
Please help us better understand this feature request by choosing a priority from the following options:
[ Really Want ]

**Comment by fallwith** [comment]
For anyone coming across this issue via a search or a browse, additional conversation takes place in https://github.com/newrelic/newrelic-lambda-layers/issues/184
