### ISSUE TITLE
Rails v7.1: Make sure the Trilogy MySQL adapter is identified and supported correctly

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2221]
Already production tested by GitHub and Shopify, GitHub's MySQL adapter [Trilogy](https://github.blog/2022-08-25-introducing-trilogy-a-new-database-adapter-for-ruby-on-rails/) is available in Rails v7.1 as an out-of-the-box choice. We should ensure that Trilogy is correctly identified by our instrumentation.

Use rails 7.1.0.beta1 or EDGE to test with.

**Comment by joevandyk** [comment]
(Trilogy can also be used by Rails 6 and 7.0)

**Comment by hannahramadan** [comment]
The Ruby agent correctly identifies and reports Trilogy as a database adapter. Tested with Ruby agent 9.6.0, Rails 7.1.1, and Trilogy 2.6.0.

From the New Relic UI:
<img width="427" alt="Screenshot 2023-11-06 at 4 49 57 PM" src="https://github.com/newrelic/newrelic-ruby-agent/assets/76922290/399fc3e1-bc8e-48c7-ac07-7e8f3ab391ae">

**Comment by rodolfoburla** [comment]
Can you re-open this issue ? We are facing the same issue mentioned by @gdubicki, even though the agent identifies the adapter correctly we have no MySQL trace on APM. We are using rails 7.1.4, new relic agent 9.15.0, trilogy 2.9.0, ruby 3.3.5.

**Comment by kaylareopelle** [comment]
Thank you for letting us know, @rodolfoburla! We'll take another look.

**Comment by rodolfoburla** [comment]
More context here, queries are displayed on traces as ActiveRecord. But when looking at APM->Databases there is no MySql there, so looking at the source code I think it is missing to map Trilogy to MySql.

**Comment by hannahramadan** [comment]
@rodolfoburla, @gdubicki - Thank you and apologies for missing this the first time around! We've put together a branch that we think solves this issue and would love any feedback on it. To use, please update your `Gemfile` to install the `newrelic_rpm` gem using:

```ruby
gem 'newrelic_rpm', github: 'newrelic/newrelic-ruby-agent', branch: 'are_you_there_trilogy'
```

**Comment by rodolfoburla** [comment]
@hannahramadan Thank you, we have tested and now the Database view has MySql again. Do you have any idea when it is going to be released?

**Comment by hannahramadan** [comment]
Thank you for testing, @rodolfoburla! We are planning a release the first week of December and will include this fix. I will follow up here when it is live.

**Comment by rodolfoburla** [comment]
Thank you @hannahramadan, btw once it is released I think you should update the documentation here: https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/#instance_details .

**Comment by hannahramadan** [comment]
Ruby agent [v9.16.1](https://rubygems.org/gems/newrelic_rpm/versions/9.16.1) is now avaliable and includes this fix. Docs are in the process of being updated. Thanks everyone for the help!
cc @rodolfoburla @gdubicki
