### ISSUE TITLE
When will this gem update to browser agent v1220+?

### ISSUE THREAD

**Issue by dkniffin** [newrelic/newrelic-ruby-agent#2233]
From what I can tell, this gem injects browser agent version 1216 (based on the instructions [here](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/update-browser-agent/))

I am working on changes to be compliant with CCPA law (the California cookie law). In order to do that, I want to eliminate as many tracking cookies as possible from my site. One of the ones I see is `JSESSIONID`. From what I see [here](https://docs.newrelic.com/docs/browser/browser-monitoring/page-load-timing-resources/new-relic-cookies-used-browser/), this is a deprecated cookie that is no longer used after browser agent v1216.

So, when will this gem update to browser agent v1220+?

**Comment by hannahramadan** [comment]
Hi @dkniffin! While the Ruby agent helps the Browser agent get installed, we don't have much control over what the Browser agent is doing. The Ruby agent automatically pulls the latest version of the Browser agent, so I'm not sure why you're seeing a deprecated cookie. 

I recommend reporting this issue in the [Browser agent repo](https://github.com/newrelic/newrelic-browser-agent) so you can get the right eyes on this issue.

**Comment by dkniffin** [comment]
@hannahramadan Oh strange... now when I follow the instructions [here](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/update-browser-agent/), I see `1.241.0.PROD` in the source, which I'm guessing means I've got version `1241`.

I was definitely seeing an older version the other day. Not sure what changed. But I guess I can close this issue.

**Comment by hannahramadan** [comment]
@dkniffin great news! Glad we got this sorted.
