### ISSUE TITLE
Unused variables in unit tests

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2247]
Running our full suite of Minitest tests reports that the following variables are declared but never used. Each test should be verified to see if the variable can be removed entirely or if the test should be refactored to include the use of the variable.

```
test/new_relic/agent/configuration/manager_test.rb:497: warning: assigned but unused variable - dd
test/new_relic/agent/configuration/manager_test.rb:515: warning: assigned but unused variable - dd
test/new_relic/agent/tracer_test.rb:311: warning: assigned but unused variable - segment
test/new_relic/dependency_detection_test.rb:214: warning: assigned but unused variable - executed
test/new_relic/dependency_detection_test.rb:231: warning: assigned but unused variable - executed
test/new_relic/dependency_detection_test.rb:248: warning: assigned but unused variable - executed
```

These warnings can be reproduced by running: `bundle exec rake test`

**Comment by chahmedejaz** [comment]
Hey @kaylareopelle  - I'd love to work on this issue, can you please assign it to me? Thanks. :)

**Comment by chahmedejaz** [comment]
Sorry, I linked the wrong issue with the PR :sweat_smile:

**Comment by kaylareopelle** [comment]
@chahmedejaz - No worries! You've been assigned to this issue. Thank you for your help. Let us know if you have any questions! 😄
