### ISSUE TITLE
Potential threading issue with add_custom_log_attributes method and Puma

### ISSUE THREAD

**Issue by dinsley** [newrelic/newrelic-ruby-agent#2291]
## Description

We have added some calls to `add_custom_log_attributes`, and it appears that the adding of custom log attributes may be leaking through into the log attributes that get added from other threads. We're tracking some information from a completely separate end-point/flow and log attributes are getting attached to entries that are unassociated, and have confirmed locally that's the case. It doesn't happen when processing in a single threaded environment.

It looks like the agent log aggregator may not be thread and shared from looking through the repository, but I was unable to ascertain if that was for sure. If this functionality is intended to be used globally and not suitable for threaded environments, we can close the ticket.

## Expected Behavior

When using `add_custom_log_attributes` log attributes shouldn't have custom log attributes from other threads attached to them.

## Steps to Reproduce

I have not been able to replicate this locally, but can reliably replicate it in production. I can provide access or any information from our New Relic account if you just let me know what would be needed.

## Your Environment

- Ruby 3.2.2
- Rails 7.0.5
- Puma 6.4.0
- New Relic Agent 9.5.0

**Comment by kaylareopelle** [comment]
Hi @dinsley, thanks for getting in touch with us. It seems that our documentation on the `add_custom_log_attributes` API may need to be improved. 

This API is intended for global use. Any attributes added with this API should be included on all log events for the given agent instance. It is not designed to add unique attributes to a log event per thread.

If I’m understanding you correctly, it sounds like you'd like to have multiple concurrent threads each with their own different log attributes. Does that seem right? If so, let's turn this issue into a feature request.

**Comment by dinsley** [comment]
Thanks for the reply!

That makes sense based on the behaviour I was seeing, updating the documentation there would be handy just incase. I assumed it would work like the other custom attribute helpers for transactions.

That's correct. I was hoping to append metadata to the individual log entries to make it a lot easier for us to track usage, without having to resort to adding data to the log messages themselves or changing formatters, and parse with grok to pull out the data. Some of the log entries also pass the size limits of New Relic, so it makes using the grok approach a little less consistent, depending on what's coming in.

As an example: We're wanting to attach user_id metadata to the log entries, as well as authentication entry points that the user went through. (login, token, oauth) -- That allows is to isolate traffic better to see trends on usage by our customers, by the approach they're using.

I can throw up a pull request for the ruby doc documentation update a bit later to make it more clear that the usage is for global. A feature request would be great as well, thank you!

**Comment by dinsley** [comment]
Pull-request has been opened here: https://github.com/newrelic/newrelic-ruby-agent/pull/2292

I will close this one as its current behaviour is as intended 👍
