### ISSUE TITLE
CONTRIBUTING.md Slack Section Documentation out of date

### ISSUE THREAD

**Issue by dinsley** [newrelic/newrelic-ruby-agent#2293]
## Description

It looks like the CONTRIBUTING.md Slack documentation section is out of date and the links are no longer accessible: 

https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md#slack.

<img width="772" alt="image" src="https://github.com/newrelic/newrelic-ruby-agent/assets/4414/ce068044-d12a-49b0-b629-d5ffebfcd77a">

Noticed when looking to join to ask a few questions and request access to #oss-contributors 😅 

## Expected Behavior

Link to request access, or to join the Slack works

*or*

Section is removed if it's no longer available

**Comment by fallwith** [comment]
Thanks for bringing this to our attention, @dinsley! The `newrelicusers.slack.com` workspace appears to gone from not being particularly active anymore to being entirely unreachable. For now with https://github.com/newrelic/newrelic-ruby-agent/pull/2305 I have removed the reference to that workspace from our documentation. I will update the documentation again in the future if I learn of any replacements or alternatives to the Slack workspace.

In the meantime, Rubyists can create a GitHub issue in this repo for any questions or comments. They can make use of the New Relic Explorer's Hub referenced in `CONTRIBUTING.md`. They can use the GitHub handles listed in `github/CODEOWNERS` to mention us in any GitHub context (such as an issue in the repo of a gem that we have instrumentation for). Or they can create a GitHub issue here to bring a publicly available conversation (via Discord or whatnot) to our attention.
