### ISSUE TITLE
Spec: Truncate custom event attributes

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#2356]
The ruby agent does not truncate custom event attributes currently, but attributes that are longer than expected will be dropped by the collector. To align with the current spec, we should implement truncation for the follow: 

> Custom event names **MUST** be limited to 255 characters. 
> Custom event attribute values **MUST** be limited to a maximum of 4095 characters. 
> Custom event attributes **MUST** be limited to a maximum of 64 attributes.

[Spec PR](https://source.datanerd.us/agents/agent-specs/pull/648)

**Comment by kaylareopelle** [comment]
Completed by #2401
