### ISSUE TITLE
Explore options for AWS Lambda instrumentation

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2364]
### Description
Intention is that we provide the ability to instrument [AWS Lambda functions](https://docs.aws.amazon.com/lambda/latest/dg/lambda-ruby.html). Need to identify the best way to achieve that; is it using the existing Ruby agent - perhaps in `lite` mode? Some other component?

### Acceptance Criteria
- Needs to power our current APM experience.
- Needs to have a Lambda Layers deliverable

### Design Consideration/Limitations
N/A

### Dependencies
TBD

### Additional context
Research spike. After determining what's feasible, we should identify the work needed in the future.

**Comment by fallwith** [comment]
Here's where we're at currently for alignment with the existing NR Lambda spec:

**Complete**

- The absence of a config file should be expected and not warned about
- The absence of a license key should be expected and not disable any agent functionality
- The preconnect and connect actions should be skipped
- The actions to connect to the collector and relay POST requests should be modified and JSON blobs should be written out locally instead
- The JSON blobs must be formatted in a specific way with additional Lamdba specific metadata and always utilize compression
- The presence of a function name environment variable must force serverless mode to be enabled
- The presence of a standard NR output file location should be detected and overwrite the STDOUT output default
- An apdex_t value must be permitted to be set via an environment variable


**In Progress**

- A `lambda_handler` API must exist to process the AWS context object
- Need to map 2 event types to `WebTransaction` and all others to `Other`
- For web requests, parse out HTTP info from both the request and response
- Extract event source information. Successfully extracted info goes in the metadata hash. Other info is omitted from the hash.
- Cold start detection
- Distributed tracing support via 3 new environment variables
- Apply adaptive sampling with target (10) and target period in seconds (60) values

**Comment by fallwith** [comment]
All agent work is now ready for review with 2474. Other NR repos for Lambda and documentation will still need to be updated.

**Comment by fallwith** [comment]
The original scope of this one has been satisfied. We're code complete and will track testing, documentation, and updates to relevant CI/CD repos separately with other issues.
