### ISSUE TITLE
[Spike] Add support for OpenAI Instrumentation

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2365]
### Description
Add agent instrumentation support for the OpenAI SDK, including support for user feedback.

### Acceptance Criteria
TBD

### Design Consideration/Limitations
TBD

### Dependencies
TBD

### Additional context
The Python Team has implemented this. These docs can serve as a starting point for understanding.

OpenAI: [Python Agent OpenAI Instrumentation](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2961604827/Python+Agent+OpenAI+Instrumentation)
User Feedback: [AI Feedback CDD](https://newrelic.atlassian.net/wiki/spaces/AIO11y/pages/3000696867/AI+Feedback+CDD)

**Comment by kaylareopelle** [comment]
[Spike document](https://docs.google.com/document/d/1x8ku6D_CNEM2bzyEWbyFsdOCsWCvBnYS1jAFCYKxwzM/edit?usp=sharing)  (Internal) describing the work and anticipated effort to make OpenAI ready for the GA release.
