### ISSUE TITLE
Refactor local_environment.rb methods

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2388]
Many of the methods inside `lib/new_relic/local_environment.rb` consist of a single `if` statement. Let's clean up these methods by doing an early return instead.

For example:

```diff
def check_for_falcon
-   if defined?(::Falcon::Server) && NewRelic::LanguageSupport.object_space_usable?
+   return unless defined?(::Falcon::Server) && NewRelic::LanguageSupport.object_space_usable?

  @discovered_dispatcher = :falcon if find_class_in_object_space(::Falcon::Server)
end
```

**Comment by fransan6** [comment]
Morning! I can give this a go if it's still an Issue?

**Comment by fallwith** [comment]
> Morning! I can give this a go if it's still an Issue?

Hi @fransan6! Thanks very much for taking a look at this one. I've gone ahead and assigned it to you.
