### ISSUE TITLE
Resque instrumentation can require `resolv-replace` which will become a bundled gem in Ruby 3.4

### ISSUE THREAD

**Issue by Earlopain** [newrelic/newrelic-ruby-agent#2396]
## Description
`resolv-replace` will get the same treatment as `base64` (see #2238/#2378/[ruby changelog](https://github.com/ruby/ruby/blob/master/doc/NEWS/NEWS-3.3.0.md#stdlib-updates)). This means that for users running Ruby 3.3 that set `resque.use_ruby_dns` to true a warning will be logged, and for Ruby 3.4 (when it gets released next year) an error will be thrown.

I tried finding this warning in the CI output here but I think this code path isn't being exercised in tests. This is the corresponding code:
https://github.com/newrelic/newrelic-ruby-agent/blob/fd98f889d7e110e99b93c58fe68badef37cb3888/lib/new_relic/agent/instrumentation/resque.rb#L29

Note that I haven't actually tested this myself in a proper environment, I'm just going through gems I currently depend on that make use of these gems without declaring them.

## Expected Behavior
No warning is logged.

## Steps to Reproduce
Set `resque.use_ruby_dns` to true with Ruby 3.3

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by tannalynn** [comment]
Thank you for bringing this to our attention, we didn't realize this. We'll take a look!

**Comment by fallwith** [comment]
For this issue to be addressed in the same manner as #2378, we'd want to store a fork of [resolve-replace.rb](https://github.com/ruby/resolv-replace/blob/master/lib/resolv-replace.rb) locally and then reference it with a `require_relative` and remove the existing `require`.

We welcome community PR submissions for this change and if in the absence of any we'll want to get after this some time in 2024.
