### ISSUE TITLE
Add support for Logstasher

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2399]
### Is your feature request related to a problem? Please describe.
From the support issue:

- "Logstasher functions in a way that is not compatible with the way the agent instruments the Ruby Logger class."
- "Currently the log decorator isn't compatible with json logs, so that would also need to be implemented."

### Feature Description
Add ability to automatically instrument and forward Logstasher logs. Additionally, add local log decoration.

### Describe Alternatives
N/A

### Additional context
Original FR - [NR-169467](https://new-relic.atlassian.net/browse/NR-169467)

### Priority
Really Want

[NR-169467]: https://new-relic.atlassian.net/browse/NR-169467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kaylareopelle** [comment]
Relates to #2341, since they both have the JSON-style logs. The agent spec on JSON log formatted logs must be merged before we can work on this.

**Comment by fallwith** [comment]
As @kaylareopelle mentions above in reference to #2341, there are 2 key aspects to this issue:

- Supporting JSON formatted log data
- Supporting the Logstasher gem's functions

When we work on this one, let's be sure that the JSON handling side of things is implemented generically for re-use by Semantic Logger and other JSON based logger libraries, whether that means code reuse with modules or some other DRY approach.
