### ISSUE TITLE
Increase log events per minute limit

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2400]
### Is your feature request related to a problem? Please describe.
Using the Ruby agent and finding that we've maxed out the application_logging.forwarding.max_samples_stored config.

### Feature Description
Would like to be able to increase the log events per minute limit, which is currently 100,000, because logs being dropped.

### Describe Alternatives
N/A

### Additional context
Original FR - [NR-171151](https://new-relic.atlassian.net/browse/NR-171151)

### Priority
Really Want

**Comment by kaylareopelle** [comment]
Unfortunately, the Ruby agent does not control how many log events can be ingested per minute. This is controlled by services that interact with the data after the agent hands it off. We'll re-route this request to teams who have the power to update the max.
