### ISSUE TITLE
OpenAI: Documentation

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2409]
- Note the need for increased custom_insights_events.max_samples_stored value if you’re using OpenAI for AIM events (should set to 100k)
- Note manual addition of the conversation ID using the add_custom_attributes API
- Verify whether anything else is needed/is happening as a cross-agent effort
- Update Ruby-specific docs with mention of the new APIs, the library support, etc.

**Comment by kaylareopelle** [comment]
I'm collaborating with Alexa Kristensen on the documentation for this project. As of 2/14/2024, I've sent her Ruby-related copy for configuration and installation.

**Comment by kaylareopelle** [comment]
PR: https://github.com/newrelic/docs-website/pull/15830

I've provided an initial review on the Ruby-related content. I still need to provide a code example for how to use the feedback API.

**Comment by hannahramadan** [comment]
Reviewed AI docs and provided feedback to docs team!
