### ISSUE TITLE
[Spike] Fix docs website automation

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2423]
Changes made to the GH newrelic organization have broken our actions that automate updates to newrelic/docs-website. 

```
  `newrelic` forbids access via a personal access token (classic). Please use a GitHub App, OAuth App, or a personal access token with fine-grained permissions.
```

One fix was attempted by creating a personal token from the ruby agent bot account with pulls permissions. I think additional permissions are required to get things working again.

**Comment by hannahramadan** [comment]
Automation has been fixed!
Test automated PR: https://github.com/newrelic/docs-website/pull/16800
