### ISSUE TITLE
Cleanup instrumentation info-level logging

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2434]
When the agent instruments a customer's app, it records a log message about what is being instrumented, for example: `Installing Fiber instrumentation`. We often hard-code this log in instrumentation files. However, the method `log_and_instrument`, which is called whenever preprend or chain is used, also logs instrumentation and records a supportability metric. This results in cases where instrumentation notices are logged twice, or potentially not at all, and supportability metrics are not recorded.

```ruby
def log_and_instrument(method, instrumenting_module, supportability_name)
  supportability_name ||= extract_supportability_name(instrumenting_module)
  NewRelic::Agent.logger.info("Installing New Relic supported #{supportability_name} instrumentation using #{method}")
  NewRelic::Agent.record_metric("Supportability/Instrumentation/#{supportability_name}/#{method}", 0.0)
  yield
end
```

We should review each instrumentation file to:
- [ ] Remove log messages if preprend or chain is being used
- [ ] Add a log statement if preprend or chain is not being used
- [ ] Record a supportability metric if preprend or chain is not being used
- [ ] Update Thor instrumentation to remove the log statement and add a comment about log_and_instrument so we can remember this 

`default_source.rb` can be used to quickly determine if prepend or chain is avaliable or not.

dupe: https://github.com/newrelic/newrelic-ruby-agent/issues/2516

**Comment by fallwith** [comment]
Please re-test #2516 after closing this issue and then either close #2516 or specify that additional work still needs to be done to address it.
