### ISSUE TITLE
OpenAI: Attach custom attributes to llm_events when prefixed with `llm.`

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2437]
Customers should be able to add custom attributes to a transaction via `add_custom_attribute` API. If a custom attribute is prefixed with `llm.`, we should automatically attach it to the llm event, ie `llm.<user_defined_metadata>` 

The conversation_id is now being handled like any other llm.* custom event and should be added to all events when available. Update the references to `conversation_id` to use this new `llm.` style.

Let's make sure the attributes are applied to all custom events. Not just chat completion summaries.

We should make sure this is captured in documentation and may need to additionally describe this functionality in the [reserved keyword](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data/#reserved-words) docs.

**Comment by kaylareopelle** [comment]
While we're working on this, let's make sure the attributes are applied to all custom events. Not just chat completion summaries. 

The `conversation_id` is now being handled like any other `llm.*` custom event and should be added to all events when available.

**Comment by hannahramadan** [comment]
@kaylareopelle Yes let's throw that on here ◡̈

**Comment by hannahramadan** [comment]
@kaylareopelle jsky Im going to remove `conversation_id` in a different PR. It'll touch a lot of files and I dont want that to detact from this addition!
