### ISSUE TITLE
Rails 7.1 ArgumentError: wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by Deekor** [newrelic/newrelic-ruby-agent#2469]
Since upgrading to rails 7.1 we get `ArgumentError: wrong number of arguments (given 3, expected 2)` when newrelic attempts to record an error

## Environment
Rails `7.1.3`
Ruby `3.2.2`
newrelic_rpm `9.7.1`

## Additional context
![image](https://github.com/newrelic/newrelic-ruby-agent/assets/1904267/fd991d71-1b22-461b-b61f-d977667c0153)

**Comment by fallwith** [comment]
Hi @Deekor,

We're sorry to hear that you ran into some issues as a result of the Rails upgrade.

Would you please give us some more information on how we might reproduce the problem? We regularly test with Rails v7.1 and Rails EDGE and haven't yet ran into this problem. If we can be shown how to reproduce an issue, we'll gladly update our tests and work on a fix.

The [New Relic Ruby agent middleware ](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/middleware_tracing.rb#L109)doesn't do anything that is Rails version dependent when it comes to error handling. It creates a New Relic error payload to report the error to New Relic and then re-raises. It doesn't make use of any Rails APIs, so it shouldn't be impacted by a version upgrade or caught sending 3 arguments to any methods expecting 2.

The stack trace you provided seems to suggest that ActionDispatch v7.1.3 is receiving a call made to `ActionDispatch::DebugExceptions#call`, and an exception is caught. That `#call` method's `rescue` block then [performs](https://github.com/rails/rails/blob/7-1-stable/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L44) a `render_exception` call with 3 arguments. `ActionDispatch::DebugExceptions#render_exception` expects 3 arguments, so it should work.

Do you happen to know which specific method is complaining with `ArgumentError: wrong number of arguments (given 3, expected 2)` and which specific caller method is calling it with only 2 arguments?

Without sending us any sensitive data or proprietary business logic, do you any code that could reliably reproduce the error? If not, do you know what steps we could take with a fresh new Rails v7.1.3 app to reproduce the error?

Any information about any first party or third party middleware that you are using in addition to New Relic's would also be helpful.

**Comment by Deekor** [comment]
Thanks for the comment - it pointed us in the right direction and turned out to be another gem that was out of date.
