### ISSUE TITLE
Cloud GUIDS: Instrument AWS SDK's Seahorse

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2497]
With a primary focus on generating cloud guids (an arn in the case of AWS) and a secondary focus on providing metrics segments for AWS SDK client calls, we should instrument the [Seahorse::Client::Base](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/base.rb) class provided by `aws-sdk-core` (limiting support to v3+).

As of the latest (February 2024) release, the "install everything, please" `aws-sdk-resources` gem declares 378 dependencies on other `aws-sdk-*` gems. Given that the client classes in these other gems all inherit from Seahorse, it makes sense to go after Seahorse first and fill in any gaps in coverage later.

**Comment by tannalynn** [comment]
After looking into it, instrumenting seahorse wouldn't give us the information we need, so we will have to instrument each gems clients individually.
