### ISSUE TITLE
OpenAI: Improve performance of OpenAI Net::HTTP response headers check

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2499]
Currently, we run a `match?` on every Net::HTTP request regardless of whether OpenAI instrumentation is enabled. Let's make this code less intrusive for users who aren't using Open AI. 

Some ideas suggested by the team:
* Add a memoized check on the AI config setting to control whether the headers are parsed
* Create a second version of Net::HTTP instrumentation to prepend when OpenAI is present

**Comment by hannahramadan** [comment]
Completed with #2512
