### ISSUE TITLE
Rails Content-Type header without modification deprecation warning

### ISSUE THREAD

**Issue by internethostage** [newrelic/newrelic-ruby-agent#2500]
## Description
We noticed an incredible amount of deprecation warnings related to this `content_type` behaviour change:
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#actiondispatch-request-content-type-now-returns-content-type-header-as-it-is

This is triggered by the query to `content_type` done on the agent ([link to relevant code](https://github.com/newrelic/newrelic-ruby-agent/blob/9.7.1/lib/new_relic/agent/transaction/request_attributes.rb#L27))

## Expected Behavior
This is not necessarily a bug, the deprecation warning is mostly a heads up.
Why I bring up this issue is to ensure that this change won't affect the new relic gem, and so that I can safely add this warning to our ignore list.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
On a rails 7.0 app, any request with the agent active should display this deprecation warning.

## Your Environment
ruby 3.2.2
rails  7.0.8
newrelic_rpm 8.14

## Additional context
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#actiondispatch-request-content-type-now-returns-content-type-header-as-it-is

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by hannahramadan** [comment]
Hi @internethostage—thank you for the heads up! We will explore how this change affects the agent and get back to you.

**Comment by hannahramadan** [comment]
@internethostage It looks like this was a change Rails made in major version 7 (listed in their [upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0 ) 6.1 to 7), and its quite a change so it makes sense why they're being loud with warnings!

This doesn't impact the Ruby agent in a breaking way. You can safely add this warning to your ignore list.

Where we previously reported content type as `'text/csv'`, for example, we now report something like `'text/csv;header=present;charset=utf-16'`. This isn't how we want to represent content type, so we will have to make that update on our end (#2506). Thanks again for bringing this to our attention!
