### ISSUE TITLE
Retest linking of error traces to transactions and update agent implementation

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2518]
### Description
Since the completion of #2129 , there have been changes in both the agent spec as well as the server-side implementation that may prevent successfully linking error traces to transactions.

Now that the server-side implementation is available, we need to retest end-to-end that linking occurs successfully, whether Distributed Tracing is enabled or disabled.

### Acceptance Criteria
Coordinate with the #help-error-tracking team on testing. Test and confirm whether our agent functions as expected. Based on that, determine what - if any - changes are needed.

Review the [agent spec](https://source.datanerd.us/agents/agent-specs/blob/f1fadba677d6e9f31bf9b7025dd832a8cb0267fe/Errors.md#traced-errors). Determine whether our agent is in compliance with the required aspects of the spec and based on that, determine what - if any - changes are required.

### Design Consideration/Limitations
Need to ensure that linking occurs whether Distributed Tracing is enabled or not.

### Dependencies
N/A

### Additional context
N/A

### Estimates
_Please provide initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_

**Comment by kmudduluru** [comment]
we need to verify that guid is available in both TransactionError Event and ErrorTrace json events regardles of DT setting (on/off) .

**Comment by kford-newrelic** [comment]
@fallwith let's capture the end-to-end test results [here](https://docs.google.com/document/d/1E-YNzUGPI8k6BvMvDU3YhgXb0SY3mGxyn3sQoj21VPw/edit#heading=h.44upugl2nmpg)

**Comment by kmudduluru** [comment]
@fallwith For now the scope is only for ErrorTrace and TransactionError events. Updated the Agent Ask doc as well.

**Comment by fallwith** [comment]
NOTE: The original work was requested with #2036 and satisfied with #2035 and then later enhanced with #2137.

**Comment by fallwith** [comment]
With #2521, the transaction guid will now be added to both ErrorTrace and TransactionError types instead of just the latter. We have audited all pathways through the code and confirmed all desired behavior with DT on and off.
