### ISSUE TITLE
Update configuration rake task

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2532]
When running locally the rake task to update our docs website configurations, and comparing it to what our docs website currently has, it appears our rake task is out of date with changes the docs team (or we) made directly to the website without updating the rake task. To see these changes:

1. Locally run `bundle exec rake "newrelic:config:docs[html]"`
2. Pull the latest `ruby-agent-configuration.mdx` file and do a diff with what our agent produces

We should do a comparision and update our rake task where it makes sense.

NOTE: Our configuration rake task runs on every release.

**Comment by kaylareopelle** [comment]
This has been resolved!
