### ISSUE TITLE
Setup Ruby team members as doc website CODEOWNERS

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#2533]
The Ruby agent has some automation of updates to the docs website - including confuguration updates. Our automation overwrites any changes made directly to those files, which is done occasionally by the docs team. We should set up Ruby team members as CODEOWNERS of at least `ruby-agent-configuration.mdx` although we may want to consider adding others files too. 

[GitHub CODEOWNERS instructions. ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

**Comment by kaylareopelle** [comment]
[Internal conversation](https://newrelic.slack.com/archives/C0DSGL3FZ/p1711727096139949) about an alternate solution, creating a CI workflow that will fail unless a user on a specified allowlist created the change.

**Comment by kaylareopelle** [comment]
An alternate solution has been implemented by the docs engineering team: https://github.com/newrelic/docs-website/pull/16742 

Now, whenever a user not on the allowlist (@newrelic-ruby-agent-bot, @fallwith, @tannalynn, @hannahramadan, @kaylareopelle) includes file changes to the Ruby agent configuration doc in a PR, a workflow will fail and a comment will be posted on the PR telling the user to submit an issue or PR for the change to the newrelic-ruby-agent repo.
