### ISSUE TITLE
elasticsearch instrumentation causing exceptions with new ElasticSearch gem v8.13.0

### ISSUE THREAD

**Issue by randypuro** [newrelic/newrelic-ruby-agent#2541]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description

The elasticsearch instrumentation is resulting in an incorrect number of arguments exception:

```
ArgumentError - wrong number of arguments (given 6, expected 2..5):
  newrelic_rpm (9.8.0) lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:13:in 'perform_request_with_tracing'
  newrelic_rpm (9.8.0) lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in 'perform_request'
  elasticsearch (8.13.0) lib/elasticsearch.rb:86:in 'verify_elasticsearch'
  elasticsearch (8.13.0) lib/elasticsearch.rb:69:in 'method_missing'
  elasticsearch-api (8.13.0) lib/elasticsearch/api/actions/search.rb:106:in 'search'
```

## Expected Behavior
Tell us what you expected to happen.

There should be no error raised

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

newrelic-ruby-agent gem 9.8.0
elasticsearch gem 8.13.0
ruby 3.2.3

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

I do not understand why the error does not occur with elasticsearch 8.12.2; however, it's true that the `elasticsearch-api (8.13.0) lib/elasticsearch/api/actions/search.rb:106:in 'search'` sends 6 arguments down through the perform_request chain; however, the `newrelic_rpm (9.8.0) lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:13:in 'perform_request_with_tracing'` prepended method only accepts 5 arguments. Perhaps that method should be rewritten to support varargs given it only depends on a few of the arguments?

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by kaylareopelle** [comment]
Hi @randypuro! Thanks for bringing this to our attention! 

I think you're on the right track. We likely need to update the way arguments are defined in the `perform_request_with_tracing` method to support version 8.13.0. We'll take a closer look and get back to you soon.

In the meantime, if you would like to keep using elasticsearch 8.13.0, you can disable New Relic's elasticsearch instrumentation by updating your configuration.

You can update your newrelic.yml file to include:
`instrumentation.elasticsearch: disabled`

Or use an environment variable:
`NEW_RELIC_INSTRUMENTATION_ELASTICSEARCH=disabled`

**Comment by kaylareopelle** [comment]
Hi @randypuro! I have a branch with a potential solution. 

If you'd like to test it out, you can update the `newrelic_rpm` line in your gemfile to: 
`gem 'newrelic_rpm', github: 'newrelic/newrelic-ruby-agent', branch: 'elasticsearch-fix'`

**Comment by kaylareopelle** [comment]
Small update, @randypuro -- support for Elasticsearch 8.13.0 will be included in our next release. I'll leave the `elasticsearch-fix` branch open until we release so that you or anyone else who comes across this issue can use it.
