### ISSUE TITLE
[Spike] k8s Operator Pattern

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2569]
### Description
Get familiar with the k8s [operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) 

### Acceptance Criteria
Research spike. Gain familiarity, determine what is needed to support this

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
[k8s auto injection](https://opentelemetry.io/docs/kubernetes/operator/automatic/)
[CDD](https://newrelic.atlassian.net/wiki/spaces/INST/pages/3308224605/K8s+Operator+for+APM+Agents)
[NR-260140](https://new-relic.atlassian.net/browse/NR-260140)

[NR-260140]: https://new-relic.atlassian.net/browse/NR-260140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hannahramadan** [comment]
- [Notes](https://docs.google.com/document/d/1bbcUy6r5pqQgoXYF4o8kbQn7AjiNhrlQTcKqehC55OA/edit?usp=sharing)
- [Milestone](https://github.com/newrelic/newrelic-ruby-agent/milestone/94)
- Created payground using docker and k8s
