### ISSUE TITLE
k8s: Create injection script

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2574]
### Description
Create a script written in Go that is responsible for injecting agent code into the customer's application container(s).

The [newrelic-agent-operator](https://github.com/newrelic-experimental/newrelic-agent-operator) repository is an OTel [fork](https://github.com/open-telemetry/opentelemetry-operator) which already includes the Go scripts for a few languages, but not Ruby. Here are the other langauages [scripts](https://github.com/newrelic-experimental/newrelic-agent-operator/tree/main/pkg/instrumentation). 

The Ruby agent code is injected into the customer’s application via a RUBYOPT environment variable that points to a setup script. This setup script uses the [bundle add utility](https://bundler.io/v2.5/man/bundle-add.1.html), which updates the dependency manifest and re-installs the dependencies.

Additionally, logic may need to be added to the injection script to not install the agent if an agent is already installed in the customer’s application container(s). For most agents this will likely be done by looking for the presents of certain environment variables within the customer’s application container. For example, a new relic license key. (This is very TBD at the moment-we will likely have a dedicated discussion about this and how we can/want to detect this.) The goal here is simply to not automatically install an agent into a container in which an application already has an agent installed.

Let's also consider contributing our Ruby script back to OTel.

**Comment by hannahramadan** [comment]
Go file: https://github.com/newrelic-experimental/newrelic-agent-operator/commit/a548a544b576e16dea393a002d03b8bf3e781d2f

**Comment by hannahramadan** [comment]
Closed with https://github.com/newrelic/newrelic-ruby-agent/pull/2635
