### ISSUE TITLE
Aws: Instrument elasticache-redis

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#2589]
Verify existing Redis instrumentation creates the entity relationship
Spin up a Ruby service in AWS that connects with an Elasticache Redis cluster

This covers: AWS_ELASTICACHE_REDIS_CLUSTER

**Comment by kaylareopelle** [comment]
Redis test environments ready for testing.
memcached environments blocked by elastic IP problem.

**Comment by kaylareopelle** [comment]
Reopening until testing passes upstream
