### ISSUE TITLE
CI: Upgrade to a newer version of Node for our SimpleCov action

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2597]
Node 16 is deprecated. Similar to #2584, we should update our SimpleCov action to, at a minimum, use Node 20, but preferably, use Node 22 or the latest version whenever this ticket is worked on.

<img width="1412" alt="Screenshot 2024-04-24 at 12 11 16 PM" src="https://github.com/newrelic/newrelic-ruby-agent/assets/87386821/065b5aa1-de9d-4dda-b044-365a7adac7d9">

Currently, we have a forked copy of this action living in the `.github/actions` directory. There may be multiple changes in our fork from the original, but one of the features is the addition of branch coverage percentages in the comments added to PRs after test runs.

We could also consider, as part of this ticket, contributing our changes to the original action or pushing up a fork of our action with our added functionality.

**Comment by kaylareopelle** [comment]
Thank you, @prateeksen! We've created issues for all the outdated actions. You can find them under https://github.com/newrelic/newrelic-ruby-agent/labels/ci%20node%20updates

**Comment by kaylareopelle** [comment]
PR for similar work in csec-ruby-agent: https://github.com/newrelic/csec-ruby-agent/pull/78/files

**Comment by prateeksen** [comment]
The above mentioned PR has incomplete changes: Please follow the relevant changes from all of these PRs:
https://github.com/newrelic/csec-ruby-agent/pulls?q=is%3Apr+head%3Agha+is%3Aclosed+head%3Aupdate-gha+author%3Aprateeksen

**Comment by prateeksen** [comment]
**[Simplecov-report-action](https://github.com/aki77/simplecov-report-action) is now archived, today. They are suggesting to use: [octocov](https://github.com/k1LoW/octocov)**

**Comment by kaylareopelle** [comment]
Thanks for these updates, @prateeksen!

**Comment by hannahramadan** [comment]
Simplecov was updated in a previous PR. https://github.com/newrelic/newrelic-ruby-agent/pull/2787/files#diff-c4f51a333bc84a9c03d3cf76e88f242bcda512b4f4d4f93fe566dc3e8a57be31L24
