### ISSUE TITLE
[Spike] E2E Test Framework (Agent2Query), Deploy Updated Ruby agents to test process

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2611]
### Description
Intent is that 100% of new agent releases run through new E2E test framework and ensure that data is reporting and getting processed through ingestion pipeline.

Make as part of the release process updating and redeploying the sample service on each new agent version release with the updated agent.

Note : This is a research spike to get familiar with the Agent2Query service, existing documentation and to understand how other teams implemented their automation solution.

### Acceptance Criteria
When new agent releases are created, the agent used in the E2E test is updated as well.

As a research spike, the intention is that we understand what needs to be done and create subsequent issues representing that work.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
See the [original work request](https://new-relic.atlassian.net/browse/NR-248765) for additional context.

Note : in Q1, other agent teams have implemented this, so we can understand what others have done and use that as a guide

**Comment by fallwith** [comment]
Idea: on a cron driven daily or hourly basis, poll RubyGems.org for new `newrelic_rpm` releases. That pattern is already used to generate new Lambda layers when new agent releases go live, and having the E2E piece ask instead of being told open up a lot of flexibility and futureproofing.

**Comment by kford-newrelic** [comment]
This was implemented by the team that originally created the test framework. No action needed.
