### ISSUE TITLE
Stripe metrics include ids in the group names

### ISSUE THREAD

**Issue by jdelStrother** [newrelic/newrelic-ruby-agent#2654]
## Description

The Stripe integration sends the bare path as the metric name, leading to lots of metrics like this - 

```
Stripe/v1/events/evt_1PJc8exKnUatkhASXasx/get
Stripe/v1/events/evt_3PJZxsadnUat0yas1dea/get
Stripe/v1/customers/cus_DHYhjqasd21w56W4/sources/card_1JGLF9FiV4PKnUatf31fasdas/get
Stripe/v1/customers/cus_IcnFdy321eraSz6B/sources/card_1I1XezFiV4PKnU12s1asd/get
Stripe/v1/customers/cus_Be9k6IbvKHeRor/sources/card_1BGrR0FiV4PKn4casd@/get
Stripe/v1/subscription_items/si_PawAB/get
Stripe/v1/events/evt_3PJjdQFiV4PKnUAsd9/get
```

which can lead to NewRelic dropping metrics via the DENY_NEW_METRICS rule (https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/troubleshooting/metric-grouping-issues/)

## Expected Behavior

ids are scrubbed from the path to allow metric grouping - maybe something like-  

```
Stripe/v1/events/*/get
Stripe/v1/customers/*/sources/*/get
Stripe/v1/subscription_items/*/get
```

## Steps to Reproduce

Run an app that uses the Stripe gem, newrelic_rpm, and have the `instrumentation.stripe` config enabled.

**Comment by tannalynn** [comment]
Thanks for the feedback on the strip instrumentation! That is a good point for us to look into, I can definitely see how that could lead to a large number of metric names. Currently we use this to create the name
```
        def metric_name(event)
          "Stripe#{event.path}/#{event.method}"
        end
```
So we'll need to take a second look here to see the best way to extract some of the more useful information out of the path while not including those ids, since removing `event.path` completely would leave metric names that simply look like "`Stripe/get`".

**Comment by jdelStrother** [comment]
Yeah, agreed. All the stripe ids I know of are 2-3 letters (eg `cus`, `sub`, `in`), then an underscore, then a bunch of letters/numbers - I wondered if you might be able to do some regex magic to scrub those.
(yes yes, and then you have two problems 😛)

**Comment by kford-newrelic** [comment]
@jdelStrother thank you for giving us this feedback - our engineers agreed with you that our current instrumentation behavior is not desirable - we plan to take this up during the next quarter.

However, it was also agreed that, though not desirable, the current behavior isn't a `bug` per se, so we'll be treating this as an enhancement (which likely won't matter to you)

**Comment by kford-newrelic** [comment]
Overruled by engineers. Re-classifying as a `bug`

**Comment by fallwith** [comment]
Hi @jdelStrother. We've put together #2716 to address this issue. NOTE that it grabs only the first two elements from the path and strips away everything else.

So given a path of "/v1/payment_methods/pm_8675309", the metric name will now be "Stripe/v1/payment_methods/get".

This differs from your original theorized idea in 2 ways:

- We don't use an asterisk placeholder replacement for the stripped away content
- We don't only strip out ids, so your original `Stripe/v1/customers/cus_IcnFdy321eraSz6B/sources/card_1I1XezFiV4PKnU12s1asd/get` metric name would now appear as `Stripe/v1/customers/get` instead.

If either of those differences are an issue for you, or if you have any feedback for the PR, please let us know.

The fix will go out in the next agent release, but you are welcome to test the change by pointing at the `stripefix` branch before then:

```ruby
gem 'newrelic_rpm', github: 'newrelic/newrelic-ruby-agent', branch: 'stripefix'
```

Thanks again for bringing this issue to our attention!

**Comment by jdelStrother** [comment]
Sounds good - I think that approach sounds fine

**Comment by fallwith** [comment]
Hi @jdelStrother. `newrelic_rpm` v9.11.0 has just been released to RubyGems.org with the Stripe metric naming logic fix.
