### ISSUE TITLE
Add Rails 7.2-specific test environments

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2671]
Presumably Rails v7.2 will be available by the time #2266 is complete. Once it is, we should create a Rails v7.2 specific environment as well.

**Comment by kaylareopelle** [comment]
@fallwith, is this a dupe of #2650?

**Comment by fallwith** [comment]
@kaylareopelle I say we leave this one to specifically focus on the `test/environments/rails72` directory being created and allow #2650 to deal with things like reviewing the v7.2 changelog, auditing to see if there were new notifications created, etc. If #2650 ends up creating the `test/environments/rails72` directory, that'll be great. But given that we still have #2266 (asking for a `test/environments/rails71` directory) after adding support for v7.1, I want to make sure v7.2's directory creation happens too.

**Comment by fallwith** [comment]
We've added the v7.2 environment and this one is good to close.
