### ISSUE TITLE
Avoid deprecated Bundler method all_specs

### ISSUE THREAD

**Issue by jcoyne** [newrelic/newrelic-ruby-agent#2733]
```
 [DEPRECATED] Bundler.rubygems.all_specs has been removed in favor of Bundler.rubygems.installed_specs
 ```
 
 This is used in several places:
 https://github.com/search?q=repo%3Anewrelic%2Fnewrelic-ruby-agent%20all_specs&type=code

**Comment by hannahramadan** [comment]
Hi @jcoyne! Thank you for letting us know about this. We still support Bundler v1, which doesn’t have the new `installed_specs` method, so we won’t be able to switch the methods out. However, we will look into silencing this warning for newer Bundler users. For now, I’m going to remove the bug label for housekeeping purposes.

**Comment by gstokkink** [comment]
@hannahramadan can't you check whether `installed_specs` is present and call that instead of `all_specs`?

**Comment by hannahramadan** [comment]
Thank you again for sharing this issue with us @jcoyne! We are including a [fix](https://github.com/newrelic/newrelic-ruby-agent/pull/2823) for this in our next release, 9.13.0, which should be available within the next week. cc @gstokkink

**Comment by gstokkink** [comment]
@hannahramadan thanks for the quick follow-up!

**Comment by hannahramadan** [comment]
[Ruby agent 9.13.0](https://rubygems.org/gems/newrelic_rpm/versions/9.13.0) is live and includes this update.

Closed by: https://github.com/newrelic/newrelic-ruby-agent/pull/2823
