### ISSUE TITLE
Replace API key with access token in artifactory

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2736]
### Description
Frog (Artifactory) is removing support for API keys. Action is required by API key users to ensure compliance and maintain secure access.

To migrate to access token, you can use the UI to generate a new Identity Token, follow this steps to [create it](https://jfrog.com/help/r/platform-api-key-deprecation-and-the-new-reference-tokens/how-to-get-an-identity-token-in-3-steps). The identity token is an Access Token that is scoped to a specific user’s permissions. After its creation, replace the API key with the generated token where needed.

### Acceptance Criteria
The new access token is put in place and used.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
[Dev Announcement](https://newrelic.slack.com/archives/C027NFCDZ2P/p1714744802092249)

[Original WR](https://new-relic.atlassian.net/browse/NR-281772)

**Comment by fallwith** [comment]
N/A for us currently, given our use of public GitHub and public RubyGems.org publications
