### ISSUE TITLE
Fix `falcon` dispatcher detection

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2778]
In our environment report, the `falcon` dispatcher is not being identified. 

According to @prateeksen, the code never reaches [this](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/local_environment.rb#L148) line

**Comment by prateeksen** [comment]
@kaylareopelle I have done a little more digging and found that [find_class_in_object_space](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/local_environment.rb#L148) method returns `nil` until the `::Falcon::Server` class is actually loaded into the object space and server is started. And the twist here is that, by the time this class is loaded into object space, and `find_class_in_object_space` returns `:falcon` Environment report is already sent from the agent from [here](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/agent_helpers/connect.rb#L105) with `nil` value in dispatcher in environment report.
I tried to return `:falcon` without checking [this](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/local_environment.rb#L148) if condition, but in that case agent's worker thread is not initiated and that got initiated when I fired a curl request on application.
Could you please look into it from here, why the agent's worker not initiated without calling [find_class_in_object_space](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/local_environment.rb#L148)

**Comment by kaylareopelle** [comment]
Hi @prateeksen, thanks for digging in! I'll take a look this week as part of my hero duties.

**Comment by kaylareopelle** [comment]
Hi @prateeksen, what's the priority on this issue? I think we may need to include it in our regular planning cycle to make meaningful progress.

**Comment by prateeksen** [comment]
Hi @kaylareopelle This is comparatively low priority than https://github.com/newrelic/newrelic-ruby-agent/issues/2777.
