### ISSUE TITLE
Redis Cluster causes instrumentation error

### ISSUE THREAD

**Issue by jdelStrother** [newrelic/newrelic-ruby-agent#2814]
## Description

I noticed this in my newrelic_agent.log:

```
[2024-08-15 14:11:05 +0000 app1-1 (690412)] ERROR : Error while installing redis_instrumentation instrumentation:
[2024-08-15 14:11:05 +0000 app1-1 (690412)] ERROR : LocalJumpError: unexpected return
```

I'm guessing this is due to the `return` here - https://github.com/newrelic/newrelic-ruby-agent/blob/4c5c8dbdf6396154262dccb505e4558652673e48/lib/new_relic/agent/instrumentation/redis.rb#L33-L49
 which is invalid outside of a method

**Comment by fallwith** [comment]
Hi @jdelStrother. Thanks very much for the report and hypothesized synopsis which seems spot on to me. We'll take a look.

**Comment by fallwith** [comment]
Hi @jdelStrother. A fix for this bug has hit our dev branch and will be available in the next agent release. Thanks for your help.
