### ISSUE TITLE
Add agent support to emit linking data for AWS_ELASTICSEARCH_CLUSTER

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2860]
### Description
Enhance existing agent instrumentation to emit data needed for creating entity relationships.

### Acceptance Criteria
Successful end-to-end validation of created entity relationships.

### Design Consideration/Limitations
Pattern after the solution used by the Java Agent.

### Dependencies
Successful implementation by the Java Agent.

### Additional context
N/A

**Comment by tannalynn** [comment]
End to end testing complete. Confirmed relationship can be created using existing data provided by the elasticsearch and opensearch gem instrumentation.
