### ISSUE TITLE
Add agent instrumentation and linking data for AWS_LAMBDA_FUNCTION

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-ruby-agent#2861]
### Description
When an APM application is calling an AWS Lambda function, the Ruby Agent should instrument that call and emit data that can be used to create the corresponding entity relationship.

### Acceptance Criteria
Successful end-to-end validation.

### Design Consideration/Limitations
Will need to support the multiple usage scenarios identified by the Java Agent.

### Dependencies
Successful implementation by the Java Agent.

### Additional context
N/A

**Comment by fallwith** [comment]
Addressed with #2926
