### ISSUE TITLE
Deprecated Bundler::RubygemsIntegration#all_specs method

### ISSUE THREAD

**Issue by excelsior** [newrelic/newrelic-ruby-agent#2885]
The bug described in #2733 is still present in 9.14. Namely, the invocation here:

https://github.com/newrelic/newrelic-ruby-agent/blob/9.14.0/lib/new_relic/agent/instrumentation/grape.rb#L23 

```ruby
((Bundler.rubygems.respond_to?(:installed_specs) && Bundler.rubygems.installed_specs.map(&:name).include?('newrelic-grape')) ||
            Bundler.rubygems.all_specs.map(&:name).include?('newrelic-grape'))
```

This expression checks whether the `newrelic-grape` gem is present using the new method and, if it's not, calls the deprecated method.

**Comment by fallwith** [comment]
Hi @excelsior. Thank you for bringing this to our attention!
