### ISSUE TITLE
Docs say that  Grape, Padrino, and Sinatra aren't supported for Ruby 3.0+ but they certainly are

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2909]
Some old documentation that presumably predates Ruby v3.0 being commonplace and well supported by the agent still notes:

> Please note that Grape, Padrino, and Sinatra aren't supported for Ruby 3.0+.

https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/

**Comment by kaylareopelle** [comment]
Resolved by https://github.com/newrelic/docs-website/pull/19465
