### ISSUE TITLE
Docs list the mysql2 gem twice in the "instance details" section

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2910]
The "instance details" section here has a duplicate listing of the `mysql2` gem:

https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/#instance_details

**Comment by kaylareopelle** [comment]
Resolved by https://github.com/newrelic/docs-website/pull/19444
