### ISSUE TITLE
Trivy nightly scan sometimes fails with TOOMANYREQUESTS error

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2937]
There are a few different errors that have come up during our Trivy nightly security scans.

1. TOOMANYREQUESTS error. If it's not a false positive, is means New Relic is sending more than 44,000 requests a minute.
2. `DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source` https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11661063026/job/32464633007#step:6:128  

Ideas:
Can we update the action to short-circuit if this is the failure reason? Maybe we can perform a looping effort to retry?

**Comment by hannahramadan** [comment]
Trivy was removed with https://github.com/newrelic/newrelic-ruby-agent/pull/2967 and we no longer need to do work on it.
