### ISSUE TITLE
Grape instrumentation renames last segment

### ISSUE THREAD

**Issue by seriousdev-gh** [newrelic/newrelic-ruby-agent#2982]
## Description
Last tracked event (database query, external api request or custom instrumentation anything that newrelic_rpm support) always renamed to "Middleware/Grape/<...>/call" where <...> is class name that implements grape api.

## Expected Behavior
Grape instrumentation doesn't rename any custom instrumentation or instrumentation included in newrelic_rpm gem.

## Steps to Reproduce
It is always reproducible with setup using: rackup + grape + newrelic_rpm

I created very simple example app https://github.com/seriousdev-gh/grape_new_relic_example

![image](https://github.com/user-attachments/assets/9763a3aa-8eed-421b-ac75-7750e60dea02)
In screenshot you can see recieved segments. Example app create two segments with names `Custom/LongProcess/1`, `Custom/LongProcess/2` and durations 1 and 2 seconds respectively. 2 second event must be named `Custom/LongProcess/2` instead of `Middleware/Grape/Main/call`.

## Your Environment
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x86_64-linux]
newrelic_rpm (9.16.1)
Other gem versions in example app.

## Additional context
Found this line of code that i think causes the issue https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/grape/instrumentation.rb#L62

For a workaround in my production app i wrote a monkeypatch:

```ruby
module NewRelic::Agent::Instrumentation # rubocop:disable Style/ClassAndModuleChildren
  module Grape
    module Instrumentation
      extend self # rubocop:disable Style/ModuleFunction

      def name_transaction(route, class_name, version)
        txn_name = name_for_transaction(route, class_name, version)
        NewRelic::Agent::Transaction.set_default_transaction_name(txn_name, :grape)
      end
    end
  end
end
```

**Comment by hannahramadan** [comment]
Hi @seriousdev-gh - Thank you so much for your detailed description and reproduction, and for sharing your workaround—it helped us quickly explore this issue and create a fix. It appears that renaming the last segment was part of an older Grape instrumentation that is no longer relevant. We've updated this part of the code in https://github.com/newrelic/newrelic-ruby-agent/pull/2987, which will go out in our next release.
