### ISSUE TITLE
Bunny Instrumentation not respecting distributed tracing disabled when using message headers

### ISSUE THREAD

**Issue by kfalconer** [newrelic/newrelic-ruby-agent#2983]
## Description
Our logs are filling with the following message:

> WARN : Not configured to accept distributed trace headers

This happens when distributed tracing is disabled, and consuming messages having a header defined. 
I was able to determine that the Bunny instrumentation seems to have the same issue when consuming messages from a queue.

Here, the consumer class calls `NewRelic::Agent::Messaging.wrap_amqp_consume_transaction`
https://github.com/newrelic/newrelic-ruby-agent/blob/9.16.0/lib/new_relic/agent/instrumentation/bunny/instrumentation.rb#L158
then calls
https://github.com/newrelic/newrelic-ruby-agent/blob/9.16.0/lib/new_relic/agent/messaging.rb#L321
then calls
https://github.com/newrelic/newrelic-ruby-agent/blob/9.16.0/lib/new_relic/agent/messaging.rb#L132
and then the log message is generated here:
https://github.com/newrelic/newrelic-ruby-agent/blob/9.16.0/lib/new_relic/agent/distributed_tracing.rb#L102

It seems like checking if tracing is enabled prior to calling `wrap_message_broker_consume_transaction` would resolve the issue. Something like this:

````ruby
      def wrap_amqp_consume_transaction(library: nil,
        destination_name: nil,
        delivery_info: nil,
        message_properties: nil,
        exchange_type: nil,
        queue_name: nil,
        &block)
        tracing_enabled = NewRelic::Agent::CrossAppTracing.cross_app_enabled? ||
                          NewRelic::Agent.config[:'distributed_tracing.enabled']
       
        headers = if tracing_enabled
          message_properties[:headers]
        end
                  
        wrap_message_broker_consume_transaction(library: library,
          destination_type: :exchange,
          destination_name: Instrumentation::Bunny.exchange_name(destination_name),
          routing_key: delivery_info[:routing_key],
          reply_to: message_properties[:reply_to],
          queue_name: queue_name,
          exchange_type: exchange_type,
          headers: headers,
          correlation_id: message_properties[:correlation_id], &block)
      end
````
I was able to confirm the log warnings stopped after disabling instrumentation of bunny. 

## Expected Behavior
There should be no log warning data

## Steps to Reproduce
Using a supported version of Bunny gem, and consuming a message having any headers

## Your Environment
Agent version 9.16.0

## Additional context

I found a similar issue reported here https://github.com/newrelic/newrelic-ruby-agent/issues/341 The issue turned out to be within the Sidekiq instrumentation as well.

**Comment by hannahramadan** [comment]
Thanks for reporting this @kfalconer and apologies for the noise! We've moved this warning to only exist when debug-level logs are enabled. https://github.com/newrelic/newrelic-ruby-agent/pull/2984

Does this work for you? If so, I'll close this issue.

**Comment by kfalconer** [comment]
Yea that works as well. Thanks

**Comment by hannahramadan** [comment]
Closed with https://github.com/newrelic/newrelic-ruby-agent/pull/2984
