### ISSUE TITLE
Log decoration throws an exception when message is nil

### ISSUE THREAD

**Issue by arlando** [newrelic/newrelic-ruby-agent#2985]
## Description

https://github.com/newrelic/newrelic-ruby-agent/blob/8032ce4b30c1b4c79950af14a4a4c876b801683e/lib/new_relic/agent/local_log_decorator.rb#L25

 When using log decoration, if the message is `nil` this throws an error.

## Expected Behavior
Tell us what you expected to happen.

I'm not sure how this is even being triggered if a message is nil. 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.

```
newrelic_rpm (9.15.0) lib/new_relic/agent/instrumentation/logger/instrumentation.rb in format_message_with_tracing at line 58
newrelic_rpm (9.15.0) lib/new_relic/agent/instrumentation/logger/prepend.rb in format_message at line 10
activesupport (6.1.7.10) lib/active_support/logger_thread_safe_level.rb in add at line 75
logger.rb in error at line 546

activesupport (6.1.7.10) lib/active_support/log_subscriber.rb in rescue in finish at line 118
activesupport (6.1.7.10) lib/active_support/log_subscriber.rb in finish at line 114
activesupport (6.1.7.10) lib/active_support/notifications/fanout.rb in finish at line 157
activesupport (6.1.7.10) lib/active_support/notifications/fanout.rb in block in finish at line 63
activesupport (6.1.7.10) lib/active_support/notifications/fanout.rb in each at line 63
activesupport (6.1.7.10) lib/active_support/notifications/fanout.rb in finish at line 63
activesupport (6.1.7.10) lib/active_support/notifications/instrumenter.rb in finish_with_state at line 45
activesupport (6.1.7.10) lib/active_support/notifications/instrumenter.rb in instrument at line 30
activesupport (6.1.7.10) lib/active_support/notifications.rb in instrument at line 203
actionpack (6.1.7.10) lib/action_controller/metal/instrumentation.rb in process_action at line 33
actionpack (6.1.7.10) lib/action_controller/metal/params_wrapper.rb in process_action at line 249
activerecord (6.1.7.10) lib/active_record/railties/controller_runtime.rb in process_action at line 27
```

## Steps to Reproduce

Send a nil log to this method.

## Your Environment

- kubernetes, rails with rack app

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by hannahramadan** [comment]
Hi @arlando - thank you for letting us know about this issue! We're now guarding against attempting to decorate messages that are `nil` with https://github.com/newrelic/newrelic-ruby-agent/pull/2986, which will go out in our next release.

**Comment by arlando** [comment]
> Hi @arlando - thank you for letting us know about this issue! We're now guarding against attempting to decorate messages that are `nil` with #2986, which will go out in our next release.

Thank you @hannahramadan.
