### ISSUE TITLE
Use monotonically increasing time

### ISSUE THREAD

**Issue by sdemjanenko** [newrelic/newrelic-ruby-agent#304]
There are a lot of calls to `Time.now` which is known to be affected by changes to system time (e.g. NTP updates). It is better to use `Process.clock_gettime(Process::CLOCK_MONOTONIC)`. For more information see: https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/

**Comment by rachelleahklein** [comment]
Hi, @sdemjanenko - thank you for your suggestion! We have brought this up with our Product Manager, who will determine whether it will be added to our roadmap, and if so, what its priority will be.

**Comment by viraptor** [comment]
Additional benefits for this change - `Process.clock_gettime(Process::CLOCK_MONOTONIC)` returns a float which can be used directly by most of the duration-calculating code. This means the agent can stop constructing `Time.now` all over the place. In my case that's ~1000 new Time objects on each request just from the tracing which uses `Time.now.to_f` to calculate duration.

**Comment by mwlang** [comment]
@viraptor thanks for the additional use-case where switching can be highly beneficial.  We definitely want to do this, but felt it was best to deprecate support for Ruby 2.0 (which is happening with our upcoming 7.0 release) before tackling this issue.

**Comment by mwlang** [comment]
With Ruby 2.0 and 2.1 deprecated for 7.0.0 release, this issue should be prioritized for inclusion an upcoming release.

Using either `Process.clock_realtime` (good enough and fastest) or more pedantically correct `Process.clock_monotonic` would improve all our duration calculations by as much as 2.7 times over `Time.now`

```
Allocations -------------------------------------
            Time.now       1/1  alloc/ret        0/0  strings/ret
Process.clock_realtime
                           0/0  alloc/ret        0/0  strings/ret
Process.clock_monotonic
                           0/0  alloc/ret        0/0  strings/ret
Warming up --------------------------------------
            Time.now    28.525k i/100ms
Process.clock_realtime
                        41.243k i/100ms
Process.clock_monotonic
                        41.683k i/100ms
Calculating -------------------------------------
            Time.now    512.386k (± 3.8%) i/s -      2.567M
Process.clock_realtime
                          1.413M (± 4.3%) i/s -      7.053M
Process.clock_monotonic
                          1.340M (± 4.1%) i/s -      6.711M

Comparison:
Process.clock_realtime:  1412578.4 i/s
Process.clock_monotonic:  1340018.5 i/s - same-ish: difference falls within error
            Time.now:   512385.8 i/s - 2.76x slower
```

Benchmark code for above results:

```Ruby
```

**Comment by kaylareopelle** [comment]
While pairing with @amhuntsman on this today, we determined `Process.clock_gettime(Process::CLOCK_MONOTONIC)` is our preferred value to replace Time.now when used as a float. Its purpose as defined by POSIX seems more appropriate than CLOCK_REALTIME for calculating the durations commonly recorded by the agent.
