### ISSUE TITLE
NameError: uninitialized constant Rake::VERSION

### ISSUE THREAD

**Issue by CamilleDrapier** [newrelic/newrelic-ruby-agent#338]
Hi,

I have noticed that I'm getting these kind of errors when I startup a typical rails application with rake tasks:

```
ERROR : Error while detecting rake_instrumentation:
ERROR : NameError: uninitialized constant Rake::VERSION
```

The way to reproduce this is:

- Create a new rails application: `rails new blog`
- Add the newrelic_rpm gem to the gem file (and bundle): `gem "newrelic_rpm"` 
- Generate the newrelic configuration: `newrelic install --license_key="YOUR_KEY" "Blog"`
- Add a simple rake/task filter in the `common` section of the newrelic configuration file (`newrelic.yml`):
   ```
     rake:
       tasks: [".*"]
   ```
- Start the rails server: `rails server`

=> The error message should appear in `log/newrelic_agent.log`

I noticed that this problem disappears when adding the `rake` gem to the bundle, but I'm unsure if this is a good way to fix this ? (as rails has a dependency constraint on rake). Another way, of course, would be to configure the newrelic agent to `disable_rake` but I guess that is not the purpose here 😅 

I also noticed that this is happening because rails loads a very small part of the `Rake` lib in [`lib/rails/test_unit/runner.rb#L5`](https://github.com/rails/rails/blob/9734dfa1a1a2d5909652dcbb80947a92ce42c431/railties/lib/rails/test_unit/runner.rb#L5) during its initialization process which result in the [`Rake` module being defined](https://github.com/ruby/rake/blob/master/lib/rake/file_list.rb), thus the [first check passes](https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/rake.rb#L10), but not the `Rake::VERSION` 😅 

I believe this error could be averted by checking if the constant is defined before reading it in the [instrumentation/rake](https://github.com/newrelic/rpm/blob/f42f233c02c3ad85ed4a8b41ea9bf2a664103d26/lib/new_relic/agent/instrumentation/rake.rb#L60) (i.e: prepending `defined?(::Rake::VERSION) &&`), but here again, I'm unsure if this is the right solution as maybe rails shouldn't partially load one of it's dependency during its initialization process and make this kind of problems possible ? And maybe this instrumentation need to be loaded at this point ?... Another solution could be to try to `require` the whole `rake` dependency, but that sounds a bit strange/dangerous/unexpected...

Please let me know what you think of this problem or if I missed some important configuration/step 🙏 

Thanks in advance 🙇

**Comment by tannalynn** [comment]
Hi @CamilleDrapier! 
Thank you for reporting this issue. I appreciate you providing such great details and steps to reproduce the problem.
We're looking into it and we will keep you updated as we investigate.

**Comment by rachelleahklein** [comment]
Hi @CamilleDrapier! Thanks again for your thorough treatment of this issue. As you can see, I've created a PR with a proposed fix. We're still in the middle of a CI migration so it may be a bit before we can merge it in good conscience, but wanted to let you know.

**Comment by CamilleDrapier** [comment]
Great, thanks a lot for working on this @rachelleahklein !
I was a bit worried that this might cause the whole rake instrumentation to not be loaded and resulting in measurements not being sent properly to NewRelic, that is not the case ?

**Comment by rachelleahklein** [comment]
@CamilleDrapier, the PR has yet to be fully vetted, but from my initial testing it doesn't look like this change interferes at all with rake instrumentation.

**Comment by mwlang** [comment]
This fix was merged to the `dev` branch and will appear in the next release!
