### ISSUE TITLE
developer_mode for rack removed?

### ISSUE THREAD

**Issue by anero** [newrelic/newrelic-ruby-agent#346]
I was trying to setup the `developer_mode` for verifying that the agent is running for a `grape` application. The documentation still mentions this feature (https://docs.newrelic.com/docs/agents/ruby-agent/features/developer-mode) and Puma has instructions on how to set it up for non-rails apps (https://github.com/puma/rpm#label-Developer+Mode+in+Rack+Applications). Now this seems to had been removed on https://github.com/newrelic/rpm/commit/6fcfeab1c1d953fddbc0d932aeba6cbd44bec7b6, and I couldn't find any instructions on how to set this up elsewhere. So a few questions:

- Is the developer mode feature still a thing?
- If so, do rack apps other than rails require any special setup for enabling developer mode, other than adding on `newrelic.yml` `developer_mode: true`?

**Comment by mwlang** [comment]
Yes, developer mode was removed for the 4.1.0.333 release.  The documentation was kept in the interim as many customers were still on prior versions of the agent, but is marked for deletion in the near future as part of larger effort to clean up and improve documentation.

For further info on this, see [Explorer's Hub thread](https://discuss.newrelic.com/t/feedback-on-the-ruby-agent-s-developer-mode/46957).

**Comment by mwlang** [comment]
Putting this one on hold rather than closing.  If others are interested in this feature, please indicate your interest in resurrecting this feature.  If interest is strong enough, then this may become a candidate for extraction to a separate gem.

**Comment by anero** [comment]
Thanks @mwlang, I'm not particularly interested in the feature, was trying to use to troubleshoot some issues that have been now resolved. I'd appreciate the documentation was updated explaining which in version this feature was deprecated.

**Comment by rachelleahklein** [comment]
Thanks for bringing this to our attention; we can definitely clarify the documentation.

Additionally, if anyone is interested in extracting this functionality into a separate gem, we are happy to provide guidance.

**Comment by rachelleahklein** [comment]
Hi @anero, I have made sure we are clearly listing the version of the agent that dropped support for developer mode in [our documentation](https://docs.newrelic.com/docs/agents/ruby-agent/features/developer-mode), and we've also added a "Deprecated" watermark in the hope that this will provide extra clarity for others who are troubleshooting.

Closing this ticket for now, if anyone's interested in extracting developer mode, please go ahead and comment and we'll reopen it.
