### ISSUE TITLE
net instrumentation can cause "stack level too deep" with 3rd party gems

### ISSUE THREAD

**Issue by MathieuDerelle** [newrelic/newrelic-ruby-agent#347]
please consider replacing monkey-patching `Net::HTTP` using class reopening and "alias_method_chain" by `prepend`

[more details in the issue I submitted to airbrake](https://github.com/airbrake/airbrake/issues/1104)

**Comment by mwlang** [comment]
@MathieuDerelle Thank you for this report and linking to airbrake issue as well.  This is a great example highlighting the need to move away from method chaining to a prepend approach to instrumenting.  I am placing this issue in our "review bucket" as a reminder to prioritize refactoring all instrumentation hooks that are not already using the prepend approach.

**Comment by gsar** [comment]
also affected by this issue. sadly, the suggested workaround of moving the `newrelic_rpm` line in the `Gemfile` ahead of `airbrake` doesn't seem to fix it here.

**Comment by MathieuDerelle** [comment]
@gsar the order in the `Gemfile` does NOT matter
it is the order of the `require`s that matters

take a look at your `config/application.rb` and look for a `Bundler.require(*Rails.groups)` or `require 'airbrake'` and put a `Bundler.require(:newrelic)` before it

**Comment by gsar** [comment]
@MathieuDerelle thanks for the tip. i tried your suggestion but it doesn't seem to make a difference, i still see the `stack level too deep` error with the stack showing airbrake and newrelic httpclient interceptors.

the issue occurs within a rake task but the main app itself appears to be fine. My `Rakefile` contains just this:

``` ruby
require File.expand_path('config/application', __dir__)

Rails.application.load_tasks
Rails.application.config.autoflush_log = true
Doorkeeper::Rake.load_tasks
```

**Comment by angelatan2** [comment]
This issue is included in the bug smash that we are working on.
