### ISSUE TITLE
undefined method to_i for array from gem in production

### ISSUE THREAD

**Issue by bharathram-nirman** [newrelic/newrelic-ruby-agent#348]
We are using Ruby-2.5 & Rails-5.2 newrelic_rpm gem - 6.10.0.364

Error we are receving: -

[NewRelic][2020-06-11 07:08:45 +0000 web.2 (18)] ERROR : Exception during Transaction#finish
[NewRelic][2020-06-11 07:08:45 +0000 web.2 (18)] ERROR : NoMethodError: undefined method `to_i’ for [“15000”]:Array

Description: -

The NewRelic gem is writing frequent errors to the log files, which makes it difficult to determine if there is a real issue and prevents us from having better alerting on errors in the logs. Can someone help us to fix

![NewRelic Error](https://user-images.githubusercontent.com/65995273/85368582-1d7a0f00-b549-11ea-8d44-fd02a8fc4562.jpg)

**Comment by mwlang** [comment]
@bharathram-nirman Could you please try the following patch by adding it to your Rails initializers folder or somewhere in your code after `newrelic_rpm` is required?

```ruby
module NewRelic::Agent::Instrumentation::MiddlewareTracing

  def capture_response_content_length(state, result)
    if result.is_a?(Array) && state.current_transaction
      _, headers, _ = result
      length = headers[CONTENT_LENGTH]
      length = length.reduce(0){|sum, h| sum + h.to_i} if length.is_a?(Array)
      state.current_transaction.response_content_length = length
    end
  end

end
```

This is a best guess effort based on the limited logged data shared above.  My guess is that a multi-part response with multiple length values is coming through and we're not handling this correctly.  

If this patch does not work, please set debug level for logging and capture a backtrace that can pinpoint exactly where the `#to_i` is invoked.  If you need further help on this, our Support team is an excellent avenue to getting assistance with this issue.

**Comment by mwlang** [comment]
@bharathram-nirman If this patch solves your issue, update this ticket and I will ensure the patch goes into the next release of the agent.

**Comment by bharathram-nirman** [comment]
@mwlang Thanks it solves my problem.

**Comment by mwlang** [comment]
This patch has been added and will appear in the next release of the agent.
