### ISSUE TITLE
Telemetry SDK: Traces

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#352]
Our [Telemetry SDKs](https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/new-relic-sdks/telemetry-sdks-send-custom-telemetry-data-new-relic) are an open source set of API client libraries that send metrics and trace data to the New Relic platform. This implementation will support the [Trace API](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/introduction-trace-api)

Aha! Link: https://newrelic.aha.io/features/RUBY-72

**Comment by angelatan2** [comment]
Telemetry SDK supporting Trace version 0.1 was released on Oct 30th.
https://github.com/newrelic/newrelic-telemetry-sdk-ruby/releases.
