### ISSUE TITLE
Telemetry SDK: Metrics

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#353]
Our [Telemetry SDKs](https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/new-relic-sdks/telemetry-sdks-send-custom-telemetry-data-new-relic) are an open source set of API client libraries that send metrics and trace data to the New Relic platform. This implementation will support the [Metric API](https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/introduction-metric-api)

**Comment by angelatan2** [comment]
Not in the Roadmap for FY22Q1 or Q2.
