### ISSUE TITLE
disable all Rubies except 2.6 in travis.yml 

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#365]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
Ruby's Travis CI configuration is not being used actively and the large number of matrix combos is causing other agent teams to queue up behind Ruby's build jobs.

## Expected Behavior
Disable all the Rubies except 2.6 so far fewer matrix jobs are spawned.

**Comment by tannalynn** [comment]
Pull request merged for this https://github.com/newrelic/newrelic-ruby-agent/pull/368
