### ISSUE TITLE
How to get the error rate of an specify external service?

### ISSUE THREAD

**Issue by justqyx** [newrelic/newrelic-ruby-agent#379]
Hi, I want to create an alert that to send an notification to me when an external http 5xx error rate above 0.05%. It's different to  the transaction error rate because the program often would handle the HTTP exception.

Is there anyway to reach?

**Comment by tannalynn** [comment]
Hi @justqyx , the next best step is to visit New Relic Support, where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. Please provide a link to this github issue when submitting your community post or support ticket.

**Comment by justqyx** [comment]
@tannalynn  Thanks
