### ISSUE TITLE
Update excon instrumentation

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#390]
The Ruby agent is known to support up to version 0.60.x of the excon gem. We would love your help in making sure our instrumentation works with the latest version.

For guidance on how to proceed, see our [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation), and please let us know if you have any questions not covered there.

**Comment by tannalynn** [comment]
We addressed this as part of our [prepend instrumentation](https://github.com/newrelic/newrelic-ruby-agent/pull/565) work
