### ISSUE TITLE
Update mongo instrumentation

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#393]
The Ruby agent is known to support up to version 2.12.x of the mongo gem. We would love your help in making sure our instrumentation works with the latest version.

For guidance on how to proceed, see our [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation), and please let us know if you have any questions not covered there.

**Comment by creaturenex** [comment]
I will also tackle this one as it is similar to issue #401

**Comment by hannahramadan** [comment]
Closing this ticket. Latest gem versions are being tested with PR: [Test unpinned gem version of core technologies](https://github.com/newrelic/newrelic-ruby-agent/pull/1204)
