### ISSUE TITLE
Update rack instrumentation

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#396]
The Ruby agent is known to support up to version 2.0.x of the rack gem. We would love your help in making sure our instrumentation works with the latest version.

For guidance on how to proceed, see our [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation), and please let us know if you have any questions not covered there.

**Comment by hannahramadan** [comment]
Closing—latest gem versions are being tested with [this PR]( https://github.com/newrelic/newrelic-ruby-agent/pull/1204)
