### ISSUE TITLE
Update sidekiq support

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#399]
The Ruby agent is known to support up to version 5.0.x of the sidekiq gem. We would love your help in making sure our instrumentation works with the latest version.

For guidance on how to proceed, see our [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation), and please let us know if you have any questions not covered there.

**Comment by angelatan2** [comment]
The ruby agent has been verified to run with both 6.0 and 6.1 versions of sidekiq gem in v6.15
