### ISSUE TITLE
Research: OTel Approach for Ruby

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#405]
To kick off our journey to supporting OpenTelemetry in the Ruby space we should better understand the current state of OpenTelemetry and what needs to be done for it to GA. We should perform a gap analysis of the state of the Ruby OTel SDK, API, and auto-instrumentation and the established guidelines for GA. From there we should identify if it seems reasonable that Ruby can GA in November and what we can contribute to.

Aha! Link: https://newrelic.aha.io/features/RUBY-134

**Comment by mwlang** [comment]
@elucus As discussed last Friday, I believe we accomplished the objectives of this milestone and should close.
