### ISSUE TITLE
Gem seems to ignore a file in config/initiatializers/new_framework_defaults.rb

### ISSUE THREAD

**Issue by davelens** [newrelic/newrelic-ruby-agent#414]
## Description
I've installed the gem as per the documentation, but for some reason our app in production started throwing presence validation errors on a `belongs_to` relation in one of our models.

Our app was upgraded from Rails 4 to 5.2, so it has the config/initializers/new_framework_defaults.rb file. This **only** contains the following to circumvent the described problem.
```ruby
Rails.application.config.active_record.belongs_to_required_by_default = false
```
Yet after the gem was running in production, we started receiving the described presence errors. Removing the gem fixed it.

Not sure what I'm doing wrong here. All I did was install the gem and copy the default `config/new_relic.yml` as explained by the New Relic website.

## Expected Behavior
To have this gem / New Relic not override application configuration without explicitly giving permission.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
---

## Steps to Reproduce
Can't share the original repo but: 
1. Given a model "Product" and "Discount":
```ruby
class Product < ApplicationRecord
  belongs_to :discount
end

class Discount < ApplicationRecord
end
```
2. Given `config/initializers/new_framework_defaults.rb`, containing:
```ruby
Rails.application.config.active_record.belongs_to_required_by_default = false
```
3. Install `newrelic_rpm` and copy the default `config/new_relic.yml` from the New Relic website.
4. Calling `#update_attributes` on Project would trigger the belongs_to validation on `Project#discount`.

## Your Environment
1. Bog standard Rails 5.2 app running in the `production` environment.
2. Ruby 2.4.4p296
3. newrelic_rpm 6.12.0.367

## Additional context
---

**Comment by mwlang** [comment]
@davelens, this feels like a startup order/dependency issue.  From the description of the problem, it may very well be that the agent's action to auto-instrument may cause your model classes to eager load before reaching the `new_framework_defaults` initializer.  

Two suggestions for possible workarounds:

1. move that one line from the initializer file into your `~/config/environments/*.rb` files or alternatively into `~/config/application.rb` file.  This should allow the configuration setting to activate earlier in the startup chain.

2. For the one model where this is currently a problem, go ahead and make the prescribed Rails 5 change on that model's association:

```ruby
class Product < ApplicationRecord
  belongs_to :discount, optional: true
end
```

**Comment by davelens** [comment]
@mwlang Thank you for the quick response and guidance. I didn't think of the gem's load order and can confirm your suggestion to move the configuration to `config/application.rb` fixes the problem.

I'm unsure if this warrants any documentation (or if I missed it?), but I did want to bring this to attention. Our app is one in a million legacy apps that went through numerous upgrades and can benefit from what New Relic can uncover.

**Comment by mwlang** [comment]
@davelens Thank you for confirming what worked.  I was definitely speculating on gem load order, but in reality, could've been a number of things, including how the Agent interacts with ActiveRecord when setting things up or another gem monkey patching ActiveRecord as discussed in this [SO article](https://stackoverflow.com/questions/38850712/rails-5-belongs-to-required-by-default-doesnt-work): 

At any rate, thanks for getting the solution on the record here!
