### ISSUE TITLE
Infinite Tracing Polish

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#440]
As a user of Infinite Tracing, I expect to get my k8s metadata in the same way I would with the standard agent collector pipeline. Also, as a user of Infinite Tracing, I expect that I would not lose span data when New Relic redirects my traffic to a different cell.

Aha! Link: https://newrelic.aha.io/features/RUBY-137

**Comment by angelatan2** [comment]
Released in 6.15.
