### ISSUE TITLE
Expect / Ignore Errors by Status Code

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#455]
## Feature Description
Implements the ability configure the agent to ignore or expect by status codes similar to following:
```YAML
  error_collector:
    enabled: true
    ignore_status_codes: 404,507-511
    expected_status_codes: 406,500-504
```

### Ignore errors by status code

* Add `error_collector.ignore_status_codes` configuration option
* The option is a comma separated list of status codes, possibly including ranges. We will want to expand this into an array of integers.
* We should not generate errors for status codes in this list.
* Both Go and Java record exceptions for status codes >= `400` with an exception of `404`. We should probably do the same. So, the config option would default to `404`.

### Expect errors by status code

* Add error_collector.expected_status_codes configuration option
* The option is a comma separated list of status codes, possibly including ranges. We will want to expand this into an array of integers.
* We should mark exceptions as expected for statuses in this list.
* If an error is expected, increment the `ErrorsExpected/all` metric, but do not increment the `Errors/all`, `Errors/[transactionName]`, `Errors/allWeb`, or `Errors/allOther` metrics.
* If an error is specified in both the ignore and expected lists, the error should be ignored

### Priority
Should be implemented during one of the upcoming "bug smash" weeks.

**Comment by angelatan2** [comment]
Added to Expected/Ignore Errors Milestone. Waiting on Feature Enhancement Prioritization. @elucus.
Keeping the issue active.
