### ISSUE TITLE
Puma Restarts End in Framework Load Error

### ISSUE THREAD

**Issue by ggennrich** [newrelic/newrelic-ruby-agent#464]
## Description
When deploying a Rails application with Capistrano and Puma we will get the error `NameError: uninitialized constant NewRelic::Control::Frameworks::RailsNotifications`. A redeploy will fix it. Basically, we are forced to deploy the app twice to resolve the issue. We have several other applications on the same stack that do not have this problem.

## Expected Behavior
Puma should restart without any NewRelic errors

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
```=== puma startup: 2020-10-02 16:41:46 +0000 ===
NameError: uninitialized constant NewRelic::Control::Frameworks::RailsNotifications
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.13.1/lib/new_relic/control/class_methods.rb:52:in `const_get'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.13.1/lib/new_relic/control/class_methods.rb:52:in `load_framework_class'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.13.1/lib/new_relic/control/class_methods.rb:32:in `new_instance'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.13.1/lib/new_relic/control/class_methods.rb:13:in `instance'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.13.1/lib/newrelic_rpm.rb:41:in `block in <class:Railtie>'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /home/capuser/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `public_send'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `method_missing'
  /var/www/onlineu/current/config/environment.rb:5:in `<top (required)>'
  /var/www/onlineu/current/config.ru:3:in `require'
  /var/www/onlineu/current/config.ru:3:in `block in <main>'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /var/www/onlineu/shared/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
=== puma startup: 2020-10-02 16:44:38 +0000 ===
```

## Steps to Reproduce

- Deploy the application via Capistrano
- One of the Puma instances will fail to restart
- Redeploy the application
- Puma instances will start fine from a new daemonized process

## Your Environment

- newrelic_rpm (5.4.0.347) and newrelic_rpm (6.13.1) (bumping the version did not help resolve the problem)
- Ruby 2.5.1
- Rails 5.2.4.2

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

**Comment by rachelleahklein** [comment]
Hi, @ggennrich. Thanks for reaching out to us. I'm sorry to hear you're having this issue - we appreciate you letting us know so we can dig into it with you.

The error you’re seeing is happening very early on when the agent is installing. I’ve narrowed the problem down to [this line](https://github.com/newrelic/newrelic-ruby-agent/blob/c9203be16af3468f275bbde078dc2805ad878655/lib/new_relic/control/class_methods.rb#L47). On that first deploy, the agent is not able to properly require the file it needs to set up Rails instrumentation. My suspicion is that for some reason, the `$LOAD_PATH` is different between the first and second deploys.
 
Some questions for you:
* Has anything recently changed in your deploy scripts that may not be fully establishing the environment or is changing the `$LOAD_PATH` during deploys?
* Are you changing paths or symlinking where gem libraries are involved in one of your deploy steps?
* Finally, are you using phased puma restarts?

**Comment by ggennrich** [comment]
Hi, @rachelleahklein. Thanks for the reply! Here are the answers:

- No. The same deploy script is used to deploy to 4 instances but only 2 of the instances are having this issue and only one app (we have several others that deploy fine on all 4 instances)
- Not that I can tell
- Yes

Appreciate the help!

**Comment by mwlang** [comment]
@ggennrich, thanks for answering those questions.  Your answers lead us to some more targeted line of questions:

* Has this been an ongoing issue for some time or did it start with a recent upgrade of the agent?
  * If it started recently with an agent upgrade, can you elaborate on what the prior version of the Agent was?
* Are you deploying with Capistrano?  If so, what version?
* Lastly, we asked about phased puma deploys, because there are a number of issues raised (and resolved) with phased Puma deploys, so some research there may help your case.
* Although I didn't see anything in Rails changes for your series that would point to a load issue, it may still be worthwhile upgrade to 5.2.4.4 as other gems Rails depends on were also updated along the way: https://github.com/rails/rails/compare/v5.2.4.2...v5.2.4.4

**Comment by angelatan2** [comment]
We are closing this issue since we did not receive a response.  If this situation continues to be an issue, please open a new ticket.
