### ISSUE TITLE
#newrelic_ignore implemented as a instance method

### ISSUE THREAD

**Issue by ts-3156** [newrelic/newrelic-ruby-agent#467]
### Is your feature request related to a problem? Please describe.

I want to disable NewRelic on requests from specific crawlers. My application returns `Status: Forbidden` early on for these crawlers. NewRelic records these requests as well, so the average response time is reduced excessively.

### Feature Description

If `newrelic_ignore` is implemented as an instance method, it can be used in this way:

```
class ApplicationController
  before_action(only: :new) { newrelic_ignore if specific_crawler? }
end
```

The conditions of the `specific_crawler?` are a bit complicated, so I cannot use a reverse proxy(Nginx) to reject a specific UserAgent.

### Additional context

- Rails application

### Priority
Nice to Have

**Comment by rachelleahklein** [comment]
Hi, @ts-3156! Thanks for reaching out to us about this!

We have some mechanisms existing in the agent already that can hopefully help you accomplish what you want here. In particular, see our documentation on [ignoring transactions dynamically](https://docs.newrelic.com/docs/agents/ruby-agent/api-guides/ignoring-specific-transactions#dynamic-ignoring). You could combine this with [Rails filters](https://guides.rubyonrails.org/action_controller_overview.html#filters) like so:

```
class ApplicationController
  before_action :disable_newrelic_tracer_for_crawlers, only: :new
  def disable_newrelic_tracer_for_crawlers
    NewRelic::Agent.ignore_transaction if specific_crawler?
  end
end
```

Alternatively, you could do something like this using [`disable_all_tracing`](https://www.rubydoc.info/github/newrelic/rpm/NewRelic%2FAgent:disable_all_tracing):
```
class ApplicationController
  around_action :disable_newrelic_tracer_for_crawlers, only: :new
  def disable_newrelic_tracer_for_crawlers
    if specific_crawler? 
      NewRelic::Agent.disable_all_tracing
      yield
    else
      yield
    end
  end
end

```

Does it seem like either of these solutions would suit your needs?

**Comment by ts-3156** [comment]
Thanks! I will try it.
