### ISSUE TITLE
Http Header Details

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#472]
<p>We are currently trying to build a solution for mobile distributed tracing and we need the ability to view then header details for the transactions reported within New Relic. Use case, a HTTP request from a mobile application, we are appending a New relic header trace.id to that request. We need to see if the agent is picking that header record up correctly.</p><p></p><p>Can we get the header details exposed in the ruby agent logs?</p>

**Comment by mwlang** [comment]
### Notes for implementation/estimate:
* Locate best point in the code to capture request headers and response headers
* Wrap in logger/audit functionality to record headers when logger level is appropriate level
* Test and verify
* Release patch
