### ISSUE TITLE
Remove SSL cert bundle

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#478]
As part of our open source efforts, we aim to stop shipping the SSL cert bundle in favor of using system certs. 

For affected customers (which we don't expect to be very many, aside from Alpine Linux users because Alpine does not come with certs by default), we need to have instructions for how to help them. On Alpine, for example, they could run something like this: 

`apk add ca-certificates`

**Comment by mwlang** [comment]
* [Troubleshooting SSL Certificate Errors](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors)
* [Automated SSL Check](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check)
