### ISSUE TITLE
Add makara to list of incompatible gems

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#507]
## Description

Issue with over-obfuscation related to use of makara was raised in [this support ticket (note: internal only)](https://newrelic.zendesk.com/agent/tickets/325320).

We originally thought we might be able to use [this solution (note: internal only)](https://newrelic.atlassian.net/browse/RUBY-2024) which worked for the octopus gem. However, it looks like makara actually modifies the adapter name on the underlying connection, so this issue will need its own fix.

We should discuss the following:
1. Is it feasible to add support for obfuscation for users of makara?
2. If yes, what priority should it be?
3. If no, should makara be added to the list of incompatible gems? 

Comment copied over: 
We are going with option 3, since there doesn’t seem to be much customer demand for support.

**Comment by emj-io** [comment]
Sad to hear this, it would be a blocker for us as we use Makara with distribute_reads.

**Comment by angelatan2** [comment]
Leave this open for another assessment and revisit the adoption of Makara and its usage.  Removing this from Major release 7.0

**Comment by kaylareopelle** [comment]
The PR to [update the docs website with makara's incompatibility](https://github.com/newrelic/docs-website/pull/3272) has been merged! 🎉 

No Ruby agent code changes needed.
