### ISSUE TITLE
Update gRPC dependency from 1.28.0 to 1.34.0

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#522]
### Is your feature request related to a problem? Please describe.
gRPC gem is 6 releases ahead of where we last tested and released.  This feature request updates gRPC and gRPC tools gems.

### Feature Description
To avoid falling behind the curve or debugging issues potentially related to stale gRPC, we should update to latest before implementing latest new feature enhancements.

**Comment by tannalynn** [comment]
Completed in PR https://github.com/newrelic/newrelic-ruby-agent/pull/523
