### ISSUE TITLE
Update Support Statement in Release Notes

### ISSUE THREAD

**Issue by azeazasloper** [newrelic/newrelic-ruby-agent#526]
Add the following to release notes:

> **Support statement:**
New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months. As of this release, the oldest supported version is [4.8.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-480341).

**Comment by tannalynn** [comment]
Release notes completed and included this at the bottom: https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-6150
