### ISSUE TITLE
Note: Delays During the Holidays

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#529]
Please note that there will be delays in responding to issues and pull requests in this repository during this holiday season. 
If you need assistance anytime, please see our [support section in the readme](https://github.com/newrelic/newrelic-ruby-agent#support) for details on how to access support through New Relic.
Happy Holidays!

**Comment by mwlang** [comment]
Welcome back and Happy New Year.  May 2021 prove a prosperous year for all.
