### ISSUE TITLE
Changelog Entries needed for 6.15.0

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#533]
This issue tracks those issues or externally submitted PRs that require a CHANGELOG entry.  Attach entries as appropriate, or review [this list of 6.15.0 tagged issues](https://github.com/newrelic/newrelic-ruby-agent/issues?q=label%3Aversion%3A6.15.0) for completeness.

**Comment by mwlang** [comment]
#498 needs a CHANGELOG entry

**Comment by tonydehnke** [comment]
Why does the Changelog show 6.15.0 but on RubyGems the latest version shown is 6.14.0?

**Comment by mwlang** [comment]
@tonydehnke 6.15.0 is the next version coming up.  This is an issue for us to add changelog notes before we ship 6.15.0.

**Comment by tonydehnke** [comment]
That's the thing though, the current changlog already shows 6.15.0 items,  should that not be in a branch that only shows up once it's merged? (Newbie learning here).

**Comment by mwlang** [comment]
@tonydehnke The `dev` branch contains all the pre-release changes and is basically "staging" for an upcoming release.  As we start implementing new features, we also start adding CHANGELOG entries for the next release, which is 6.15.0 in this case.  A lot of teams wait until the release is imminent to write up the CHANGELOG or use automated solutions that will version bump and add all CHANGELOG entries as last step before formal release, but we like the hands-on touch to our CHANGELOGs so we add as we go in most cases while the problem and solution are still fresh in our minds.

`dev` branch also happens to be our default branch so that might be super-confusing since it's a different default setup from many other repos on github.  However, `dev` as default works great for us because PRs (esp. from forked repos) are almost always targeting the right branch (`dev` in this case). 

When we release, everything in `dev` gets merged to the `main` branch and a final set of automated tests run to ensure everything works as expected.  If everything passes, then a new gem is released and published to rubygems.org.
