### ISSUE TITLE
Write up a How-To Guide for upgrading from 6.x to 7.0

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#541]
### Feature Description

As part of the upcoming 7.0 major release, we want to document the following:
* What's new in 7.0 and what to expect with auto-instrumentation changes.
* What was deprecated in 6.x and now removed in 7.0 and how to change customization code.
* ~How Method Tracers now work.~

**Comment by mwlang** [comment]
* [Troubleshooting SSL Certificate Errors](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors)
* [Automated SSL Check](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check)

**Comment by mwlang** [comment]
* [Installing CA Certificates](https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu/719047#719047)

**Comment by angelatan2** [comment]
Discussion 3/16:
A. Looking for migration guide ( SSL certs, API - prepend, or Config) with the following:
1. How does a customer quickly identify they need to make a change
2. Provide the alternative/replacement instructions.
3. Recommendation to customers:  Test your changes in staging first.

** Put migration this doc under getting started, create a new page with this information.
** Look for customer-facing documentation related to our changes in this release and add additional messaging.  When appropriate, direct the customers to the migration doc/URL.
•• Note: Method tracer moved to next major release.

Ticket with Docs team to review our changes
[Internal](https://newrelic.atlassian.net/browse/DOC-6646)

B. Nerd life post, Explorer Hub, post.  These will point back to the migration guide.
C. Let's try and get the migration guide draft ready for review 3/18.

**Comment by angelatan2** [comment]
Please update new configurations here:
- [ ] https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/

**Comment by tannalynn** [comment]
https://github.com/newrelic/docs-website/pull/1985
https://github.com/newrelic/docs-website/pull/1983
