### ISSUE TITLE
Remove IdeaFlow tool from Release CI

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#542]
## Description
In the recent past,  IdeaFlow Tool has only provided limited verification value since it is not used much within New Relic. Let's remove the IdeaFlow Tool and prepare for our CI to be able to include Crossroad. Please see the link for the ticket

[Internal Only](https://newrelic.atlassian.net/browse/IHE-300)

## Expected Behavior
Improve our CI with deployment test of Ruby Gem in Crossroad.

**Comment by tannalynn** [comment]
Jira tickets related to getting this set up for discourse plugin as well:
[internal only](https://newrelic.atlassian.net/browse/IHE-311)
[internal only](https://newrelic.atlassian.net/browse/IHE-333)
