### ISSUE TITLE
Enable distributed tracing by default

### ISSUE THREAD

**Issue by azeazasloper** [newrelic/newrelic-ruby-agent#550]
Currently, the `distributed_tracing.enabled` configuration flag defaults to `false`. In the next major version bump of the agent, we will change the default value to `true`.

We also need to update our [public docs](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#distributed_tracing-enabled) to reflect the new default value.

**Comment by angelatan2** [comment]
- [ ] Agent Spec draft and update 
- [ ] Update configuration to enable DT by default
- [ ] Update all public facing documentation that calls out CAT as Default.
- [ ] Deprecate CAT
