### ISSUE TITLE
Deprecate CAT

### ISSUE THREAD

**Issue by azeazasloper** [newrelic/newrelic-ruby-agent#551]
Change the default for `cross_application_tracer.enabled` configuration flag to `false` and add deprecation warnings.

The [public docs](https://docs.newrelic.com/docs/agents/ruby-agent/features/cross-application-tracing-ruby) will also need to be updated.

We will completely remove support for this feature in a future major version release.

**Comment by kaylareopelle** [comment]
The work to deprecate CAT in the ruby-agent's code has been merged into `dev`. The remaining work involves updating the docs-website repo with deprecation messages where CAT is referenced. There are a handful of areas where CAT is mentioned  that I would like to test with DT to make sure it is an applicable replacement.

**Comment by kaylareopelle** [comment]
Docs WIP Branch: https://github.com/kaylareopelle/docs-website/tree/ruby-agent/deprecate-cat 

Steps before close: 
* Can parallel requests using the `Hydra` mechanism in Typhoeus receive entire tracing support through DT? 
* Can requests made via the `Curl::Multi` Api have full tracing support with distributed tracing? 
* Is `NewRelic::Agent::Hooks` still a viable middleware for inclusion in Rack-based applications? (If not, which version of the gem did it lose support?)
* Can DT be used on pure Rack applications?

**Comment by kaylareopelle** [comment]
Testing complete (notes above). Documentation PR ready for ruby-agent team review: https://github.com/newrelic/docs-website/pull/3583
