### ISSUE TITLE
AWS metadata request not compatible with v2

### ISSUE THREAD

**Issue by lefthand** [newrelic/newrelic-ruby-agent#552]
The metadata requests fail on AWS if instance metadata v1 is disabled on the host.

## Description
When my app boots up the New Relic gem fires off requests to all known cloud provider metadata endpoints. The request to AWS uses the deprecated v1 request method. It is a best practice to not only use the v2 service but to disable access to v1 on hosts.

See:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/utilization/aws.rb

## Expected Behavior
I expect New Relic to use the v2 metadata service.

## Steps to Reproduce
Disable instance metadata v1 on your host and then start an app using any version of the New Relic gem.

## Your Environment
My hosts are in AWS and have instance metadata v1 disabled

## Additional context
For now I'm disabling requests to the metadata service completely to avoid the errors.

**Comment by mwlang** [comment]
@lefthand Thank you for reporting this.  You're right, we need to bring the Agent code up to date with at least v2 API for AWS.

This is more than a simple fix.  It looks like we also need to refactor a bit to retrieve a valid token for issuing API calls on v2 endpoints. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html
![image](https://user-images.githubusercontent.com/18387/106531270-eba43000-64bb-11eb-805a-c3b549793613.png)

I'm also looking for documentation on when v1 endpoints are EOL'd.  If anyone knows, please attach a link to this issue to help us prioritize.

**Comment by lefthand** [comment]
Thanks for looking into this. I haven't seen any info on a possible EOL for v1, I'm sure it will be quite a while before it gets retired.

**Comment by woodhull** [comment]
For us, this is a security concern. We'd like to disable IMDSv1 on our instances as defense-in-depth against SSRF / data exfiltration from the AWS metadata service. Disabling v1 is the recommended AWS best practice for security.

**Comment by tannalynn** [comment]
@woodhull Thank you for letting us know about your interest in this feature request. It's not scheduled to be part of our next release (8.0.0), but after that, we will talk with project management to see when this work should be prioritized for.

**Comment by elucus** [comment]
This is not on our short-term roadmap but we will evaluate this for one of our quarterly feature packs.

**Comment by soupmatt** [comment]
I'd like to upvote this for the same security reasons. It is a blocker for my employer as well.

**Comment by kaylareopelle** [comment]
Thanks to all for their continued persistence on this issue. We are internally QA'ing a few solutions to enable IMDSv2 on the Ruby Agent and will have a test branch ready soon. If anyone is available/interested in testing the solution, it would be a huge help to our team. We'll post the branch here when we're ready.

**Comment by kaylareopelle** [comment]
Hello! I wanted to let y'all know the feature can be tested by pointing your `newrelic_rpm` installation to the `include_a_token_with_aws_imds_requests` branch. 

```ruby
gem 'newrelic_rpm', git: 'https://github.com/newrelic/newrelic-ruby-agent.git', branch: 'include_a_token_with_aws_imds_requests'
```

**Comment by fallwith** [comment]
Hey all. This change has also now gone out in version 8.5.0 of the agent gem now available from RubyGems.org
