### ISSUE TITLE
Ruby Agent v8 

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#555]
Refactor Method Tracers and other APIs that are not Ruby 3.0 ready

- [<ins>#502 Custom Method Tracers for Ruby 3.0 and beyond</ins>](https://github.com/newrelic/newrelic-ruby-agent/issues/502)
- Datastores.trace API

Aha! Link: https://newrelic.aha.io/features/RUBY-146

**Comment by kaylareopelle** [comment]
Reminder: PR for deprecate-cat docs updates: kaylareopelle/docs-website#1
