### ISSUE TITLE
Sidekiq error: NameError: undefined local variable or method `headers' for NewRelic::Agent::DistributedTracing:Module

### ISSUE THREAD

**Issue by leonid-shevtsov** [newrelic/newrelic-ruby-agent#556]
## Description

The following exception is logged repeatedly from our Sidekiq workers. This does not break metric reporting, and the exception is catched somewhere in the New Relic code.

## Expected Behavior

No exception in logs.

## Troubleshooting

 We have not configured Distributed tracing, beyond enabling it in the config file:

```
common: &default_settings
  distributed_tracing:
    enabled: true
```

The log message reads

```
ERROR : error during accept_distributed_trace_headers
ERROR : NameError: undefined local variable or method `headers' for NewRelic::Agent::DistributedTracing:Module
```

## Steps to Reproduce

Enable distributed tracing, then run a Sidekiq job.

## Your Environment

```
newrelic_rpm (6.15.0)
sidekiq (6.0.6)
```

**Comment by mwlang** [comment]
@leonid-shevtsov Thanks for reporting this issue.  There's a typo in the method that checks that the parameters passed to the `accept_distributed_trace_headers` API call are of the expected type.   In this case, the first method parameter, `headers`  is expected to be a `Hash` object.  The validation check had a typo leftover from refactoring effort and is resolved by PR #558 and will appear in the next release of the agent.
