### ISSUE TITLE
Elastic Search requests disappear from "external services" after upgrading

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#557]
## Description
From [@brian38 on Explorer's Hub](https://discuss.newrelic.com/t/ruby-why-have-elasticsearch-requests-disappeared-from-external-services/127884)

In our rails app, requests to our elasticsearch cluster have historically accounted for a high percentage of our outgoing HTTP traffic. Until recently, requests to it would appear near the top of the list at “External Services.”

Now, it’s not found there at all. I can kind of find my way to that “external service” item by going to “Transactions”, selecting a slow transaction, seeing the request to Elasticsearch at the top of that (it usually accounts for a high percentage of those transactions), and clicking that link. At that point I’m sent to “External Services”, and I’m looking at graphs of response time and throughput for requests to the Elasticsearch cluster. I can see at the top of those charts the throughput (CPM), which should place it easily at #1 on the list—but it doesn’t appear in the list at all.

We upgraded gem newrelic_rpm from 3.18.1.330 to 6.14.0… which I realize is an enormous gap. Unfortunately, that’s long enough ago that I can’t compare data in Newrelic before and after.

Most of our app makes requests using Typhoeus directly. In the case of requests to elasticsearch, we use the chewy gem, which uses the elasticsearch gem, which uses the elasticsearch-transport gem, which uses the faraday gem. Faraday is essentially just an interface around whatever actual http library it detects is present (or is configured to use), and since we haven’t configured it otherwise, it ends up using Typhoeus. (I’ve double-checked some backtraces during those requests to confirm that’s the case.)

We’re on Typhoeus 1.4.0, but as recently as 2 weeks ago, we were using Typhoeus 0.8.0—although I had noticed that these elasticsearch requests were absent in Newrelic even before that, so I think we can rule that out as a cause.

**Comment by gsar** [comment]
@mwlang seeing this issue as well. currently on newrelic_rpm 6.15.0 and rails 6.1.1, but was also happening prior to those versions.

**Comment by angelatan2** [comment]
We plan on adding instrumentation to Elastic Search, we will revisit this ticket during the implementation of that feature.

**Comment by tannalynn** [comment]
This issue has been resolved. We've released 8.12.0 which introduces brand new elasticsearch instrumentation which will record data related to elasticsearch requests independent of the instrumentation of the underlying http library being used.
