### ISSUE TITLE
Agent breaks Net::HTTP IPv6 requests

### ISSUE THREAD

**Issue by natpicone** [newrelic/newrelic-ruby-agent#562]
Making Net::HTTP request to an IPv6 addresses will raise `URI::InvalidURIError` 
It looks like the issue is here
https://github.com/newrelic/newrelic-ruby-agent/blob/55cc3e55b1a6fc60fec6a576d197895facf886bb/lib/new_relic/agent/http_clients/net_http_wrappers.rb#L66
because it doesn't recognize IPv6 addresses which require to be enclosed by `[]` (see rfc3986)

## Steps to Reproduce
```
require 'newrelic_rpm'
Net::HTTP.new('::1').request(Net::HTTP::Get.new('/'))
```

Output
```
Traceback (most recent call last):
	6: from newrelic_test.rb:2:in `<main>'
	5: from /xxxx/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:16:in `request'
	4: from /xxxx/.rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/http_clients/net_http_wrappers.rb:65:in `uri'
	3: from /xxxx/.rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/http_clients/uri_util.rb:38:in `parse_and_normalize_url'
	2: from /xxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
	1: from /xxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
/xxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "http://::1:80/" (URI::InvalidURIError)
```

## Your Environment
`ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]`
`newrelic_rpm (6.14.0)`

**Comment by mwlang** [comment]
@natpicone Thank you for reporting this!  Definitely is a bug we need to fix.

**Comment by tristinbarnett** [comment]
@natpicone Thank you so much for your contribution, this bug has been fixed and the update will be included in a future release.
