### ISSUE TITLE
Deprecate Support for Ruby 2.0 and 2.1

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#570]
Ruby 2.0 and 2.1 are EOL'd for over four years and is not a prerequisite for Rails .  We should remove it from our test matrix.

## Ruby 2.1 EOL Announcement

> Support of Ruby 2.1 has ended
> Posted by usa on 1 Apr 2017
> 
> [We announce](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/#:~:text=Therefore%2C%20at%20March%2031%2C%202017,of%202.1%20will%20be%20released.) that all support of the Ruby 2.1 series has ended.
> 
> After the release of Ruby 2.1.10 at the end of March of the last year, the support of the Ruby 2.1 series was in the security maintenance phase. Now, after one year has passed, this phase has ended. Therefore, at March 31, 2017, all support of the Ruby 2.1 series has ended. Bug and security fixes from more recent Ruby versions will no longer be backported to 2.1, and no further patch release of 2.1 will be released. We highly recommend that you upgrade to Ruby 2.4 or 2.3 as soon as possible.
> 

## Ruby 2.0 EOL Announcement

> Support plans for Ruby 2.0.0 and Ruby 2.1
> Posted by usa on 24 Feb 2016
> 
> [We announce](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/) the future support plans for Ruby 2.0.0 and Ruby 2.1.
> 
> About Ruby 2.0.0
> As it has been announced before, all support for Ruby 2.0.0 has ended today. Bug and security fixes from more recent Ruby versions will no longer be backported to 2.0.0, and no further patch release of 2.0.0 will be released.
> 
> We highly recommend that you upgrade to Ruby 2.3 or 2.2 as soon as possible.
> 
> Please contact us via the ruby-core ML if you’d like to continue maintaining the 2.0.0 branch as for some justifiable reason you can’t upgrade.
> 
> 

### Feature Description
Remove Ruby 2.0 and 2.1 from test matrix.  Any code currently successfully running for Ruby 2.0 and 2.1 is not removed.  However, starting with 7.0 Release of the agent, Ruby 2.0 and 2.1 will no longer be covered under the test matrix.

**Comment by angelatan2** [comment]
Per Michael Lang - 2.0 and 2.1 were removed from the test matrix.
Documentation was released as well.
