### ISSUE TITLE
google-protobuf 3.15.0 breaks Infinite Tracing implementation.

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#576]
## Description
The latest `google-protobuf 3.15.0` released yesterday (Feb 18) breaks our implementation of Infinite Tracing.

```
TypeError: wrong argument type nil (expected Google::Protobuf::Descriptor)
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/infinite_tracing/streaming_buffer_test.rb:117:in `[]'
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/infinite_tracing/streaming_buffer_test.rb:117:in `block in test_drops_queue_when_max_reached'
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/test_helper.rb:59:in `block (2 levels) in with_serial_lock'
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/test_helper.rb:59:in `synchronize'
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/test_helper.rb:59:in `block in with_serial_lock'
    /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/infinite_tracing/test/test_helper.rb:41:in `block in timeout_cap'
```

## Steps to Reproduce
Run `bundle exec rake test:multiverse[infinite_tracing]` or switch to infinite_tracing folder and run `bundle exec rake test`

## Your Environment
* Infinite Tracing
* Google Protobuf 3.15.0. gem

**Comment by tannalynn** [comment]
We're running google-protobuf 3.15.6 on our tests now, and everything passes now. Looks like they had multiple bugs filed related to 3.15 that appear to be fixed now. Should we just close this issue? Or should we add something to the gemspec that requires NOT those versions of google-protobuf be used?

**Comment by mwlang** [comment]
Closing this bug with no action taken.  Users of google protobuf v3.15.0 need only to upgrade to latest 3.15.x to resolve.
