### ISSUE TITLE
Update usage of MD5 in the agent to a FIPS compliant alternative

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#602]
Problem:
"The NewRelic ruby agent utilizes MD5 digests in a few places and is causing our app to crash when the OS is in FIPS mode. md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!"

The agent uses MD5 in a couple of places:
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/sql_sampler.rb#L362
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/sql_sampler.rb#L365
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/monitors/cross_app_monitor.rb#L105

MD5 is not FIPS compliant, causing applications on FIPS servers to crash upon encountering this error. 

`md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`

Other agent teams, such as the Node agent, have updated this to use SHA1. 

[Internal JIRA](https://newrelic.atlassian.net/browse/GTSE-7735)

**Comment by angelatan2** [comment]
Migrating suggestion from another source:

Thanks for the update! In the meantime, we've patched the NewRelic agent methods to use Digest::SHA256, we haven't seen any issues so far but wanted to check if there was anything we should be looking out for.”

```
if defined?(NewRelic)
  require 'digest'

  class NewRelic::Agent::DistributedTracing::CrossAppMonitor
    private

    def hash_transaction_name(identifier)
      Digest::SHA256.digest(identifier).unpack1('@12N') & 0xffffffff
    end
  end

  class NewRelic::Agent::SqlTrace
    private

    def consistent_hash(string)
      if NewRelic::Agent.config[:'slow_sql.use_longer_sql_id']
        Digest::SHA256.hexdigest(string).hex.modulo(2**63 - 1)
      else
        # from when sql_id needed to fit in an INT(11)
        Digest::SHA256.hexdigest(string).hex.modulo(2**31 - 1)
      end
    end
  end
end 
```
