### ISSUE TITLE
CI Error: A pre-dependency on multi-arch support is not met for mysqlclient lib install

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#607]
Some of the CI jobs have started failing with installing the MySQL client.  A pre-dependency on multi-arch support is not met.

![image](https://user-images.githubusercontent.com/18387/109727183-e05b2780-7b81-11eb-9d25-903995f378bf.png)

**Comment by angelatan2** [comment]
This issue is related to Ubuntu 20.04.  Plan on addressing when we upgrade.

**Comment by angelatan2** [comment]
Solved for Ruby versions < 3.2.
