### ISSUE TITLE
mimemagic's licensing conflicts with GPLv2 and recent actions causing CI to fail

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#631]
Currently, our CI is failing for Rails on Ruby 2.2 because of mimemagic's recent changes to deal with violating GPLv2 License terms (mimemagic was released under MIT, but utilized sources that were previously distributed under GPLv2).  Mimemagic's recent actions was to yank all tainted versions, which Rails depended on and re-release a new MIT version from which Rails can continue to use.  That action requires further action to actually work since the GPLv2 files are no longer distributed.

Although mimemagic just released 3.7 under MIT, it cannot be used with Ruby 2.2 because it depends on a version of Nokogiri that depends on Ruby >= 2.3.  (they've acknowledged and may offer a fix later).  At the moment, no fix available.

Also, even with fixes in place, the MIT release still indirectly depends on the GPLv2 sources and is not a long-term fix.  The. Rails team has said as much and is working on alternatives to depending on mimemagic going forward.  No fixes yet released at the time of filing this issue.

* [New mimemagic version licensed under MIT #41757](https://github.com/rails/rails/issues/41757)

![image](https://user-images.githubusercontent.com/18387/112504404-1e530200-8d62-11eb-8c91-d7d4dac56370.png)

**Comment by mwlang** [comment]
[Yanked 0.3.x breaks Rails install #98](https://github.com/mimemagicrb/mimemagic/issues/98)

**Comment by pjmartorell** [comment]
there is a replacement for `mimemagic`, check `marcel` 1.0.0

**Comment by tannalynn** [comment]
This has been resolved and our CI is passing now
