### ISSUE TITLE
Add latest Pumas to Rack instrumentation test matrix

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#652]
We're only testing up to Puma 3.11.x in our Rack instrumentation tests.

Add 4.x, 5.x to the matrix.  5.2.2 is latest Puma version at the time of this writing.

**Comment by ChaelCodes** [comment]
Does this just involve adding [new Puma versions here](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/test/multiverse/suites/rack/Envfile)? Or is it more complicated?
