### ISSUE TITLE
Rainbows is still marked as experimental

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#653]
The Rainbows framework has been experimental since v3.6.0 of the Agent. 

Rainbows is now at 5.2.1 with > 500k downloads.  Review supportability of latest and remove experimental status.

**Comment by kaylareopelle** [comment]
Due to low adoption, we deprecated the support for rainbows in version 8.7.0 of the agent. Closing this since we will not need to update the instrumentation anymore.
