### ISSUE TITLE
Replace HTML in our config descriptions with markdown

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#658]
In our default_source.yml, we have descriptions for our config settings that are used to generate the [config documentation](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/agents/ruby-agent/configuration/ruby-agent-configuration.mdx). The docs site uses markdown now, so our script is replacing the preferred markdown with html when defining links and bold text. 
We should find all instances of using html in our config descriptions and update to use markdown.
Example: 
`<a href="https://docs.newrelic.com/docs/accounts-partnerships/accounts/account-setup/license-key">license key</a>`
to 
`[license key](https://docs.newrelic.com/docs/accounts-partnerships/accounts/account-setup/license-key)`

**Comment by tannalynn** [comment]
Feedback from the docs team indicates that links actually should not be the full link since it can have issues sometimes like that, so we should use relative links
Example:
```
https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/mongo-instrumentation
```
should instead be
```
/docs/agents/ruby-agent/frameworks/mongo-instrumentation
```

**Comment by wyhaines** [comment]
Please let me know if there is anything that you would prefer that I do differently in the PR (and in future PRs).  Thank you!

**Comment by angelatan2** [comment]
@wyhaines Thanks for signing the CLA and thank you for your contribution.  We will review your contribution soon.
