### ISSUE TITLE
Update CI to use Ubuntu 20.04

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#678]
GHA ubuntu latest has moved to Ubuntu 20.04.  When running Ubuntu 20.04 with our CI, we ran into failures.  This issue is to upgrade and resolve the failures of our CI.  At the moment the CI is on Ubuntu 18.04.

**Comment by fallwith** [comment]
We're hoping that once we get all CI tests passing for #903, we'll be ready to make the switch to 20.04.
