### ISSUE TITLE
Make configuration callbacks consistent with config source precedence

### ISSUE THREAD

**Issue by amhuntsman** [newrelic/newrelic-ruby-agent#691]
A client had noted that when passing NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERRORS to a Ruby application, this value was overwritten by server-side config values for `error_collector.ignore_errors`. Investigation revealed that certain config settings would use environment variables over server-side configs, but others would not. This was reproducible in local testing.

A possible cause for this lies in the way some parts of the agent code fetch config values. Whenever a config source - e.g. ServerSource, YamlSource, EnvironmentSource - is loaded, the agent invokes `NewRelic::Agent::Configuration::Manager#replace_or_add_config` on that source, which passes its values to any callbacks for each config setting that's been defined. For example, `ErrorCollector` registers this callback on setup:

    Agent.config.register_callback(:'error_collector.ignore_errors') do |ignore_errors|
      initialize_ignored_errors(ignore_errors)
    end

What this means is that whenever a config source is loaded, this callback will be called with `ignore_errors` being the value given by `error_collector.ignore_errors` in that source. The `initialize_ignored_errors` method will then populate an `@ignore` variable based on this value.

Where I think we're hitting trouble is the fact that server configs are loaded *after* other sources initially, and then again whenever the server-side config changes. This causes the agent to overwrite whatever may have been set in the environment by what is provided by the server. This is *not consistent* for all configuration settings - it depends on how the agent checks the value of any particular setting. For example:

    def distributed_tracing_enabled?
     NewRelic::Agent.config[:'distributed_tracing.enabled']
    end

Helper methods like this will always check the configuration cache, which observes the config precedence stack. However, a registered callback like the one above will only set its relevant value once on loading, bypassing precedence.

I had some discussion with the Ruby Agent team about this. The question arose of whether our documentation is wrong, and that we should make server-side config a higher precedence than environment variables - this is already done in other language agents. However, I *suspect* that our docs are correct, that the *intent* is that environment variables should have higher precedence, and that over the course of 8 or so years of development, the config event callback system has gotten out of sync with the source precedence system, and that this has been a latent issue since clients aren't as likely to be overriding server-side configs with env variables.

Whatever the intended precedence, we should review the config callback system in place, particularly:
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/configuration/manager.rb#L159

A full review of this code and existing callbacks I estimate would take 1-2 weeks of work.

@angelatan2 @tannalynn

**Comment by angelatan2** [comment]
Please verify the assessment above with the x-agent spec for Expected Errors and Ignore Error.  
[Internal Only](https://source.datanerd.us/agents/agent-specs/blob/master/Errors.md#ignore--expected-errors)
Note for the case of Expected errors and Ignore error feature configuration, many of these configurations are not meant to be specified in the environment configuration.

**Comment by fallwith** [comment]
Closing as per Ruby agent dev team discussion today.
