### ISSUE TITLE
Clarify Browser Default Configuration Setting Documentation 

### ISSUE THREAD

**Issue by linbaker** [newrelic/newrelic-ruby-agent#701]
## Description

Browser configuration has the default setting as 'Dynamic' - this is confusing when in almost every situation, the default value is true. 

https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/#browser_monitoring-auto_instrument

## Expected Behavior

Add comment in configuration description that it will be set to 'true' in almost all cases

**Comment by tannalynn** [comment]
Note: This is part of our autogenerated docs for configuration, we'll need to change that in default_source.rb and generate new config docs

**Comment by tannalynn** [comment]
Docs PR merged
