### ISSUE TITLE
`ActionController::Metal` integration

### ISSUE THREAD

**Issue by chaffeqa** [newrelic/newrelic-ruby-agent#710]
When using the guide to adding `ActionController::Metal` support, the controller mixins do not get properly added.

## Description
The code suggests that as long as `ActionController::Instrumentation` is included, NR will add appropriate hooks to enable "Rails" support.  However, adding `newrelic_ignore` results in a compile error.  This is because even though the hook is invoked, all NR controller mixins are only added to `ActionController::Base`, and therefore not the base application.

The hope is you can extend the controller, not just `ActionController::Base`, but I beleive the problem is the `on_load` hook passes in `ActionController::Base` as the `context`

## Expected Behavior
`newrelic_ignore` would work in `ActionController::Metal` context

**Comment by amhuntsman** [comment]
@chaffeqa Just to make sure, is this the guide you're looking at? https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/metal-controller-instrumentation/

Based on the rationale in this guide, I would presume that not including helpers from `NewRelic::Agent::Instrumentation::ControllerInstrumentation` into `ActionController::Metal` is intentional. However, if you are instrumenting Metal controllers, this should accomplish what you describe:

    class MetalController < ActionController::Metal
      include ActionController::Instrumentation
      include NewRelic::Agent::Instrumentation::ControllerInstrumentation

      newrelic_ignore :only => [:show]

      def show
        self.response_body = "Hello World!"
      end
    end

I cannot confirm this as documented or even recommended behavior, but I will check on it.

**Comment by chaffeqa** [comment]
Got it, so I guess the only change I'd recommend is to:

- Add a note that none of the helper methods are added *unless* `NewRelic::Agent::Instrumentation::ControllerInstrumentation` is included or...
- add `include NewRelic::Agent::Instrumentation::ControllerInstrumentation` commented out in the code snippet with a note above it explaining that it can be included to get access to the helpers

I guess its just not clear that when saying `you can use with Metal` that doesn't mean all documented functionality is available, there is no caveate.

**Comment by amhuntsman** [comment]
@chaffeqa Would you mind sharing your particular use case in instrumenting `ActionController::Metal`? Typically this is used for more performant requests than `ActionController::Base` provides, but having more detail will help us improve instrumentation in this area.

**Comment by chaffeqa** [comment]
So the situation arose from the fact that we needed to remove x1 middleware, the best way to do that in rails practice is [documented here](https://api.rubyonrails.org/classes/ActionController/Base.html#method-c-without_modules)

**Comment by kaylareopelle** [comment]
New documentation added and merged into https://github.com/newrelic/docs-website/pull/7233

**Comment by kaylareopelle** [comment]
Hi @chaffeqa! 👋  I wanted to let you know that our documentation for `ActionController::Metal` has been updated and will be published alongside our next release. Thanks for bringing this to our attention!
