### ISSUE TITLE
Failure to load a configuration YAML file containing integer values

### ISSUE THREAD

**Issue by cbeer** [newrelic/newrelic-ruby-agent#713]
## Description

NewRelic breaks when it loads a configuration containing integer values:

```
NoMethodError: undefined method `empty?' for 404:Integer
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/error_filter.rb:32:in `load_from_config'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/error_collector.rb:32:in `block (2 levels) in initialize'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/configuration/manager.rb:157:in `register_callback'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/error_collector.rb:31:in `block in initialize'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/error_collector.rb:30:in `each'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/error_collector.rb:30:in `initialize'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/agent.rb:63:in `new'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/agent.rb:63:in `initialize'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/agent.rb:106:in `new'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/agent.rb:106:in `instance'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/new_relic/control/instance_methods.rb:70:in `init_plugin'
/opt/app/mise/mise/shared/bundle/ruby/3.0.0/gems/newrelic_rpm-7.2.0/lib/newrelic_rpm.rb:41:in `block in <class:Railtie>'
```

## Steps to Reproduce

Our newrelic configuration includes configuration like:

```
common: &default_settings
  # ...
  error_collector:
    enabled: true
    ignore_status_codes: 404
```

This breaks in the newrelic 7.2.0 release (commit 673b4711c014efa47806b83ecd63730dcbff0966).

**Comment by tannalynn** [comment]
Hello @cbeer 
We introduced the `ignore_status_codes` config value in 7.2.0, however originally this [config value](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-ignore_status_codes) was expected to be a comma delimited string, and not a single integer value. However, I agree that an integer should be allowed as well, so I'll put this in our backlog for us to change. Thanks for bringing this to our attention!

**Comment by brammerl** [comment]
TO DO - TESTS: 
[x] A test in error_filter_test.rb to account for integer inputs

**Comment by elaguerta** [comment]
Hi @cbeer thanks for posting this bug! Just updating you on the status. We resolved it so that you will be able to include an Integer status code in the config. The fix will be included in a future release. Thanks for your contribution!
