### ISSUE TITLE
Validate options for add_method_tracer earlier in call

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#720]
Refactor validating options to occur earlier with the API call (current implementation raises exception that appears to go unhandled, change to logging error instead).  Ensure invalid options aren’t preventing agent from starting and also that exceptions raised here aren’t stopping customer’s app from running properly.

**Comment by angelatan2** [comment]
7/26/2021 This story will be reviewed once the method tracer PR is merged.  We need more information on the exception itself and will monitor after the merge.
