### ISSUE TITLE
Performance testing for add_method_tracer changes

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#721]
Run performance tests on the changes in add_method_tracer and track changes and improve as we can.

**Comment by amhuntsman** [comment]
Here are the benchmark results for a performance test relevant to the method tracers rework. The test itself adds a method tracer to an empty method, then calls that method an arbitrarily large number of times (10k in this case). These are the results over 1k iterations of that test.

```
# dev

% script/runner -T TransactionTracingPerfTests#test_long_transactions -N 1000
1 tests, 0 failures, 759.035805 s total

TransactionTracingPerfTests#test_long_transactions: 1.781 ips (561.42 ms / iteration)
    cpu_time_user: 542.711 (0.54 / iter)
  cpu_time_system: 16.6043 (0.02 / iter)
       iterations:    1000


# method_tracer_prepend

% script/runner -T TransactionTracingPerfTests#test_long_transactions -N 1000
1 tests, 0 failures, 30508.917091 s total

TransactionTracingPerfTests#test_long_transactions: 1.211 ips (825.77 ms / iteration)
    cpu_time_user: 797.335 (0.80 / iter)
  cpu_time_system: 25.1792 (0.03 / iter)
       iterations:    1000
```

The difference in each iteration is roughly 0.25 seconds. That accounts for 10k invocations of the traced method, so the actual overhead of calling the method is much smaller. Of course this is important if a customer’s traced method is being called many times.

Also bear in mind that our test methods here don’t actually *do* anything, so these numbers reflect only the overhead of calling the traced method. It’s arguably reasonable to assume that traced methods in the wild are not computationally trivial.
