### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by khanimdad** [newrelic/newrelic-ruby-agent#727]
#<Thread:0x00005621b3df0928 /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10650: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
	10649: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:724:in `block in start_worker_thread'
	10648: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:697:in `deferred_work!'
	10647: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:678:in `catch_errors'
	10646: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:698:in `block in deferred_work!'
	10645: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent.rb:501:in `disable_all_tracing'
	10644: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:699:in `block (2 levels) in deferred_work!'
	10643: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/agent.rb:944:in `connect'
	 ... 10638 levels...
	    4: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `parse'
	    3: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `new'
	    2: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/uri.rb:823:in `initialize'
	    1: from /home/imdad/.rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/uri.rb:2392:in `defer_validation'
/home/imdad/.rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/uri.rb:826:in `block in initialize': stack level too deep (SystemStackError)

**Comment by angelatan2** [comment]
Hello @khanimdad, Thank you for submitting the issue regarding the stack level-too-deep.  We and the community have helped to resolve this expected effect with Major Release 7.0. 

Have you reviewed this [Prepend Blog](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/migration-7x-guide/#prepend-instrumentation)?

**Comment by khanimdad** [comment]
Sorry @angelatan2, it still not working with release 7.2 or 7.0, I have rails 6.1 and ruby 2.7

**Comment by tannalynn** [comment]
Hello @khanimdad 

Please see our [troubleshooting guide](https://docs.newrelic.com/docs/agents/ruby-agent/troubleshooting/systemstackerror-stack-level-too-deep/) on how to resolve this error using configuration options available in the agent. Thank you.
