### ISSUE TITLE
Create a Migration Guide for Ruby Agent 7.0 to Ruby Agent 8.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#732]
We should create a migration guide to enable our customers a smooth transition from Ruby Agent 7.0 to Ruby Agent 8.0.

### Feature Description
In the document, please identify APIs,  configuration changes, or removal. The document should help to guide our customers with the usage of newer supported APIs and configurations.  Please provide examples when appropriate on how to apply the replacement APIs (Reference Method Tracer changes) and configurations.

Please document features that will be deprecated as well as features that will become default.

Review the lessons learned from previous 6.0 to 7.0 migration guide whereby we needed to add more troubleshooting guidance to prepend to enable our customers to unblock themselves.  If there are relevant troubleshooting steps, please also consider them in this story.

### Additional context
[Internal link](https://newrelic.atlassian.net/browse/DOC-7188?atlOrigin=eyJpIjoiMDdiYTcyMDM5NTJhNGMwZTk5ZjgxYWI2NGYxZWY3MWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

### Priority
Must Have, target release by August 20th.

**Comment by tannalynn** [comment]
PR https://github.com/newrelic/docs-website/pull/3592
