### ISSUE TITLE
Agent injects javascript into XML resource when there is a <head> tag

### ISSUE THREAD

**Issue by jcavalieri** [newrelic/newrelic-ruby-agent#734]
## Description

I'm working on a project that has NITF as the content of an Atom XML feed. NITF has a <head> tag. It appears that the New Relic agent sees the head tag and assumes it is HTML. And then injects JavaScript.

## Expected Behavior
No JavaScript injection for files ending in `.xml`

## Steps to Reproduce
1. Create an XML resource that includes a <head> tag
2. View page source

E.g.
```
<?xml version="1.0"?>
<feed xmlns:apnm="http://ap.org/schemas/03/2005/apnm" xmlns="http://www.w3.org/2005/Atom" xmlns:apcm="http://ap.org/schemas/03/2005/apcm">
    <author>
        <name>Example</name>
        <uri>http://example.com/</uri>
    </author>
    <id>ExampleId</id>
    <title>Example Title</title>
    <link href="http://example.com/" rel="self"/>
    <updated>2021-07-21T21:00:34-04:00</updated>
    <entry>
        <content type="text/vnd.IPTC.NITF">
            <nitf xmlns="http://iptc.org/std/NITF/2006-10-18/" version="-//IPTC//DTD NITF 3.6//EN">
                <head>
                    <script type="text/javascript">
                    window.NREUM || (NREUM = {});
                    NREUM.info = {
                        "beacon": "bam.nr-data.net",
                        "errorBeacon": "bam.nr-data.net",
```

## Your Environment
Rails 5.2.5
newrelic_rpm (7.1.0)

**Comment by amhuntsman** [comment]
@jcavalieri Thank you for the report. I have been trying to replicate this behavior in Rails, but our browser monitoring middleware should check that the Content-Type of the response is text/html before injecting any JS. Can you confirm that the XML page in your example is being served as */xml?

https://github.com/newrelic/newrelic-ruby-agent/blob/7.1.0/lib/new_relic/rack/browser_monitoring.rb

**Comment by angelatan2** [comment]
@jcavalieri we have not heard from you for a while. I understand everyone has priorities.  If you get a chance, could you respond to the question above, please?  We plan to close this issue next Monday 8/23/2021 if there is no response because we are unable to proceed.

**Comment by jcavalieri** [comment]
What happens on your end when content type is not set?

**Comment by jcavalieri** [comment]
But it looks like I need to set the content type. It is not set on our end.

**Comment by jcavalieri** [comment]
Feel free to close if you would like.

**Comment by angelatan2** [comment]
Hello @jcavalieri, thank you for the feedback.  Did adding the content type help to resolve the issue that you saw?

**Comment by angelatan2** [comment]
Closing this issue per previous response.
