### ISSUE TITLE
Remove deprecated legacy Excon instrumentation 

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#741]
Remove support for Excon versions below 0.19.0

File: `lib/new_relic/agent/instrumentation/excon.rb`

* Remove deprecated method to install legacy Excon instrumentation. 
* Replace all calls to `Excon#install_legacy_excon_instrumentation`
 with `install_middleware_excon_instrumentation`
* Add removal to CHANGELOG
* Add steps to adjust to migration guide

**Comment by angelatan2** [comment]
Size - Small
