### ISSUE TITLE
Remove deprecated method to install legacy Mongo instrumentation

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#742]
Remove support for Mongo versions below 2.10.0 

File: `lib/new_relic/agent/instrumentation/mongo.rb`

* Remove Mongo#install_mongo_instrumentation 
* Replace all references to Mongo#install_mongo_instrumentation with Mongo#install_mongo_command_subscriber
* Add removal to CHANGELOG
* Add steps to adjust to migration guide

**Comment by angelatan2** [comment]
Size = Small.
