### ISSUE TITLE
Remove deprecated Transaction.wrap class method

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#744]
The `Transaction.wrap` class method was deprecated three years ago. Let's remove it.

File: `lib/new_relic/agent/transaction.rb` 

* Remove deprecated method, `NewRelic::Agent::Transaction.wrap`
* Replace all calls to `Transaction.wrap` with `Tracer#in_transaction` (and verify this is the correct method)
* Add removal to CHANGELOG
* Add steps to adjust to the migration guide

**Comment by angelatan2** [comment]
For the initial scope, let's review and verify that deprecation is in the public-facing API document in addition to the deprecation note in logs.

**Comment by pizzaz93** [comment]
The deprecation is mentioned in the Changelog [here](https://github.com/newrelic/newrelic-ruby-agent/blob/1c0a3be631078b6b40c813c426c913be9a6b0f58/CHANGELOG.md#v600)

**Comment by hannahramadan** [comment]
This work was previously completed with PR #757. [Commit](https://github.com/newrelic/newrelic-ruby-agent/commit/ece33a252f4ff503e6296a31d568f5c28af09f5e).
