### ISSUE TITLE
Remove deprecated method, NewRelic::Agent#disable_transaction_tracing

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#745]
The `NewRelic::Agent#disable_transaction_tracing` method was deprecated three years ago. Let's remove it.

File: `lib/new_relic/agent.rb`

* Remove the deprecated method, `NewRelic::Agent#disable_transaction_tracing`
* Replace all calls to `NewRelic::Agent#disable_transaction_tracing` with `NewRelic::Agent#disable_all_tracing` or `NewRelic::Agent#ignore_transaction`
* Add removal to CHANGELOG
* This is part of the public API. Update references in the documentation to note removal, replacements, and supported versions.
* Add steps to adjust to the migration guide

**Comment by angelatan2** [comment]
Size = S

**Comment by angelatan2** [comment]
For the initial scope, let's review and see if the public API doc has called out deprecation in addition to the deprecation shown in the log for this method.

**Comment by tannalynn** [comment]
closing, PR merged
