### ISSUE TITLE
Remove deprecated method, NewRelic::Agent::External#start_segment

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#746]
The `NewRelic::Agent::External#start_segment` method was deprecated three years ago. Let's remove it.

File: `lib/new_relic/agent/external.rb`

* Remove deprecated method, `NewRelic::Agent::External#start_segment`
* Replace all calls to `NewRelic::Agent::External#start_segment` with `Tracer#start_external_request_segment`
* Add removal to CHANGELOG
* This is part of the public API. Update references in the documentation to note removal, replacements, and supported versions.

**Comment by angelatan2** [comment]
A quick review showed that the customer-facing documentation did not call out deprecation on this method.   At a minimum add deprecation to documentation.
