### ISSUE TITLE
Remove unused start_time argument from SqlSampler#on_start_transaction 

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#758]
### Overview
The second argument in `SqlSampler#on_start_transaction`, `start_time` is not called in the method. Let's remove the argument and clean up the references to it in the tests and codebase.

Discovered while developing https://github.com/newrelic/newrelic-ruby-agent/pull/757 

### Priority
Nice to Have

### T-shirt Size
S

**Comment by angelatan2** [comment]
Changes were added to #757
