### ISSUE TITLE
Multiverse Test Suite Requiring Bundler 2.2.27 and 1.17.3 Depending on EnvFile 

### ISSUE THREAD

**Issue by brammerl** [newrelic/newrelic-ruby-agent#769]
## Description
When running the Padrino test suite using 2.6.8 and both bundler 2.2.27 and 1.17.3, the test asks for JUST 1.17.3. But when we delete 2.2.27 the test requires 2.2.27. It won't allow us to manually switch between bundler versions to run the tests. It will always fall back on the most recent version. 

## Expected Behavior
We expect the test to be able to run either 2.2.27 or 1.17.3 depending on what it is required at the time. 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
``` 
Your bundle requires a different version of Bundler than the one you're running.
Install the necessary version with `gem install bundler:1.17.3` and rerun bundler using `bundle _1.17.3_ install`
System command: bundle install failed 3 times. Giving up...
Failed local bundle, trying again without the version lock...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile.0:
    padrino (~> 0.14.0) was resolved to 0.14.0, which depends on
      padrino-gen (= 0.14.0) was resolved to 0.14.0, which depends on
        bundler (~> 1.0)

  Current Bundler version:
    bundler (2.2.27)
```

## Steps to Reproduce
Use ruby 2.6.8, have bundler 2.2.27 and 1.17.3 installed at the same time. 
bundle exec rake test:multiverse\[padrino\]  

## Your Environment
Running agent locally off of `dev` branch 

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

**Comment by elaguerta** [comment]
Tests pass locally with the latest version of padrino=0.15.1 with ruby=2.6.8 and bundler=2.2.7.

They do not pass locally with padrino=0.14 because earlier versions of padrino require bundler 1.17.3. Fortunately, he github CI will automagically run the older bundlers with the older padrinos.
