### ISSUE TITLE
Add missing instrumented gems to docs site

### ISSUE THREAD

**Issue by tristinbarnett** [newrelic/newrelic-ruby-agent#771]
### Is your feature request related to a problem? Please describe.
Incomplete documentation

### Feature Description
Gems are missing from [Ruby agent requirements and supported frameworks](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/)

- yajl-ruby
- actionview
- activejob
- actioncable

Documentation does not state that sinatra, padrino, and grape are excluded on Ruby 3

### Additional context
Discovered while woking on yajl-ruby ignite sprint goal updates. Additional gems from Erik's Ruby Gem Analysis

### Priority
[Must Have]

**Comment by angelatan2** [comment]
@tristinbarnett for those gems that are missing from our documentation, do you have the versions that we support? If you do, could you please add to this ticket?

**Comment by elaguerta** [comment]
Closed by this PR to the docs website: https://github.com/newrelic/docs-website/pull/3867

yajl-ruby: we added a line in the docs that says:

> * Yajl-Ruby:1.1.0 or higher

`actionview`, `actionjob`, and `actioncable` come packaged with rails, so we felt that we could exclude these and rely on our rails support documentation.

We added a line stating that Grape, Padrino, and Sinatra are not supported for Ruby 3.0+
