### ISSUE TITLE
add_method_tracer NoMethodError: super: no superclass method

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#776]
## Description

When running 8.0 of the agent against an application that uses `add_method_tracer` on an instance method, without any arguments, within a module inherited by many classes, execution is stopped with the error: 

```
NoMethodError: super: no superclass method 'instance_method' for <ExampleClass>
```

## Expected Behavior
`add_method_tracer` should be able to be added to any method without raising an error or stopping execution

## Steps to Reproduce
Call a method that calls the 'instance_method' traced by `add_method_tracer`

The instance method in question was part of a module that was inherited by many other classes.

## Your Environment
Rails 3.2 LTS
Ruby 2.7.4
newrelic_rpm 8.0.0-pre

## Additional context
This came up during the prerelease testing process using an internal New Relic application.

**Comment by kaylareopelle** [comment]
Reference PR with error messages: https://source.datanerd.us/APM/rpm_site/pull/35794

**Comment by amhuntsman** [comment]
Issue was found to be in older versions of mocha gem (<1.2.0), and test helper methods using alias method chaining in setup/teardown. Both were updated in the RPM PR.
