### ISSUE TITLE
Deprecate support for yajl-ruby

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#790]
The yajl-ruby gem has not been updated since 1.4.1 in 2018.  The gem is a C binding to allow YAJL JSON parsing and generation library.

https://rubygems.org/gems/yajl-ruby/versions/1.4.1

### Feature Description
Deprecate Ruby Agent support for this gem based on our discovery documented in [internal spike](https://docs.google.com/spreadsheets/d/1ksVLFNrqgx2LcbQpa5Gsl9oRWxXrrq6u2v26VG4I0yg/edit#gid=524076386)

### Describe Alternatives
N/A

### Additional context
Reduce the toil/chore of updating verification on a gem with limited usage.

**Comment by elucus** [comment]
Since we are supporting the latest version we will keep support for yajl-ruby and review if/when they release a new version.

**Comment by fallwith** [comment]
We test agent compatibility with YAJL, and don't instrument it for customer use. We're happy with the checks being currently performed for compatibility and will leave them be for the time being.
