### ISSUE TITLE
Update Core Tech: Rack Gem

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#791]
This is a follow-up story from Ignite Sprint's goal.
- [ ] Understand if methods were deprecated by gem owners.
- [ ] Find new methods that are of value
- [ ] Instrument those new methods
- [ ] Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.

**Comment by fallwith** [comment]
> Understand if methods were deprecated by gem owners.

We instrument `URLMap` and `Builder`. Neither of these have been deprecated. `Builder#run` has been updated to accept a block, however, and we will need to conditionally (if Rack >= v3.0.0) update our own instrumentation to handle a block as well.

> Find new methods that are of value

and

> Instrument those new methods

From looking over the [added](https://github.com/rack/rack/blob/main/CHANGELOG.md#added) list, there isn't anything new on the same level as `Builder` or `URLMap`.

> Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.

This has already been done for Rack.
