### ISSUE TITLE
Update Redis gem

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#792]
This is a follow-up story from Ignite Sprint's goal.
- [ ] Understand if methods were deprecated by gem owners.
- [ ]  Find new methods that are of value
- [ ] Instrument those new methods
[Done] Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.

**Comment by fallwith** [comment]
closing in favor of #1361
