### ISSUE TITLE
CI: Test ARM64

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#797]
### Is your feature request related to a problem? Please describe.

The Ruby Agent outlines its supported Ruby versions and Operating Systems on the [docs website](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/). 

~~Our CI does not currently test against every supported version. Some notable outliers are JRuby 9.0 and 9.1. We are not actively monitoring the way our agent code may run against these older JRuby versions.~~

During our ARM64 spike, we determined the 8.0 agent could run on ARM64 using Ruby 3.0 and 2.7. We do not currently have a CI or other automated system of checks to verify whether ARM64 support will be maintained.

### Feature Description

Create a GitHub Action that runs the CI against lesser-used versions of Ruby/OS in the following cases: 
* When merging a branch 
* When creating a PR for the `dev` branch into the `main` branch

At a minimum, the Ruby/OS versions that should be included in this Action are:
 * ARM64 
 * ~~JRuby 9.0.x~~
 * ~~JRuby 9.1.x~~

A possible expansion of this scope could be to move versions of MRI with a low customer usage rate to the new action.

#### Point of Inquiry
We are operating under an assumption that the CI will take an unreasonable amount of time to run if these Ruby/OS versions are included in our current checks run on commit. When working on this ticket, verify the time it takes to add the new Ruby/OS versions. Check with the team to determine if this time is reasonable or if it requires a separate CI action.

### Describe Alternatives

Instead of running the new action on merge, it could be run on every commit to a PR. This would likely increase the length of the CI. ARM64 will double the runtime. ~~JRuby 9.0.x and 9.1.x will likely add a few minutes.~~ 

Instead of running the new action on merge, it could be run on a regular schedule. This functionality in GitHub actions seems to have [recently changed behavior](https://newrelic.slack.com/archives/C119L74HL/p1632499300114800). This may allow breaking changes 

### Additional context

These changes may provide the following benefits:
* Faster development CI when making frequent changes
* Verification check before merging work into the `dev` branch that supported versions will not have regressions

These benefits may come at the cost of the following trade-offs: 
* Impact on morale -- when a developer believes an issue is resolved, the merge PR may tell a different story and require additional work
* ~~Increased lead time for this unit of work -- we are not aware how JRuby 9.0.x and JRuby 9.1.x operate within our current test suite and may need to make fixes.~~

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**2022-08-15 UPDATE** struck out all JRuby related content, as we are currently in good shape there, and renamed this one to "CI: Test ARM64". Unfortunately, our options for testing ARM64 aren't great. We can [self-host](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) a runner. Or we can use a [third party action](https://github.com/marketplace/actions/run-on-architecture) that does things that are not supported by GitHub.

**Comment by angelatan2** [comment]
A spike was completed on ARM64 discovery as well as adding to the support statement.  We allocated no implementation time during the Spike to add verification of ARM64 to CI.

**Comment by tannalynn** [comment]
Testing ARM64 using github actions would require use of the large custom runners, which would incur a cost. However, the risk for the ruby agent running on ARM64 is very low since anything related to architecture is handled by the ruby language, and not the agent.
