### ISSUE TITLE
Padrino Multiverse tests do not accurately test instrumentation installation

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#802]
A bug was reported (#737) that the padrino instrumentation was not working correctly. After looking into it we found that the padrino instrumentation was not being installed in such a way that it would work. The instrumentation was being installed too late for us to prepend, as the ancestor chain had already been established on the objects using the modules we prepended our instrumentation to. 
While we were able to correct the issues with instrumentation installation, we were not able to figure out a way to update our padrino tests to load the same way as running a padrino app outside of multiverse does. The tests do still test the functionality of the instrumentation, however it is not able to accurately test **IF** the instrumentation actually gets installed. 
We should update our multiverse tests to load padrino in the same way an application using padrino does.

**Comment by kaylareopelle** [comment]
A similar issue was raised during the resolution of an issue related to Rails load order and initializers. 

Issue: https://github.com/newrelic/newrelic-ruby-agent/issues/662 
PR: https://github.com/newrelic/newrelic-ruby-agent/pull/806

**Comment by angelatan2** [comment]
The original failure no longer occurs.  Improvements have been made to our test and merged.
