### ISSUE TITLE
Add mysql2 instrumentation

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#815]
Add instrumentation for the [mysql2](https://rubygems.org/gems/mysql2) gem, a "A simple, fast Mysql library for Ruby, binding to libmysql."

## Spike Questions
_Fill in the blanks/remove unrelated items before getting started..._

* We plan to instrument the following methods: 
* We plan to add the following metrics:
* We plan to add the following supportability metrics: 
* We plan to add the following events: 
* We will load this instrumentation based on the following conditions:

_Consider the following questions and add responses if appropriate_
* Are there other things, like samplers, that would be good to add? 
* Where could conflicts with our existing instrumentation and structure come up? 

## Checklist
_All items should be checked off before the issue is closed_

### Code
- [ ] Are there instrumentation options for chain and prepend?
- [ ] Has a new multiverse suite been created for the instrumentation?
  - [ ] If the gem is installed, does it load?
  - [ ] If the gem isn’t installed, does it skip? 
  - [ ] Are errors raised by the gem we’ve instrumented being recorded by the agent?
  - [ ] Do any errors raised by New Relic code escape the agent? 
  - [ ] Are the metrics we’ve added reporting?
  - [ ] Are the events we’ve added reporting? 
- [ ] Can a new performance test be added for this instrumentation? (Probably no, but think about it for a sec…)
- [ ] How is the signal-to-noise ratio for the new data flowing from the agent? Is this new data valuable to customers? Does it overflow them with too much information?
- [ ] How are the methods we’ve instrumented helping our customers solve new problems?

### Public documentation
- [ ] Has the [Ruby agent requirements and supported frameworks document](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/) been updated to include support for this instrumentation?
- [ ] Have any new configuration options been added to:
  - [ ] [Default Source](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/configuration/default_source.rb)
  - [ ] [newrelic.yml](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/newrelic.yml)
  - [ ] [Config docs](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/)
- [ ] Have you added an entry to the Changelog?

### Pull Request 
- [ ] Have you attached a screenshot where the data is reporting in the UI?
- [ ] Do you have a blurb in the PR about why the instrumented method(s) were chosen?
- [ ] Does this instrumentation create any new metrics? What are they?
- [ ] Does this instrumentation create any new events? What are they?

**Comment by fallwith** [comment]
Closing as unnecessary / redundant with the database information already collected by our existing Active Record instrumentation.
