### ISSUE TITLE
Investigate the behavior of Ruby Agent with 8T enabled when running into an expired certificate issue

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#832]
Discover the following:
- If the agent encounters an expired cert, what is the behavior?
- When the agent encounters a disconnect on 8T, it should back off as per agent spec.
- Investigate gRPC behavior when there is a disconnect to the endpoint.

## Expected Behavior
If using older SSL clients, we would expect the endpoint to disconnect.
We expect the backoff strategy to be as per agent spec.

## Steps to Reproduce
Use the recent release of the agent and point it to the staging environment with the expired cert.

**Comment by kaylareopelle** [comment]
Internal Document with answers to the questions outlined above: https://docs.google.com/document/d/1WcLPY6-qzGcoSXgvpy7iOYUV-SRmQ_E6_4TQddmZTn8/edit#

**Comment by angelatan2** [comment]
@kaylareopelle @tannalynn for investigating the behavior of 8T reconnects!
