### ISSUE TITLE
NewRelic::Agent.add_custom_attributes support for ActiveJob::DelayedJob transactions

### ISSUE THREAD

**Issue by danielmklein** [newrelic/newrelic-ruby-agent#834]
### Is your feature request related to a problem? Please describe.
In many of our controllers, we do things like...
```ruby
    ::NewRelic::Agent.add_custom_attributes(
      {
        my_cool_attribute: "blah"
      }
)
```
to add custom attributes to the resulting transactions, which we can then use in queries when generating charts and whatnot in New Relic. However, we cannot figure out how to implement this same functionality for `ActiveJob::DelayedJob` transactions so that we can add similar info to our background job transactions.

### Feature Description
We would really, really like an easy way to add custom attributes to `ActiveJob::DelayedJob` transactions.

### Describe Alternatives
We have tried creating a DJ plugin like so:
```ruby
module NewRelicInstrumenter
  class DelayedJobPlugin < Delayed::Plugin
    callbacks do |lifecycle|
      lifecycle.before(:perform) do |_worker, job|
        ::NewRelic::Agent.add_custom_attributes(
          {
            my_test_attribute: "blah"
          }
        )
      end
    end
  end
end
```

and then adding it into our DJ initializer (`config/initializers/delayed_job.rb)` like so:
```ruby
require "new_relic_instrumenter"

Delayed::Worker.plugins << NewRelicInstrumenter::DelayedJobPlugin
```

but we do not see any custom attributes on the resulting transactions. I'm not sure if we're just missing the right place/way to implement this, or if it's not possible right now, but we would LOVE guidance/tips here.

### Additional context
n/a

### Priority
[Really Want]

**Comment by kaylareopelle** [comment]
Hi @danielmklein, thanks for reaching out! I'm surprised to hear `NewRelic::Agent.add_custom_attributes` isn't working within `ActiveJob::DelayedJob` transactions. 

I have a few questions I hope will provide some context to dive more deeply into this issue:

* Do you see any errors or other odd messages in the `newrelic_agent.log` file when attempting either strategy? 
* What versions run on your application for the following:
  * Ruby 
  * ActiveJob
  * DelayedJob 
  * newrelic_rpm

**Comment by danielmklein** [comment]
@kaylareopelle thanks for following up!!

I do not see anything unexpected in `newrelic_agent.log`.

We are running...
* Ruby 2.7.4
* activejob 6.1.4.1
* delayed_job 4.1.9
* newrelic_rpm 8.1.0

For some additional context that I just noticed --

If I add custom attributes from _within the job's `perform` method itself_, it works. However, when doing this I cannot access DJ-specific stuff like what time the job was queued (unless I am missing something). In other words, this works, and I see the custom attributes on the resulting transactions:
```ruby
class NewRelicTestJob < ApplicationJob
  queue_as :default

  def perform
    ::NewRelic::Agent.add_custom_attributes(
      {
        job_class: "NewRelicTestJob",
        attribute_source: "inside_the_job"
      }
    )
    puts "Hello from NewRelicTestJob at #{Time.current}!"
  end
end
```

However, adding attributes from a DJ plugin does not work (I know I've already said this, just wanted to get both these in one place). Digging into the source code a bit, I noticed that if I put a breakpoint inside the block here, `NewRelic::Agent::Transaction.tl_current` is nil, which I _think_ has something to do with why attributes added here don't make it (because there's maybe not yet an actual transaction to put them on?):

```ruby
module NewRelicInstrumenter
  class DelayedJobPlugin < Delayed::Plugin
    callbacks do |lifecycle|
      lifecycle.before(:perform) do |_worker, job|
        # `NewRelic::Agent::Transaction.tl_current` is nil here
        ::NewRelic::Agent.add_custom_attributes(
          {
            job_class: job.payload_object.job_data["job_class"],
            attribute_source: "NewRelicInstrumenter:DelayedJobPlugin",
            job_creation_time: job.created_at
          }
        )
        puts "Hello from NewRelicInstrumenter::DelayedJobPlugin at #{Time.current}!"
      end
    end
  end
end
```

I hope this helps! Please let me know if there's any other info I can provide -- I am going to keep poking at things and will follow up if I have a breakthrough. 😄

**Comment by danielmklein** [comment]
Good news!! After experimenting with DJ callbacks, this works:

```ruby
module NewRelicInstrumenter
  class DelayedJobPlugin < Delayed::Plugin
    callbacks do |lifecycle|
      lifecycle.around(:invoke_job) do |job, *args, &block|
        # Forward the call to the next callback in the callback chain
        puts "Hello from NewRelicInstrumenter::DelayedJobPlugin at #{Time.current}!"
        ::NewRelic::Agent.add_custom_attributes(
          {
            job_class: job.payload_object.job_data["job_class"],
            attribute_source: "NewRelicInstrumenter:DelayedJobPlugin"
          }
        )
        block.call(job, *args)
      end
    end
  end
end
```

In conjunction with (as before), this in the initializer in `config/initializers/delayed_job.rb`:
```ruby
require "new_relic_instrumenter"

Delayed::Worker.plugins << NewRelicInstrumenter::DelayedJobPlugin
```

**Comment by kaylareopelle** [comment]
That's wonderful news, @danielmklein! Thanks for sharing your solution! Is there anything else our team can do to help resolve this issue?

**Comment by danielmklein** [comment]
@kaylareopelle not currently. Is there a good place where we might be able to document this for future travelers?

**Comment by kaylareopelle** [comment]
@danielmklein - there sure is! We have a specific page in [the Ruby Agent's documentation for Delayed::Job Instrumentation](https://docs.newrelic.com/docs/apm/agents/ruby-agent/background-jobs/delayedjob-instrumentation/) that would be a good fit for this solution.

New Relic's docs are open source as well. You're welcome to contribute to this page directly by clicking the "Edit Page" button in the top right corner. If you'd prefer we take care of the changes, let me know and I'll create a ticket for our team to add the content.

**Comment by danielmklein** [comment]
@kaylareopelle thanks for the guidance! I've opened a PR on the docs repo here: https://github.com/newrelic/docs-website/pull/4887. We shall see how it fairs in the review process 😂
