### ISSUE TITLE
Test Ruby 3.1-preview1 release

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-ruby-agent#845]
Test the preview release of Ruby 3.1 and Rails 7 alpha 2.

Acceptance Criteria:

- Run test suite on Ruby 3.1 and Rails 7 alpha 2
- Document failure (stories in Github)
- T-shirt size if no spike is needed.

**Comment by kaylareopelle** [comment]
[Upgrade Estimates document](https://docs.google.com/spreadsheets/d/1RGL8Zk7XJckaUkalI3G4Sei-F3EEsmW9J03uH1t5HEw/edit?usp=sharing)

**Comment by kaylareopelle** [comment]
Hi @guillaumewrobel! 👋 

I received your request to access the upgrade estimates document. Unfortunately, this is stored on New Relic's internal Google Drive. I am not able to share the document with you at this time. Do you have any questions about our upgrade plans? Is there something specific I could help you with?

Thanks for your interest and engagement!

**Comment by guillaumewrobel** [comment]
Hey @kaylareopelle :hatched_chick: 

I clicked on the link before noticing it was an internal document. No need to share any private information.
As we only live once, we are running on the last non-released version of Rails and I'd be thrilled to get rid of the

> Detected untested Rails version 7.0.0.alpha2

warning message. Thus, if the community can do something to merge the new Ruby and Rails version acceptance tests, don't hesitate.

As always, thanks for maintaining such a great project.

**Comment by kaylareopelle** [comment]
Thanks for your response, @guillaumewrobel! I'm honored to have the opportunity to maintain it! 😄 

Oof, log messages like that are no fun. We want to do all we can to clear them out ASAP. 🤦 

With the release of Rails 7.0.0.rc1, our team has prioritized getting the agent running on Rails 7. We're creating issues for fixing failed tests and supporting new features in [this milestone](https://github.com/newrelic/newrelic-ruby-agent/milestone/21). 

Feel free to pick up a ticket or add a new issue to that milestone requesting instrumentation for your favorite Rails 7 features!

**Comment by kaylareopelle** [comment]
Closed by #859 

We'll continue to monitor [Ruby Releases](https://www.ruby-lang.org/en/downloads/releases/) for additional previews.
