### ISSUE TITLE
Switch to IMDSv2 for metadata calls.

### ISSUE THREAD

**Issue by vinoth2710** [newrelic/newrelic-ruby-agent#848]
I can see that inside lib/new_relic/agent/utilization/aws.rb, you are using IMDSv1 calls, to fetch instance details, however, it is a security recommendation that we use IMDSv2 calls for this purpose. AWS security hub recommends having [IMDSv2 calls](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) only. So, this gem using v1 calls is a blocker for us to move forward on this.

Priority:  Blocker

**Comment by tannalynn** [comment]
hello @vinoth2710 ,
Thank you for letting us know that this issue is impacting you. 
This is a Duplicate of #552, so I will be closing this issue so it can be tracked in one ticket.

**Comment by tannalynn** [comment]
Duplicate of #552
