### ISSUE TITLE
ASync Gem Instrumentation Spike

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#850]
At Rubyconf, it was discussed that the [Async](https://github.com/socketry/async) gem has been invited to ruby core, and will likely be included in 3.1 or 3.2. We should investigate this gem and how we may instrument it in the future.
Some questions to consider as part of the spike:
- How many customers are using async?
- How similar or different do things seem to be to the [concurrent_ruby](https://github.com/ruby-concurrency/concurrent-ruby) gem?
- What parts of async could be hooked into by the agent?
- What seems like the most valuable information to gather?
- What work would likely need to be completed in the agent design (for multithreaded) to support instrumentation for this gem?

**Comment by bhasto** [comment]
To share state between fibers, would it help to use thread-local instead of fiber-local variables (`thread_variable_get`, `thread_variable_set`)? That would mean fibers have access to the same state.

**Comment by fallwith** [comment]
Thanks, @bhasto, that's a great idea. We use that strategy in some key places of the agent where atomicity is important and it could very well help out here as well.

We're super interested in better instrumentation of Fiber itself and the idea could help there as well.

As for async as a topic in general, we've looked at version 2 of the Async gem, Ruby 3's fiber scheduler interface, and the concurrent-ruby gem as good candidates for instrumentation. If you have any preferences there, we welcome all community members to speak up and share what they'd like to see the agent handle. It really helps us prioritize our roadmap.

**Comment by bhasto** [comment]
Hi @fallwith. Our current use case is using the Async gem for concurrent I/O (as an alternative to threads). We’re running into similar problems with the agent that multi-threaded code usually suffers from – not seeing the correct segments in APM, method tracers don’t work etc. Solving these would be the biggest improvement for us (having some data about fiber scheduler internals and similar would be nice too but not that important for us currently).

**Comment by fallwith** [comment]
Thank you, @bhasto. I have relayed this information to our leadership team. Also, if you happen to have a support contract with New Relic, you can optionally use that as an avenue for putting forward any preferences for what we go after next - either by filing the not seeing of the correct segments as a bug, or the development of better Async specific or multi-threaded generic support as a feature request.

**Comment by tannalynn** [comment]
Spike completed
[milestone doc](https://docs.google.com/document/d/1DDILkJbtT5Iv1O2dgOffuyDVAIW44gzyP6c5g8d_wx8/edit?usp=sharing)
