### ISSUE TITLE
`ruby_agent_version` not updating on internal systems configuration pages

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#872]
## Description
The systems configuration pages' attribute for `ruby_agent_version` has not been updating upon release since:
EU - version 6.12.0 
Prod - version 6.14.0
Staging - version 7.2.0

## Expected Behavior
The latest Ruby agent version should be sent to the EU, staging, and prod environments when a new version is released.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Additional context
[GitHub Action with API call to update systems configuration](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/.github/workflows/release.yml#L61-L87)

**Comment by kaylareopelle** [comment]
@tannalynn discovered our API keys expired. Generating new API keys was enough to fix the staging and production environments. The EU key needs to be generated through an EU account. The API Evolution team is investigating the best next steps. 

[Slack thread](https://newrelic.slack.com/archives/C0MPX17GU/p1638814105194800)

**Comment by kaylareopelle** [comment]
The API Evolution team found a solution to this issue. Deployment is being tracked through https://newrelic.atlassian.net/browse/PLATFO-6990 (Internal)

**Comment by angelatan2** [comment]
Changes limited to internal key updates.
