### ISSUE TITLE
Test New Relic Ruby Agent against Rails 7 Alpha 2

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#873]
Run the existing testing frameworks that we have against Rails 7 Alpha 2.  Please create issues and t-shirt size the failures found.

**Comment by angelatan2** [comment]
Test Error:
NewRelic::Agent::Agent::ConnectTest#test_environment_for_connect: RuntimeError: Thread count changed in this test from 0 to 1 
 
Test Line:
test/new_relic/agent/agent/connect_test.rb:200

Test Error:
NewRelic::Agent::Instrumentation::ActionControllerSubscriberTest#test_records_filtered_request_params_in_txn [/home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/test/new_relic/agent/instrumentation/rails/action_controller_subscriber.rb:289]: Expected: "[FILTERED]" Actual: "secret" 

Test Line:
test/new_relic/agent/instrumentation/rails/action_controller_subscriber.rb:280

**Comment by kaylareopelle** [comment]
The Rails 7.0.0.alpha2 errors have been turned into issues and T-shirt sized: 
* https://github.com/newrelic/newrelic-ruby-agent/issues/879 (Medium)
* https://github.com/newrelic/newrelic-ruby-agent/issues/880 (Small)
