### ISSUE TITLE
Migrate our release staging from crossroad to another application/service

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#890]
Crossroad EOL in Dec 2021. 
We need to find a replacement for Crossroad that will help us verify that the agent is robust enough prior to release.  
We need to implement the replacement.
Update the release workflow.

**Comment by kaylareopelle** [comment]
@angelatan2 - Should this be addressed before 8.3.0?

**Comment by angelatan2** [comment]
@kaylareopelle I don't think that's necessary.  However, if possible, I'd like to add this to our upcoming technical debt milestone.  It's probably good to identify a few services/applications and see what gems are being used so that we have a higher coverage when we implement the replacement in our release workflow.

**Comment by kaylareopelle** [comment]
Possible replacement, available for pushes 1/17/22: https://source.datanerd.us/support-tools/haberdasher (Internal)

**Comment by kaylareopelle** [comment]
We may be able to use Demotron, an application used by Sales and Training teams, as our replacement. This application isn't slated for retirement, which makes it preferable over the app listed above.

**Comment by angelatan2** [comment]
April 2022, We have added ASGS to our staging step.
