### ISSUE TITLE
Error Inbox Grouping issue

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#899]
Errors Inbox groups errors by error message. 

We have customers reporting that they observed poor grouping because of truncated messages. Sometimes the truncated part is interesting but more often it is a result of variable length tokens that occur before the truncation making the remaining message hard to group. Our current character limit is 256, causing the truncating of error messages and the grouping logic to fail, making Errors Inbox full of duplicate-looking errors.

### Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

### Additional context
[Internal link](https://newrelic.aha.io/features/RUBY-176)

### Acceptance Criteria:
Investigate the details of the observation and share them with the team.
Assess if there is a problem or not
Share the resolution through PR if it's a bug on our end.

### Initial T-shirt size
S

**Comment by tannalynn** [comment]
After talking to the error inbox team, the ruby agent doesn't appear to be contributing to the truncation of error messages, as we do not limit error message size at all.
