### ISSUE TITLE
newrelic_ignore not available in sinatra with agent disabled

### ISSUE THREAD

**Issue by NC-piercej** [newrelic/newrelic-ruby-agent#901]
## Description
The `newrelic_ignore` method is only available for Sinatra when the NewRelic agent is enabled. This makes stuff complicated to work with in environments where NewRelic is not enabled, as the method needs to be conditionally called.

## Expected Behavior
The `newrelic_ignore` method should be available as long as `newrelic_rpm` is required. It should be a no-op when the agent is not enabled.

## Steps to Reproduce
1) Define an environment where `agent_enabled` is false in `newrelic.yml`
2) Add a `newrelic_ignore` to a Sinatra controller
3) Observe the `undefined method 'newrelic_ignore'` when running the server
4) Switch `agent_enabled` to `true`
5) Observe that stuff starts up as expected

## Your Environment
NewRelic RPM 8.3
JRuby 9.3.2.0
Sinatra 2.1

**Comment by kaylareopelle** [comment]
Thanks, @NC-piercej! We're grateful you brought this to our attention. We were able to reproduce the bug with the information you shared and will start searching for a solution. 🐛

**Comment by kaylareopelle** [comment]
Hi @NC-piercej! We have a potential solution for you! Could you update the `newrelic_rpm` line in your Gemfile to the following and let us know if that resolves the issue?
 
 ```
 gem 'newrelic_rpm', git: 'https://github.com/newrelic/newrelic-ruby-agent.git', branch: 'bugfix/sinatra-newrelic-ignore-crash'
 ```

**Comment by NC-piercej** [comment]
@kaylareopelle I can confirm that the issue is fixed when using that branch. Thanks for the ultra-quick resolution!

**Comment by kaylareopelle** [comment]
@NC-piercej splendid! You're most welcome! We'll include the change in our upcoming 8.4.0 release. I'll let you know when it's published 😄

**Comment by fallwith** [comment]
Hello @NC-piercej, the 8.4.0 release which resolves this issue is now available on RubyGems. Please note that we will soon be removing the feature branch now that the fix is generally available. Thank for bringing this one to our attention!
