### ISSUE TITLE
[Spike] Improve Performance Suite

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#906]
Update the performance suite to be more compatible with our current needs

Understand how the tests are run:
* Running tests with an iteration flag runs much more quickly than without an iteration flag 
* The duration and object allocation output when running with an iteration flag is much higher than when running without the iteration flag (could this be related to integer division?)

**Comment by fallwith** [comment]
Having both the baseline and comparison (delta producing) runs use a fixed iteration count just makes more sense. Iteration counts are now the default for all suites as of #2140.
