### ISSUE TITLE
Update documentation examples for Rails 7.0 Support

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#907]
### Feature Description
It can be frustrating to find documentation that suits your use case, but end up with an example that continues to raise errors. 

Let's take some time to verify the examples in the Ruby Agent's documentation work on Rails 7.0. All examples should be technically accurate and functional for Rails 7.0 to complete this story. If code changes will take time that exceeds the estimate, reach out to the team to separate changes out into additional issues.

### Documentation to Verify
- [x] [Ruby Custom Metrics](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ruby-custom-metrics/) 
- [x] [Ignoring Specific Transactions](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions/ )
  - [x]  Blocking all instrumentation - transactions blocked.
  - [x] Ignoring specific actions with Rails
    - [x] `:only` 
    - [x] `except` 
  - [x] Ignoring Apdex contributions
  - [x] Block browser instrumentation
  - [x] Ignoring transactions dynamically 
    - [x] NewRelic::Agent.ignore_transaction 
    - [x] NewRelic::Agent.ignore_apdex 
    - [x] NewRelic::Agent.ignore_enduser
  - [x] Ignoring transactions by URL with configuration
- [x] [Sending Handled Errors](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic/ ) 
- [x] [Ruby Custom Instrumentation](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation/)  
  - [x] Tracing in class definitions
  - [x] Tracing initializers
  - [x] Tracing blocks of code
  - [x] Naming transactions

### Additional context
Currently, there is a disclaimer listed at the top of articles with examples that have not been tested with Rails 7.0. This should be removed once examples are tested and, if necessary, updated.

**Comment by kaylareopelle** [comment]
**Team discussion notes**

Size: Small
* Technical accuracy in this story
* Wordsmithing can occur in other stories
* Important to have this done so that we can be clear about what's supported in Rails 7
* If things aren't working in Rails 7 and the time exceeds the estimate, it can go into a different ticket 
* May be able to wrap examples in the #executor blocks to resolve issues if they arise 

Priority: High - important to have a published source of truth about custom instrumentation for our most popular framework
Helping support, ourselves, and our customers be their best advocates by having access to accurate information

**Comment by kaylareopelle** [comment]
@hannahramadan 
* Look at similar documentation
* Review current documentation 
* Make a plan for what needs to change

**Comment by hannahramadan** [comment]
Completed testing documentation examples with Rails7. No issues with any example and Rails7 compatibility. 

Docs PR resolving Rails7 warnings: https://github.com/newrelic/docs-website/pull/11056#pullrequestreview-1252544730

**Comment by kaylareopelle** [comment]
Closing this issue! I think it remained open by accident.
