### ISSUE TITLE
Review ActiveSupport::Notifications methods available for subscription

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#912]
### Feature Description
The Ruby Agent's Rails instrumentation relies on subscribing to events through ActiveSupport::Notifications. This issue involves taking an inventory of the available methods and comparing them with the methods the agent subscribes to. From that point, the assignee should determine if any new methods should be added to our existing instrumentation. Additional issues can be created for that work, or it can be accomplished as part of this issue. 

**Bonus points** for verifying the [Rails Guides article on this topic](https://guides.rubyonrails.org/active_support_instrumentation.html) covers all available instrumented methods.

**Comment by kaylareopelle** [comment]
Size: M 
Priority: Med/High? 
* This change is not breaking anything that exists
* This is a new feature, adding in extra instrumentation, not a bug fix
* This has a clear path to take action to add the information 
* Async, however, provides information that we can provide to customers 
* Possibly an Ignite project to take inventory on the instrumentation and add instrumentation

**Comment by fallwith** [comment]
Investigation and team discussion complete. A new [Rails notifications](https://github.com/newrelic/newrelic-ruby-agent/milestone/43) milestone has been created with the following new issues to track the work that needs to be done:

- #1510 
- #1511 
- #1512
- #1513 
- #1514 
- #1515 
- #1516 
- #1517
