### ISSUE TITLE
Update Team Vault

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#927]
The Vault's permissions strategy is changing. We need to open a PR against our team permissions manifest to update the policy so that we can maintain access to internal tools like Team Store, AWS, etc.

Due: February 15, 2022

Resources: 
[Slack Post - Internal](https://newrelic.slack.com/archives/C027NFCDZ2P/p1643140470079900)

**Comment by angelatan2** [comment]
[Internal only:](https://source.datanerd.us/auth-and-secrets/team-permissions/pull/1458)
