### ISSUE TITLE
browser_monitoring.auto_instrument is duplicated in the a "clean" newrelic.yml

### ISSUE THREAD

**Issue by robotfelix** [newrelic/newrelic-ruby-agent#955]
## Description

I'm just in the middle of updating our New Relic ruby agent version. I downloaded a clean newrelic.yml from the Account Settings page in the web interface and noticed that the `browser_monitoring.auto_instrument` config option is included twice, with ever-so-slightly different documentation and different commented values.

This issue can be seen in the newrelic.yml file on the master branch here: https://github.com/newrelic/newrelic-ruby-agent/blob/7460cedcaa7f084c536bc11d4b9f16b02d8cd0f9/newrelic.yml#L85-L91

## Expected Behavior

`browser_monitoring.auto_instrument` appears once in newrelic.yml. I don't feel qualified to say whether the comment value should be false or true.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]

N/A - no real trouble!

## Steps to Reproduce

N/A - documentation / template config issue only

## Your Environment

N/A

## Additional context

N/A

**Comment by tannalynn** [comment]
Good catch! Thanks for letting us know, we'll take a look and get that updated.
