### ISSUE TITLE
Remove all previously deprecated configuration options

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#957]
In the next major release 9.0.0 of the agent, we should remove all configuration options marked with `deprecated => true` in `default_source.rb`. The replacement configuration options that currently reference these deprecated options should have their default values updated to no longer reference those options as well.

**Comment by tannalynn** [comment]
For our next major release, leave the deprecated configuration options referencing analytic events, as those have been recently deprecated. All other deprecated configuration options should be able to be removed.

**Comment by kaylareopelle** [comment]
Some of these deprecated attributes are called out as such in [this document](https://docs.newrelic.com/docs/apm/agents/ruby-agent/attributes/enable-disable-attributes-ruby/). Let's update it when we work on this ticket.
