### ISSUE TITLE
Spike:  Logger Class Discovery

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#959]
### Is your feature request related to a problem? Please describe.
We've implemented Logging metrics, however there are two more additional features that make up the Logging Initiative.
There is a PR
1. Log Forwarding
2. LiC 

### Feature Description
The goal of this spike is to uncover:
1)  Design for performance
2) Design for sustainability aspects of the initiative

Acceptance criteria:
MMF/Milestone document capturing design decisions, risks, and any dependencies.
Outline of stories to prepare for estimation with the team.
T-shirt size of these stories by the milestone lead.

### Priority
[Must Haver]

**Comment by kaylareopelle** [comment]
All stories noted on the Google Document have been added to GitHub Issues. This can be closed.
