### ISSUE TITLE
GitHub Issues should default to having the "Ruby Engineering Board" project

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#972]
It would be handy to have "Ruby Engineering Board" be the default project for new GitHub Issues.

**Comment by kaylareopelle** [comment]
It looks like we're using "Projects (classic)" and if we plan to continue using the GitHub project, should migrate to the new "Projects" tool. 

Once we do that, we can use a GitHub action to make sure all issues are added to the project when they're created: https://github.com/actions/add-to-project

**Comment by fallwith** [comment]
Closing in favor of https://github.com/newrelic/newrelic-ruby-agent/issues/1951
