### ISSUE TITLE
Implement Data Usage Supportability Metrics Agent Spec

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#976]
The newly approved [Data Usage Supportability Metrics Agent Specs (Internal)](https://source.datanerd.us/agents/agent-specs/blob/main/Data-Usage-Supportability-Metrics.md) needs to be implemented into the Ruby Agent. 

The basics for this spec are already implemented in the codebase with the name `Supportability/invoke_remote_size` metrics defined in `NewRelic::Agent::NewRelicService#record_size_supportability_metrics`, however, the metric names need to be updated to match the new format: 
`Supportability/{language}/Collector/Output/Bytes`, `Supportability/{language}/Collector/{method}/Output/Bytes`

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ruby-Agent-578cc3351c7940044e18b71e/issues/newrelic/newrelic-ruby-agent/976?planning-poker) with ZenHub @kaylareopelle

**Comment by kaylareopelle** [comment]
Closed by #1008
