### ISSUE TITLE
Please implement serverless gcp support

### ISSUE THREAD

**Issue by modosc** [newrelic/newrelic-ruby-agent#981]
### Is your feature request related to a problem? Please describe.
currently we cannot instrument google cloud functions written in ruby.  out of the box something connects to newrelic and creates a project / reports log calls but no instrumentation data is sent.

we can instrument cloud functions written in node (via `NEW_RELIC_SERVERLESS_MODE_ENABLED=true`). 

### Feature Description
we'd like to instrument google cloud functions written in ruby.

### Describe Alternatives
we could port our ruby code to node since this works there

### Priority
Must Have

**Comment by angelatan2** [comment]
Hello @modosc, thank you for submitting a feature request.  I've tagged our Product Manager to take a look at the request.  @elucus.  

** Others who sees this card, please upvote by commenting if this feature is useful to you as well.

**Comment by kaylareopelle** [comment]
Hi @modosc! Out of curiosity, why did you decide to close this issue? Are google cloud functions working with this agent?

**Comment by modosc** [comment]
i'm no longer using cloud functions so this wasn't important anymore.  feel free to reopen if progress was tied to having this issue open?

**Comment by kaylareopelle** [comment]
Thanks for clarifying! I'll verify the status with our product manager and may reopen the issue.
