### ISSUE TITLE
Get Logging metrics into Angler for long term capture 

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#989]
_Duplicate of [LOGGING-7214: Get Logging metrics into Angler for long term capture (Internal)](https://newrelic.atlassian.net/browse/LOGGING-7214)_

In addition to capture in Angler (which goes to Events in some various accounts), we want to turn those via events-to-metrics into long-term form for comparison quarter-over-quarter. 

See [Measuring Success section within Engineering Brief: Logging in Agents (Internal)](https://docs.google.com/document/d/1HG9RD0NAYiLtR8ZFfH0obLbVZiVmQxOt3k8xBz-RZaQ/edit#heading=h.judm544j1nnp) for metrics and datapoints to capture.

**Comment by kaylareopelle** [comment]
Meeting with @rvanderwal-newrelic to discuss implementing these changes into Angler on Monday, February 28.

**Comment by kaylareopelle** [comment]
|Supportability Metric Name|In Agent?|In Angler?|
|---|---|---|
|`Supportability/Logging/{language}/{framework}/{enabled\|disabled}`|NOT YET, will be part of overall application_enabled flag|NOT YET, can still be added to Angler even though it's not in the agent yet|
|`Supportability/Logging/Metrics/{language}/{enabled\|disabled}`|YES|NOT YET|
|`Supportability/Logging/Forwarding/{language}/{enabled\|disabled}`|YES|NOT YET|
|`Supportability/Logging/LocalDecorating/{language}/{enabled\|disabled}`|YES|NOT YET|
|`Supportability/Logging/Forwarding/{Seen\|Sent}`|YES, Dropped is also recorded at the same time|NOT YET|

**Comment by fallwith** [comment]
Angler PR https://source.datanerd.us/agents/angler/pull/291 has been merged
