### ISSUE TITLE
Enforce `TODO:` using Rubocop

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#998]
### Feature Description
Use Rubocop to enforce a standardized `TODO:` format by creating a custom cop

Example here: https://evilmartians.com/chronicles/custom-cops-for-rubocop-an-emergency-service-for-your-codebase 

### Alternatives
* If there is an existing "cop" that can achieve this goal, use it instead.
* Contribute this new "cop" as an option to the Rubocop repository and upgrade to the newest version in this repo.

### Priority
Nice to Have

**Comment by hannahramadan** [comment]
I'm interested in this issue for future work.
