### ISSUE TITLE
Refactor NewRelic::Agent::Agent into smaller services

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#999]
### Is your feature request related to a problem? Please describe.
The `lib/new_relic/agent/agent.rb` file is 1220 lines and counting. It is responsible for initializing the Agent and its instance variables, loading configuration, detecting frameworks, running the harvest cycle, connecting to the New Relic servers and possibly more! This is a lot of responsibility for one file. 

### Feature Description
Let's determine what should remain in NewRelic::Agent::Agent and what additional responsibilities can be moved into other classes.

### Describe Alternatives
Instead of refactoring the entire file in one go, we could separate this out into smaller initiatives to move an individual responsibility to a new class. This may be the safer approach. 

### Additional context
This is how the agent has been organized for a while. This refactor may take a significant effort.

### Priority
Really want

### T-Shirt size

**Comment by tannalynn** [comment]
@kaylareopelle Yeah I can totally do that, I didn't get very far, but i'd be happy to get a pr going for it.
